'use strict';
// ============================================================
//  にゃんこファンタジー 台本（第五章〜エピローグ・おまけ・友情イベント）と、物語の進行
// ============================================================
Object.assign(SCENES, {
  // ================= 第五章　眠れる子猫 =================
  c5_01: { title: '古代遺跡', cast: ['e:sekizou'], bgm: 'field',
    stage: { zone: 'ruins_out', at: [-6, 20], face: 0, cast: { 'e:sekizou': [{ at: [-2.6, 5.4], hidden: true }, { at: [2.4, 5.8], hidden: true }] }, points: { ruins: [12, 2.2, 14] } },
    lines: [
      ['n', 'くろねこ谷の北。森に埋もれるように、古代の遺跡が眠っていた。倒れた柱のあいだに、猫の石像が並んでいる。', { cam: 'look:ruins', dur: 7, look: { all: 'ruins' } }],
      ['shiro', 'すごい……！　これ、何千年も前の猫たちの遺跡よ！', { f: 'joy', g: 'cheer' }],
      ['tama', '……ここ、しってる……ような……。', { f: 'sleepy', g: 'tilt' }],
      ['kuro', '……タマ？', { f: 'serious', to: 'tama' }],
      ['tama', '……ううん。……ねむいだけ。', { f: 'sleepy', g: 'shake' }],
      ['n', '石のねこ像が、ぎぎぎ……と動き出した！', { enter: 'e:sekizou', shake: 0.3, cam: 'wide', r: { all: 'surprise' }, stance: { all: 'ready' } }],
      ['mike', 'わわっ、像が動いた！', { f: 'surprise', g: 'recoil' }],
    ] },
  // 石畳の丘の、大階段を上りきったところ：石の神殿（遺跡）と扉の結界、その前の「つながりの石畳」が見える
  c5_01b: { title: 'つながりの石畳', bgm: 'field',
    stage: { zone: 'ruins_hill', at: [0, -13], face: 0, points: { gate: [0, 4.5, 20], tiles: [0, 0.6, 9] },
      shots: { gate: { pos: [2, 2.2, -8], look: [0, 8.2, 20] }, tiles: { pos: [0, 6.5, -3], look: [0, 0.6, 9] } } },
    lines: [
      ['n', '大階段を上りきると、森の奥に、石の神殿のような遺跡がそびえていた。……遺跡の扉には、うっすらと光る結界が張られている。', { cam: 'gate', dur: 7, look: { all: 'gate' } }],
      ['shiro', '結界……！　外庭の石像たちは、これを守ってたのね。', { f: 'serious', g: 'point' }],
      ['kuro', '……扉の前の石畳。足もとの石が、光るようだ。', { f: 'serious', g: 'think', cam: 'tiles', dur: 6, look: { all: 'tiles' } }],
      ['tama', '……ぜんぶの石を……てを、つなぐ、みたいに……。', { f: 'sleepy', g: 'tilt' }],
      ['mike', '手をつなぐ？　……石と？', { f: 'neutral', g: 'tilt', to: 'tama' }],
      ['shiro', '立て札もあるわ。「始まりの石から、すべての石をひと筆で」……ですって。', { f: 'neutral', g: 'think' }],
      ['n', '（つながりの石畳：始まりの石（足あと）から、すべての石を一度ずつ踏み、最後に終わりの石（星）を踏むと、結界が消える。光った石をまた踏むか、石畳から出ると、やりなおし。ひとつ前の石へもどると、一歩取り消せる。丘のふもとの西、「光の庭」で練習もできる）', { cam: 'tiles', dur: 9 }],
    ] },
  c5_02: { title: '壁画の回廊', bgm: 'dark',
    stage: { zone: 'ruins_in', at: [0, -10], face: 0,
      // 壁画の見る点は、壁画の面のすぐ手前（壁の中に置くと、カメラが壁を突き抜ける）
      points: { mural0: [-25.5, 2.2, 5], mural1: [25.5, 2.2, 5], mural2: [-12, 2.2, 19.5] },
      // 壁画・二（東のくぼみ）と古代文字（北の壁）は、大広間の中から斜めに写す
      shots: { mural1: { pos: [16, 2.4, 0], look: [25.5, 2.2, 5] }, mural2: { pos: [-13.5, 2.6, 10], look: [-12, 1.8, 19.5] } } },
    lines: [
      ['shiro', '見て、壁画よ！　……大きな猫が、樹を抱いて眠ってる。', { f: 'joy', g: 'point', cam: 'look:mural0', dur: 6, look: { all: 'mural0' } }],
      ['n', '大広間の壁には、ほかにも壁画が続いていた。', { cam: 'wide', dur: 5 }],
      ['kuro', '……こっちは、四匹の猫が、樹のまわりで手をつないでいる。', { f: 'serious', g: 'point', cam: 'mural1', dur: 6, look: { all: 'mural1' } }],
      ['mike', '……一匹、すごく小さい。', { f: 'neutral', g: 'tilt' }],
      ['tama', '……。', { f: 'neutral', look: { tama: 'mural1' } }],
      ['shiro', '古代文字もあるわ。えっと……「樹は、猫たちのつながりから生まれた。つながりが絶えるとき、樹は……最後のにゃんこを生む」', { f: 'serious', g: 'think', cam: 'mural2', dur: 7, look: { all: 'mural2' } }],
      ['mike', '……最後のにゃんこ？', { f: 'worry', g: 'tilt' }],
      ['tama', '……。', { f: 'worry', cam: 'tama', close: true }],
      ['kuro', '……行こう。大広間の奥にも、まだ道が続いている。', { f: 'serious', cam: 'wide', dur: 5 }],
    ] },
  // 崩れた回廊の入口の間：白い時の水晶。タマがふれると、遺跡が昔の姿にもどる（シーンの中だけ。もう一度ふれて、今にもどす）
  c5_02b: { title: '時の水晶', bgm: 'dark',
    // 入口の間（南）の白い水晶。北の壁に二つの口：右（right：今は瓦礫・昔に通れる）と、左（left：今は崩れて通れる・昔は石の門）
    // touch：水晶にふれるタマを、水晶の向こう（北）から、顔が見えるように
    stage: { zone: 'ruins_maze', at: [-18, 38], face: 0, points: { crystal: [0, 1.6, 6], left: [-9, 1.5, 12], right: [9, 1.5, 12] },
      shots: { left: { pos: [-9, 3.4, 1], look: [-9, 1.4, 12] }, right: { pos: [9, 3.2, 3], look: [9, 1.4, 12] },
        touch: { pos: [-0.2, 2.1, 9.2], look: [0.7, 1.0, 5.4] } } },
    lines: [
      ['n', '大広間の奥は、崩れかけた回廊だった。入口の間に、白く光る縦長の水晶があって、かすかに鳴っている。', { cam: 'look:crystal', dur: 6, look: { all: 'crystal' } }],
      ['mike', '……奥へ続く口は二つ。でも、右の口は、瓦礫でふさがってるよ。', { f: 'worry', g: 'point', cam: 'right', dur: 6, look: { all: 'right' } }],
      ['tama', '……この水晶……むかしの、におい。', { f: 'sleepy', move: { tama: [1.1, 5.1] }, speed: 1.4, face: { tama: [0, 6] }, look: { mike: 'tama', kuro: 'tama', shiro: 'tama', tama: 'crystal' }, cam: 'touch', dur: 7 }],
      ['n', 'タマが水晶にふれると——', { waitMove: true, face: { tama: [0, 6] }, r: { tama: ['neutral', 'reach'] }, cam: 'keep', later: [0.6, { fx: 'timeshift' }] }],
      ['n', '右の口をふさいでいた瓦礫が、ひとりでに組み上がって、昔の回廊の姿にもどった。', { cam: 'right', dur: 6, look: { all: 'right' } }],
      ['shiro', 'うそ……遺跡が、昔を思い出してる……！？', { f: 'surprise', g: 'surprise' }],
      ['kuro', '……だが、左の口には、さっきまでなかった石の門が立っている。', { f: 'serious', g: 'point', cam: 'left', dur: 6, look: { all: 'left' } }],
      ['mike', 'あっちが通れるようになったら、こっちがふさがっちゃった！？', { f: 'surprise', g: 'tilt' }],
      ['n', 'タマがもう一度ふれると、遺跡は、今の姿にもどった。', { fx: 'timeshift', cam: 'touch', dur: 6, r: { tama: ['neutral', 'reach'] }, look: { mike: 'tama', kuro: 'tama', shiro: 'tama', tama: 'crystal' } }],
      ['shiro', '「今」と「昔」で、通れる道がちがうのね。……奥の小部屋にも、こういう水晶があるかもしれないわ。', { f: 'serious', g: 'think' }],
      ['n', '（時の水晶にふれると、遺跡が「今」と「昔」で切りかわる。今は瓦礫でふさがった道も、昔なら通れる。昔は石の門でふさがっていた道が、今は崩れて通れる。水晶をさがして切りかえながら、奥の封印の扉へ）', { cam: 'wide', dur: 9 }],
    ] },
  c5_03: { title: '封印の扉', bgm: 'dark',
    // ahead：扉へ歩きだすタマを、前（右ななめ前）から。とちゅうで front に切りかえる
    // front：扉の前に着いたタマと、開いていく扉を、扉の正面（タマのうしろ）から。タマが会話の窓に隠れないよう、高めから見下ろす
    stage: { zone: 'ruins_maze', at: [0, -34], face: 0, points: { door: [0, 3.2, 12] }, shots: { ahead: { pos: [2.4, 1.7, 10.4], look: [0, 0.9, 7.2] }, front: { pos: [0, 3.2, 0.8], look: [0, 1.45, 12] } } },
    lines: [
      ['n', '回廊の奥に、封印された大きな扉があった。', { cam: 'look:door', dur: 6, look: { all: 'door' } }],
      ['shiro', '封印の魔法……天才のわたしでも、びくともしないわ。', { f: 'worry', g: 'reach' }],
      ['kuro', '……俺の剣でも、無理だ。', { f: 'serious' }],
      ['tama', '……。', { f: 'neutral', move: { tama: [0, 11.3] }, speed: 1.8, face: { tama: [0, 12] }, look: { all: 'tama', tama: 'door' }, cam: 'ahead', dur: 6, drift: 0.1, later: [5.2, { cam: 'front', dur: 10 }] }],
      ['n', 'タマが扉にふれると、封印の光がやさしく広がり、石の扉が、ゆっくりと奥へ開いていった。', { waitMove: true, face: { tama: [0, 12] }, r: { tama: ['neutral', 'reach'] }, cam: 'keep', later: [0.9, { fx: 'seal:n', r: { mike: 'surprise', kuro: 'surprise', shiro: 'surprise' } }] }],
      ['shiro', '開いた……！？　タマ、どうして……', { f: 'surprise', g: 'surprise' }],
      ['tama', '……わかんない。……扉が、「おかえり」って言った。', { f: 'sleepy', g: 'tilt', face: { tama: 'mike' } }],
      ['shiro', '……回廊の古代文字。「つながりが絶えるとき、樹は……最後のにゃんこを生む」。……まさか。', { f: 'surprise', g: 'think', to: 'tama' }],
      ['tama', '……ぼく？', { f: 'surprise', cam: 'tama', close: true }],
      ['n', '開いた扉の奥から、ひんやりとした風が流れてくる。……奥で、何かが目をさます気配がした。', { cam: 'look:door', dur: 6, look: { all: 'door' } }],
      ['n', '【目的】開いた扉の奥、封印の間へ。', { cam: 'wide', dur: 5 }],
    ] },
  // 封印の間で、祭壇の前の守護神が目をさます（このあと 5-3 の戦い。勝つと c5_04）
  c5_03b: { title: '遺跡の守護神', cast: ['e:guardian'], bgm: 'dark',
    stage: { zone: 'ruins_seal', at: [0, 1], face: 0, cast: { 'e:guardian': { at: [0, 6.6], hidden: true } }, points: { altar: [0, 2, 10] } },
    lines: [
      ['n', '扉の奥は、樹の根をかたどった祭壇の間だった。床いっぱいに、光る根の模様が広がっている。', { cam: 'look:altar', dur: 7, look: { all: 'altar' } }],
      ['mike', 'ここが……封印の間？', { f: 'neutral', g: 'lookUp' }],
      ['tama', '……だれか……いる。', { f: 'worry', look: { all: 'altar' } }],
      ['n', '祭壇の光がふくれあがり、遺跡の守護神が姿を現した！', { enter: 'e:guardian', shake: 0.5, cam: 'wide', stance: { all: 'ready' } }],
      ['e:guardian', '……封印を開けられるのは、最後のにゃんこだけ……。その心、確かめさせてもらおう。'],
      ['kuro', '……来るぞ。', { f: 'serious', stance: { all: 'ready' } }],
    ] },
  c5_04: { title: '樹の秘密', cast: ['e:guardian'], bgm: 'sad',
    stage: { zone: 'ruins_seal', at: [0, 1], face: 0, cast: { 'e:guardian': { at: [0, 5.4] } }, points: { altar: [0, 2, 10] } },
    lines: [
      ['n', '戦いを終えた守護神は、祭壇の前に静かにたたずみ、一行を見つめていた。', { cam: 'wide', dur: 7, look: { all: 'altar' } }],
      ['n', '守護神は、光の文字で語りはじめた。', { cam: 'foe:e:guardian', dur: 6 }],
      ['n', '……にゃんだーの樹は、猫たちの笑い・友情・思い出・優しさ……心のつながりを糧に生きている。', '遺跡の声', { cam: 'wide', dur: 7 }],
      ['n', 'つながりが薄れると、樹は弱り、感情の実は実らなくなる。実らなければ、猫たちはさらに心を閉ざし、つながりは薄れていく。', '遺跡の声'],
      ['n', '樹が枯れかけたとき、樹はひとつの命を生む。樹を救うための子——最後のにゃんこを。', '遺跡の声', { look: { all: 'tama' } }],
      ['n', '最後のにゃんこは、樹と心がつながっている。樹が弱るほど、その子は深く眠る。', '遺跡の声'],
      ['kuro', '……タマがいつも眠っていたのは、そのせいか。', { f: 'serious', look: { kuro: 'tama' } }],
      ['tama', '……ぼく……樹から、生まれたの？', { f: 'surprise', g: 'lookDown' }],
      ['mike', 'タマはタマだよ！　どこから生まれたって、関係ない！', { f: 'angry', g: 'fist', to: 'tama' }],
      ['shiro', '……そうよ。タマは、わたしが面倒見てる、わたしの……仲間なんだから。', { f: 'worry', g: 'handChest' }],
      ['shiro', '……今度は、ぜったいに、手をはなさないんだから。', { f: 'worry', g: 'fist' }],
      ['kuro', '……今度は？', { f: 'serious', g: 'tilt', to: 'shiro' }],
      ['shiro', 'な、なんでもないわよ！', { f: 'shy', g: 'turnAway' }],
      { bond: ['mike', 'tama', 10] },
      ['kuro', '……樹を枯らしているのは、魔王じゃない。世界に広がった……孤独、か。', { f: 'serious', g: 'think' }],
      ['n', '樹の心臓は、いにしえの猫たちが封じた。その扉を開けられるのもまた、最後のにゃんこだけ……。', '遺跡の声'],
      ['n', '樹の根は、世界じゅうの地下をめぐり、その先は「世界の果て」に行きつく。誰の声も届かぬ、音も色もない場所に……。', '遺跡の声'],
      ['n', '……北の魔王もまた、樹の根に巣くう「何か」を知っている……。', '遺跡の声'],
      ['shiro', '魔王が……？', { f: 'surprise' }],
      ['mike', 'じゃあ、魔王に会いに行こう！　笑いの実も、返してもらわなきゃ！', { f: 'serious', g: 'fist' }],
      ['kuro', '……魔王城は、遺跡の東の魔王領だ。', { f: 'serious', g: 'point' }],
      ['tama', '……みんな……いっしょ？', { f: 'worry', g: 'tilt' }],
      ['mike', '当たり前じゃん！', { f: 'joy', g: 'cheer', r: { tama: 'smile' } }],
    ] },

  // ================= 第六章　魔王城へ =================
  c6_01: { title: '魔王領', cast: ['e:mazoku', 'e:kangoshi'], extra: ['mazoku_yukyu'], bgm: 'field',
    stage: { zone: 'demon_land', at: [-2, 24], face: 0,
      cast: { mazoku_yukyu: { at: [0, 2.8], face: 'mike' },
        'e:mazoku': { at: [-2.6, 7], hidden: true }, 'e:kangoshi': { at: [2.6, 7.4], hidden: true } },
      points: { castle: [2, 20, 86] }, shots: { castle: { pos: [-1.4, 3.2, -11], look: [2, 19, 86] } } },
    lines: [
      ['n', '魔王領。紫の空の下、おそろしい魔王城がそびえている。……はずなのだが。', { cam: 'castle', dur: 7, look: { all: 'castle' } }],
      ['mazoku_yukyu', 'あ、どうも。魔王軍の者です。……あの、有給休暇の申請って、どこに出せばいいか知りません？', { f: 'worry', g: 'bow' }],
      ['mike', 'ゆうきゅう？', { f: 'neutral', g: 'tilt' }],
      ['mazoku_yukyu', '休んでも、お給料がもらえるお休みです。……もう三年、申請が通らなくて。', { f: 'sad', g: 'lookDown' }],
      ['shiro', '……ここ、本当に魔王領なの？', { f: 'surprise', g: 'shrug' }],
      ['mazoku_yukyu', 'それに今日はお城で、年に一度の健康診断の日でして……。みんな、城の保健の間に並んでるんです。', { f: 'worry', g: 'explain' }],
      ['mike', 'ぼくたち、魔王に会いに来たんだ！　笑いの実を、返してもらうの！', { f: 'joy', g: 'fist' }],
      ['mazoku_yukyu', '魔王さまに？　それなら、まずお城の受付で、面会の手続きを……。魔王さま、最近ずーっと、ひとりで猫じゃらしで遊んでますけど……', { f: 'neutral', g: 'explain' }],
      ['mazoku_yukyu', 'あっ、これ言っちゃいけないやつだった！　し、侵入者だーー！', { f: 'surprise', g: 'recoil', enter: ['e:mazoku', 'e:kangoshi'], later: [0.5, { exit: 'mazoku_yukyu' }], stance: { all: 'ready' } }],
      ['kuro', '……油断するな。', { f: 'serious' }],
    ] },
  // 魔王城の受付：面会許可証（ハンコの欄が五つ）を受け取る。健康診断と、四天王四人のハンコを集める
  c6_01b: { title: '面会の手続き', extra: ['uketsuke'], bgm: 'field',
    stage: { zone: 'demon_castle', at: [1, 14.2], face: 0, cast: { uketsuke: { at: [1.3, 3], face: 'mike' } } },
    lines: [
      ['n', '魔王城の大広間。……入ってすぐのところに、小さな受付があった。', { cam: 'wide', dur: 6 }],
      ['uketsuke', 'ようこそ、魔王城へ〜。受付のメリーです。ご用件をどうぞ〜。', { f: 'smile', g: 'bow' }],
      ['mike', '魔王に会いに来たんだ！　笑いの実を、返してもらうの！', { f: 'joy', g: 'fist' }],
      ['uketsuke', '魔王さまとの面会ですね〜。では、こちらの「面会許可証」をどうぞ。', { f: 'smile', g: 'offer', hold: { mike: 'card' }, card: 0 }],
      ['shiro', '……ハンコを押す欄が、五つもあるんだけど。', { f: 'neutral', g: 'tilt', card: 0 }],
      ['uketsuke', 'まず、保健の間で健康診断を受けて、「異常なし」のハンコをもらってくださいね〜。', { f: 'smile', g: 'explain', card: 0 }],
      ['kuro', '……なぜ、健康診断がいる。', { f: 'serious', g: 'tilt' }],
      ['uketsuke', '魔王さま、ああ見えて、すぐかぜをひくんです〜。お客さまからうつったら大変なので、面会の前には健康診断が決まりなんですよ。', { f: 'smile', g: 'explain' }],
      ['uketsuke', 'それから、四天王さま四人の「通ってよし」のハンコ。五つそろったら、三階の玉座の間へどうぞ〜。', { f: 'smile', g: 'point', card: 0 }],
      ['kuro', '……戦いに来たんだがな。', { f: 'serious', g: 'lookDown', hold: { mike: null } }],
      ['mike', 'スタンプラリーみたいで、楽しそう！', { f: 'joy', g: 'hop' }],
      ['tama', '……はんこ……ぺたぺた……。', { f: 'smile', g: 'nod' }],
      ['shiro', '……魔王城って、お役所だったのね。', { f: 'smug', g: 'shrug' }],
      ['uketsuke', '保健の間は、大広間の西の廊下の先です。健康診断がすむまで、ほかの扉にはカギがかかってますので〜。', { f: 'smile', g: 'point' }],
      ['uketsuke', 'あ、それから……幹部さんが「侵入者は追い返せ」っていう命令を出したまま、取り消してないんです〜。', { f: 'worry', g: 'explain' }],
      ['uketsuke', '兵のみなさんは命令どおりに襲ってくると思いますけど、許可証は本物ですから、気にしないでくださいね〜。', { f: 'smile', g: 'bow' }],
      ['shiro', '……同じお城の中なのに、連絡が行ってないのね。', { f: 'smug', g: 'shrug' }],
      ['mike', 'じゃあ、戦いながらスタンプラリーだね！', { f: 'joy', g: 'fist' }],
    ] },
  c6_02: { title: '魔王城の健康診断', cast: ['e:kanbu'], extra: ['mazoku_nurse', 'mazoku_nurse2'], bgm: 'field',
    stage: { zone: 'demon_clinic', at: [-12, 8], face: 0,
      cast: { mazoku_nurse: { at: [1.2, 2.2], face: 'mike' }, mazoku_nurse2: { at: [-1.6, 3], face: 'mike' }, 'e:kanbu': { at: [0, 6.5], hidden: true } } },
    lines: [
      ['n', '魔王城の西、保健の間。ここでは、年に一度の健康診断が行われていた。', { cam: 'wide', dur: 6 }],
      ['mazoku_nurse2', 'はーい、次の方〜。……あら、面会の方？　許可証をお持ちなのね。じゃあ、受けていって〜。', { f: 'smile', g: 'wave', card: 0 }],
      ['mazoku_nurse', 'はい、体重計にのってくださいね〜。……あら、あなた、ちょっと魚の食べすぎね。', { f: 'smile', g: 'point', to: 'mike' }],
      ['mike', 'えっ、ぼく！？', { f: 'surprise', g: 'recoil' }],
      ['shiro', '……ぷっ。', { f: 'joy', g: 'laugh' }],
      ['mazoku_nurse', 'そっちの黒い子は……眉間のしわが深いわね〜。もっと笑いましょう。', { f: 'smile', g: 'point', to: 'kuro' }],
      ['kuro', '……余計なお世話だ。', { f: 'shy', g: 'turnAway' }],
      ['mazoku_nurse', '白い子は、夜ふかしのしすぎ。目の下に、くまがあるわよ〜。', { f: 'smile', to: 'shiro' }],
      ['shiro', 'け、研究が忙しいのよ！', { f: 'surprise', g: 'recoil' }],
      ['mazoku_nurse', '小さい子は……一日二十時間は、ちょっと寝すぎかしら〜。', { f: 'worry', to: 'tama' }],
      ['tama', '……まだ……ねむい……。', { f: 'sleepy', g: 'nod' }],
      ['mike', 'なーんだ、みんなもひっかかってるじゃん！', { f: 'joy', g: 'laugh', r: { shiro: 'pout', kuro: 'shy' } }],
      ['e:kanbu', 'こ、こら！　保健係が、侵入者の健康診断をしてどうする！', { enter: 'e:kanbu' }],
      ['mazoku_nurse2', 'でも幹部さん、この子たち、面会許可証を持ってますよ〜。', { f: 'neutral', g: 'point', to: 'e:kanbu' }],
      ['e:kanbu', 'なにっ。……受付め、また勝手に……！　わしの命令は「侵入者は追い返せ」だ！　そんな許可証……いたたた、胃が……。', { shake: 0.2 }],
      ['mazoku_nurse', 'あら幹部さん、胃が痛いなら、あとで診てあげますよ〜。', { f: 'smile', g: 'wave', to: 'e:kanbu' }],
      ['e:kanbu', 'い、今はそれどころではない！　ええい、かかれーっ！', { later: [0.8, { exit: ['mazoku_nurse', 'mazoku_nurse2'] }] }],
      ['kuro', '……来るぞ。', { f: 'serious', stance: { all: 'ready' } }],
    ] },
  c6_02b: { title: '異常なし', cast: ['e:kanbu'], extra: ['mazoku_nurse', 'mazoku_nurse2'], bgm: 'field',
    stage: { zone: 'demon_clinic', at: [-12, 8], face: 0,
      cast: { mazoku_nurse: { at: [1.2, 2.2], face: 'mike' }, mazoku_nurse2: { at: [-1.6, 3], face: 'mike' }, 'e:kanbu': { at: [0.4, 5.6] } } },
    lines: [
      ['e:kanbu', '……ぐ、ぐぬぬ……胃が……。'],
      ['mazoku_nurse', 'はい、幹部さんは胃薬ね〜。……それから猫ちゃんたち、健康診断の結果は……', { f: 'smile', g: 'explain' }],
      ['mazoku_nurse', '「異常なし」！　ハンコ、ぽん♪', { f: 'joy', g: 'cheer', stamp: true, card: 1, fx: 'sparkle:mike' }],
      ['mazoku_nurse', '……ただし、魚はひかえめに、ね？', { f: 'smile', g: 'point', to: 'mike', card: 1 }],
      ['mike', 'はーい……。', { f: 'pout', g: 'lookDown' }],
      ['e:kanbu', 'ハンコが押されてしまったものは、しかたない……。だが、四天王が、そうかんたんに通すものか……！'],
      ['shiro', '四天王って、どんな人たちなの？', { f: 'neutral', g: 'tilt', to: 'mazoku_nurse2' }],
      ['mazoku_nurse2', 'みなさん、いい人ですよ〜。健康診断も、ちゃんと受けてくれますし。……結果は、ちょっとアレでしたけど。', { f: 'smile', g: 'explain' }],
      ['kuro', '……アレ？', { f: 'serious', g: 'tilt' }],
      ['mazoku_nurse2', '最初は、東の兵の詰め所の奥の厨房で、カレーを煮こんでいるグツグツさんね〜。いってらっしゃーい。', { f: 'smile', g: 'wave' }],
    ] },
  // 魔王軍四天王（ゆるい）：倒すと面会許可証に「通ってよし」のハンコ
  c6_k1: { title: '四天王 炎のグツグツ', extra: ['gutsugutsu'], bgm: 'field',
    stage: { zone: 'demon_barracks', at: [-11, -23.5], face: 0, cast: { gutsugutsu: { at: [1.6, 3.6], face: 'mike' } }, points: { pot: [0, 2.2, 10.5] },
      shots: { pot: { pos: [-4.5, 2.6, 0.5], look: [1.2, 1.3, 7] } } },
    lines: [
      ['n', '食堂の奥の厨房に、甘いカレーのにおいがただよっている。かまどの大なべの前で、コック帽の魔族が、おたまを振っていた。', { cam: 'pot', dur: 7, look: { all: 'pot' } }],
      ['gutsugutsu', 'おっと、そこまでだ！　おれは魔王軍四天王のひとり、炎のグツグツ！', { f: 'joy', g: 'point', shake: 0.15 }],
      ['shiro', '炎の……四天王？', { f: 'surprise', g: 'tilt' }],
      ['gutsugutsu', 'そうさ！　この城のかまどの火は、ぜんぶおれが守っている！', { f: 'joy', g: 'fist' }],
      ['kuro', '……かまどの番だな。', { f: 'serious' }],
      ['gutsugutsu', 'ハンコがほしけりゃ、おれを倒してみな！　……の、前に。ちょっと味見してくれない？', { f: 'smile', g: 'offer' }],
      ['mike', 'いいの！？　いただきまーす！', { f: 'joy', g: 'hop' }],
      ['mike', '…………あれ？　味が、しない。', { f: 'neutral', g: 'tilt' }],
      ['gutsugutsu', 'やっぱり……？　健康診断で「塩分ひかえめ」って言われちゃってさあ……。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……ちょっと、かわいそう……。', { f: 'worry' }],
      ['gutsugutsu', 'こうなったら、やけ食い……じゃない、勝負だ！　四天王の火力、見せてやる！', { f: 'angry', g: 'fist', stance: { all: 'ready' } }],
    ] },
  c6_k1b: { title: '減塩のひみつ', extra: ['gutsugutsu'], bgm: 'field',
    stage: { zone: 'demon_barracks', at: [-11, -23.5], face: 0, cast: { gutsugutsu: { at: [1.6, 3.6], face: 'mike' } }, points: { pot: [0, 2.2, 10.5] } },
    lines: [
      ['gutsugutsu', 'まいった！　……いい腕してるな、おまえたち。', { f: 'pained', g: 'lookDown' }],
      ['gutsugutsu', 'ほら、約束のハンコだ。……通ってよし！', { f: 'joy', g: 'point', stamp: true, card: 2 }],
      ['mike', 'ねえ。塩のかわりに、魚の骨でだしをとるといいよ。魚屋のおばちゃんが、いつもやってるんだ！', { f: 'smile', g: 'explain' }],
      ['gutsugutsu', '魚の骨で、だし……！？　その手があったか！', { f: 'surprise', g: 'recoil' }],
      ['shiro', '……ミケって、魚のことだけは本当にくわしいわね。', { f: 'smug', g: 'shrug' }],
      ['mike', 'へへん！', { f: 'joy', g: 'cheer' }],
      ['gutsugutsu', '恩に着るぜ！　……次の四天王は、地下の牢屋で寝てる、ネムネムだ。', { f: 'joy', g: 'explain' }],
      ['gutsugutsu', 'ああ、あいつはちょっとやそっとじゃ起きないぞ。がんばれよ！', { f: 'smile', g: 'wave' }],
    ] },
  c6_k2: { title: '四天王 眠りのネムネム', extra: ['nemunemu'], bgm: 'field',
    stage: { zone: 'demon_cellar', at: [-23.5, -18], face: 270, wide: { pos: [-2.2, 2.2, -2.4], look: [0.6, 0.6, 3.2] },
      cast: { nemunemu: { at: [1.6, 6.7], y: 0.25, face: 'mike', stance: 'sleep' } } },
    lines: [
      ['n', '地下の牢屋。いちばん奥の牢の、わらの寝床で、大きな魔族がすやすやと眠っていた。', { cam: 'wide', dur: 6, fx: 'zzz:nemunemu' }],
      ['shiro', '……四天王が、牢屋で寝てる。', { f: 'neutral', g: 'shrug' }],
      ['mike', 'おーい！　ハンコちょうだーい！', { f: 'joy', g: 'wave' }],
      ['nemunemu', '……ぐう……。', { f: 'sleepy', fx: 'zzz:nemunemu' }],
      ['kuro', '……起きろ。', { f: 'serious', g: 'point' }],
      ['nemunemu', '……すぴー……。', { f: 'sleepy', fx: 'zzz:nemunemu' }],
      ['tama', '……わかる……。ここ、しずかで……ひんやりして……。', { f: 'sleepy', stance: { tama: 'sleep' }, fx: 'zzz:tama' }],
      ['shiro', 'タマまで寝ないで！', { f: 'angry', g: 'point', to: 'tama' }],
      ['mike', 'そうだ！　……ごはんだよーーっ！', { f: 'joy', g: 'cheer' }],
      ['nemunemu', 'ごはん！？', { f: 'surprise', stance: { nemunemu: 'idle', tama: 'idle' }, shake: 0.2, r: { tama: 'surprise' } }],
      ['nemunemu', '……なんだ、ごはんじゃないのか……。おれは四天王、眠りのネムネム……。', { f: 'sleepy', g: 'lookDown' }],
      ['nemunemu', '夜勤明けでね……。寝室は、みんなのいびきがうるさいから、ここで寝てる……。', { f: 'sleepy', g: 'explain' }],
      ['kuro', '……四天王の寝床が、牢屋か。', { f: 'serious' }],
      ['nemunemu', 'ハンコ……？　おれに勝ったら……むにゃ……勝負だ……ぐう。', { f: 'sleepy', g: 'nod', stance: { all: 'ready' } }],
    ] },
  c6_k2b: { title: 'ぐっすり', extra: ['nemunemu'], bgm: 'field',
    stage: { zone: 'demon_cellar', at: [-23.5, -18], face: 270, wide: { pos: [-2.2, 2.2, -2.4], look: [0.6, 0.6, 3.2] },
      cast: { nemunemu: { at: [1.2, 4.4], face: 'mike' } } },
    lines: [
      ['nemunemu', '……ふあぁ。……よく動いたら、よく眠れそう……。', { f: 'sleepy', g: 'lookUp' }],
      ['nemunemu', 'ほい……通ってよし……。', { f: 'sleepy', g: 'nod', stamp: true, card: 3 }],
      ['shiro', '……ハンコ、まがってるわよ。', { f: 'neutral', g: 'point', card: 3 }],
      ['nemunemu', '……味があって、いいだろ……。次は、中庭のチョキチョキじいさん……ぐう。', { f: 'sleepy', stance: { nemunemu: 'sleep' }, fx: 'zzz:nemunemu' }],
      ['mike', '……寝ちゃった。', { f: 'neutral', g: 'tilt' }],
      ['tama', '……おやすみ……。', { f: 'smile', g: 'wave' }],
      ['kuro', '……タマ。おまえは寝るな。行くぞ。', { f: 'serious', g: 'nod' }],
    ] },
  c6_k3: { title: '四天王 風のチョキチョキ', extra: ['chokichoki'], bgm: 'field',
    stage: { zone: 'demon_court', at: [17, -5], face: 0, cast: { chokichoki: { at: [2.5, 3.8], face: 'mike' } }, points: { bed: [3, 1.2, 7] } },
    lines: [
      ['n', '中庭。猫じゃらしの花壇の前で、大きなはさみを持った年寄りの魔族が、葉を一枚ずつそろえていた。', { cam: 'look:bed', dur: 7, look: { all: 'bed' } }],
      ['chokichoki', 'おや、お客さんかい。わしは四天王のひとり、風のチョキチョキ。この庭の手入れをまかされておる。', { f: 'gentle', g: 'nod' }],
      ['shiro', '風の四天王なのに、庭師なの？', { f: 'neutral', g: 'tilt' }],
      ['chokichoki', 'ほっほっ。落ち葉を集めるには、風がいちばんじゃよ。', { f: 'smile', g: 'explain' }],
      ['chokichoki', 'この猫じゃらしは、魔王さまのために育てておるのじゃ。……今年は、よう育ったのう。', { f: 'gentle', look: { chokichoki: 'bed' } }],
      ['chokichoki', '……もっとも、いっしょに遊ぶ相手が、おらんのじゃが。', { f: 'sad', g: 'lookDown' }],
      ['mike', '……魔王って、ひとりで遊んでるの？', { f: 'worry', g: 'tilt' }],
      ['chokichoki', '……おっと、年寄りはしゃべりすぎていかん。ハンコがほしければ、腕前を見せてもらおうかの！', { f: 'serious', g: 'raise', look: { chokichoki: 'mike' }, stance: { all: 'ready' } }],
    ] },
  c6_k3b: { title: 'じいさんの猫じゃらし', extra: ['chokichoki'], bgm: 'field',
    stage: { zone: 'demon_court', at: [17, -5], face: 0, cast: { chokichoki: { at: [2.5, 3.8], face: 'mike' } }, points: { bed: [3, 1.2, 7] } },
    lines: [
      ['chokichoki', 'ほっほっ、見事じゃ。……通ってよし。', { f: 'smile', g: 'nod', stamp: true, card: 4 }],
      ['chokichoki', 'それと……これを持っていきなさい。', { f: 'gentle', g: 'offer' }],
      ['n', 'チョキチョキは、花壇でいちばん立派な猫じゃらしを一本切って、ミケに手わたした。', { hold: { mike: 'jarashi' }, fx: 'sparkle:mike' }],
      ['chokichoki', '魔王さまに会ったら……一度、それを振ってみておくれ。', { f: 'gentle', g: 'explain' }],
      ['mike', '？　……うん、わかった！', { f: 'joy', g: 'nod' }],
      ['kuro', '……武器には、見えんな。', { f: 'serious', g: 'tilt' }],
      ['chokichoki', '最後の四天王は、2F の回廊におる、まとめ役のドドンじゃ。……ちょうど今朝、有給の温泉から帰ってきたところでな。', { f: 'smile', hold: { mike: null } }],
      ['shiro', '……四天王が、有給？', { f: 'surprise', g: 'recoil' }],
    ] },
  c6_k4: { title: '四天王 大地のドドン', extra: ['dodon'], bgm: 'field',
    stage: { zone: 'demon_castle_2f', at: [0, -15.2], face: 0, cast: { dodon: { at: [0, 4.6], face: 'mike' } } },
    lines: [
      ['n', '三階への階段の前。浴衣すがたの大きな魔族が、腕を組んで待ちかまえていた。……頭には、手ぬぐいがのっている。', { cam: 'wide', dur: 7 }],
      ['dodon', 'よく来たな！　わしは魔王軍四天王のまとめ役、大地のドドン！', { f: 'smug', g: 'fist', shake: 0.3 }],
      ['mike', '……なんで浴衣なの？', { f: 'neutral', g: 'tilt' }],
      ['dodon', '有給で、温泉に行っておってな。今朝、帰ってきたところだ。……いい湯だったぞ。', { f: 'smile', g: 'nod' }],
      ['shiro', '……まとめ役が、いちばんくつろいでるじゃない。', { f: 'smug', g: 'shrug' }],
      ['dodon', 'まずは許可証を見せてもらおう。……健康診断よし。グツグツよし。ネムネムは……まがっておるが、よかろう。チョキチョキよし。', { f: 'serious', g: 'nod', card: 4 }],
      ['dodon', 'ふむ、手続きはきちんとしておる。感心だ。……では、これは土産だ。食え。', { f: 'smile', g: 'offer' }],
      ['n', 'ドドンは、一匹ずつに温泉まんじゅうを配った。', { hold: { mike: 'manju' }, cam: 'wide', dur: 5 }],
      ['tama', '……あまくて……おいしい……。', { f: 'joy', g: 'nod' }],
      ['kuro', '……戦うんじゃないのか。', { f: 'serious', g: 'tilt' }],
      ['dodon', 'もちろん戦う！　腹ごしらえは、戦いの基本だからな。', { f: 'joy', g: 'laugh' }],
      ['dodon', 'わしのハンコは、わしを倒した者にしか押さん！　温泉で温まったこの体、受けてみよ！', { f: 'angry', g: 'fist', hold: { mike: null }, stance: { all: 'ready' }, shake: 0.3 }],
    ] },
  c6_k4b: { title: 'いい湯だった', extra: ['dodon'], bgm: 'field',
    stage: { zone: 'demon_castle_2f', at: [0, -15.2], face: 0, cast: { dodon: { at: [0, 4.6], face: 'mike' } } },
    lines: [
      ['dodon', 'ぬう……！　はっはっは、見事！　……有給明けの体には、ちとこたえたわい。', { f: 'pained', g: 'laugh' }],
      ['dodon', '約束だ。……通ってよし！', { f: 'joy', g: 'point', stamp: true, card: 5 }],
      ['shiro', '……ハンコ、いちばん大きいわね。', { f: 'neutral', g: 'point', card: 5 }],
      ['dodon', 'まとめ役だからな！', { f: 'smug', g: 'fist', card: 5 }],
      ['dodon', '……勇者たちよ。魔王さまは、ああ見えて、ずっとお客を待っておられる。……遊んで、いや、会ってさしあげてくれ。', { f: 'gentle', g: 'nod' }],
      ['mike', 'うん！　まかせて！', { f: 'joy', g: 'cheer' }],
      ['n', '面会許可証のハンコが、五つそろった。……三階の玉座の間は、もうすぐそこだ。', { cam: 'wide', dur: 6, card: 5 }],
    ] },
  c6_03: { title: '魔王', bgm: 'boss',
    stage: { zone: 'demon_throne', at: [0, -12], face: 0, host: 'maou',
      cast: { maou: { at: [0, 3.6], face: [0, 6], item: 'jarashiUp', stance: 'jarashi' } } },
    lines: [
      ['n', '玉座の間。大きなクッションの前で、黒い猫がひとり、猫じゃらしにじゃれていた。', { cam: 'maou', dur: 6, fx: 'lure:maou' }],
      ['maou', 'にゃっ、にゃっ……ふふ、捕まえたぞ……にゃっ——', { f: 'joy', g: 'laugh' }],
      ['n', '……目が合った。', { face: { maou: 'mike' }, cam: 'wide', dur: 4 }],
      ['maou', '…………。', { f: 'surprise', cam: 'maou', close: true }],
      ['maou', '……見たな。', { f: 'shy' }],
      ['mike', '……見ちゃった。', { f: 'surprise' }],
      ['maou', 'い、今のは違う！　余は魔王である！　これは、その……鍛錬だ！', { f: 'angry', g: 'point', hold: { maou: null }, stance: { maou: 'armsCrossed' } }],
      ['shiro', '猫じゃらしの？', { f: 'smug', g: 'tilt' }],
      ['kuro', '……鍛錬。', { f: 'serious' }],
      ['maou', 'ええい、黙れ！　……だいたい、そなたら、どうやってここまで来た。玉座の間へは、面会の手続きが……', { f: 'angry', g: 'point' }],
      ['mike', 'してきたよ！　ほら、ハンコ五つ！', { f: 'joy', g: 'offer', hold: { mike: 'card' }, card: 5 }],
      ['maou', '……！？　健康診断に……四天王のハンコまで……全部、そろっておる……。', { f: 'surprise', cam: 'maou', close: true, card: 5 }],
      ['maou', '……この手続きを最後までやりとげた者は、そなたらが、はじめてだ……。', { f: 'shy', g: 'lookDown' }],
      ['shiro', '……なんで照れてるのよ。', { f: 'neutral', g: 'tilt', hold: { mike: null } }],
      ['maou', 'て、照れてなどおらぬ！　……よく来たな、勇者ども。余は、この世界を滅ぼす者だ！', { f: 'smug', g: 'raise', shake: 0.3 }],
      ['mike', '笑いの実を返して！　ニャハハ王国のみんなが、困ってるんだ！', { f: 'angry', g: 'fist' }],
      ['maou', 'ふん……返してほしくば、余を倒してみよ！', { f: 'angry', stance: { maou: 'ready', all: 'ready' }, cam: 'wide' }],
      ['n', '（ヒント：チョキチョキにもらった猫じゃらし……。マオウに「はなす」を使うと、ミケが見せる。四天王にも「はなす」は効くかもしれない。）', { cam: 'wide', dur: 5 }],
    ] },
  c6_04: { title: '魔王の孤独', bgm: 'sad',
    stage: { zone: 'demon_throne', at: [0, -12], face: 0, host: 'maou', cast: { maou: { at: [0, 3], stance: 'kneel', face: 'mike', f: 'pained' } },
      shots: { laugh: { pos: [2.6, 1.7, 5.6], look: [-0.3, 0.7, 1.2] } } },
    lines: [
      ['maou', '……ぐ……余が、負けるとは……。', { f: 'pained', g: 'lookDown' }],
      ['mike', 'ねえ。どうして、世界を滅ぼそうとしたの？', { f: 'sad', g: 'tilt' }],
      ['maou', '…………。', { f: 'sad', g: 'lookDown' }],
      ['maou', '……寂しいから。', { f: 'sad', cam: 'maou', close: true, r: { all: 'surprise' } }],
      ['maou', '余と遊んでくれる者がいない。', { f: 'cry' }],
      ['maou', '……「世界を滅ぼす」と言えば、誰かが城まで来てくれると思った。……勇者でも、よかったのだ。', { f: 'sad', g: 'lookDown' }],
      ['maou', '……面会の手続きを、うんと面倒にしたのも余だ。どうせ誰も来ぬなら、来ないのは手続きのせいだと……思いたかった。', { f: 'sad', g: 'lookDown' }],
      ['shiro', '……面倒くさい魔王ね。', { f: 'sad', g: 'shrug' }],
      ['maou', '部下どもは、余を怖がるか、有給をほしがるばかり。……笑いの実を盗んだのも、その実があれば、ひとりでも笑えると思ったからだ。', { f: 'sad', hold: { maou: 'fruitGray' } }],
      ['maou', '……だが、ひとりで持っていても、実は灰色になるばかりだった。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……マオウも……さみしかったんだね。', { f: 'sad', move: { tama: [0.5, 2] } }],
      ['maou', '……ふん。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'じゃあ、ぼくたちと遊ぼうよ！', { f: 'joy', g: 'offer', hold: { mike: 'jarashi' } }],
      ['maou', '……！　そ、それは……！', { f: 'surprise', fx: 'lure:maou', stance: { maou: 'idle' } }],
      ['maou', '……ぬう……卑怯なり……。', { f: 'shy', g: 'pout', r: { shiro: ['joy', 'laugh'], kuro: 'smile' } }],
      ['maou', '……ふ……ふふっ……。……にゃははっ！', { f: 'joy', g: 'laugh' }],
      ['n', 'つられて、ミケたちも笑い出した。玉座の間に、にぎやかな笑い声がひびく。', { cam: 'laugh', dur: 6, face: { maou: 'mike' },
        r: { mike: ['joy', 'laugh'], shiro: ['joy', 'laugh'], tama: ['joy', 'laugh'], kuro: ['smile', 'nod'], maou: ['joy', 'laugh'] } }],
      ['mike', 'あははっ！　マオウ、笑うとかわいいじゃん！', { f: 'joy', g: 'laugh', r: { shiro: ['joy', 'laugh'], tama: ['joy', 'laugh'] } }],
      ['kuro', '……ふっ。', { f: 'smile', g: 'turnAway' }],
      ['n', 'そのとき、マオウの手の中で、灰色だった笑いの実が、ほんのりと光りはじめた。', { hold: { maou: 'fruit' }, fx: 'sparkle:maou', cam: 'maou', close: true }],
      ['shiro', '見て、実が光ってる……！', { f: 'surprise', g: 'point' }],
      ['shiro', '……そうか。笑いの実は、だれかといっしょに笑うと光る実なのよ。ひとりきりで持っていたら、光らないのは当たり前だわ。', { f: 'serious', g: 'explain' }],
      ['maou', '……余が、そなたらと笑ったから……か。', { f: 'surprise', g: 'lookDown' }],
      ['tama', '……みんなで笑うと……あったかいね……。', { f: 'smile', g: 'nod' }],
      ['mike', 'ニャハハ王国のみんなも、この実があれば、また笑えるよ！', { f: 'joy', g: 'cheer' }],
      ['maou', '……勇者よ。樹の根元には、何かがいる。……ずっと余に「ひとりでいい」とささやいてきた、黒い何かが。', { f: 'serious', hold: { mike: null } }],
      ['kuro', '……「ひとりでいい」……。', { f: 'serious', g: 'lookDown', cam: 'kuro', close: true }],
      ['kuro', '……ひとつ聞く。昔、黒影洞窟で、四匹の猫を襲ったのは、お前の兵か。', { f: 'serious', to: 'maou' }],
      ['maou', '黒影洞窟？　余の兵は、あそこへは近づかぬ。……あそこにも、その黒い何かが巣くっておる。', { f: 'serious', g: 'shake' }],
      ['kuro', '……俺たちを襲ったのは、魔王軍じゃなかったのか。', { f: 'surprise', cam: 'kuro', close: true, r: { mike: 'worry' } }],
      ['maou', '余の兵は、有給をほしがるばかりの者たちだ。城の外で戦をしたことなど、一度もない。', { f: 'sad', g: 'shrug' }],
      ['mike', 'クロ……。', { f: 'worry', g: 'reach', to: 'kuro' }],
      ['kuro', '……そうか。……本当の敵は、樹の根元にいるんだな。', { f: 'serious', g: 'nod' }],
      ['maou', '笑いの実は、王国へ返そう。……光った実のほうが、きっと喜ばれる。', { f: 'gentle', g: 'nod', hold: { maou: 'fruit' } }],
      ['maou', '……勘違いするな。余は、退屈しのぎについていくだけだ。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'あ、そうだ！　マオウ、魔王領で会ったベルの有給、通してあげてね！　三年も通ってないんだって。', { f: 'joy', g: 'point' }],
      ['maou', '……有給？　……そういえば、申請書が山になっておったな。……よかろう。皆、好きなだけ休むがよい。', { f: 'neutral', g: 'nod' }],
      ['n', 'その日、魔王城では、三年分の有給がいっせいに通ったという。', { cam: 'wide', dur: 5 }],
      { give: 'maou' },
      ['mike', 'よろしくね、マオウ！', { f: 'joy', g: 'cheer' }],
      ['maou', '……ふん。……よろしく、してやらんこともない。', { f: 'shy', g: 'nod' }],
      ['n', '笑いの実は、魔族兵たちの手で、ニャハハ王国に届けられた。一行は、にゃんだーの樹の根元へ向かう。', { cam: 'wide', dur: 7 }],
    ] },

  // ================= 第七章　最後のにゃんこ =================
  c7_01: { title: 'にゃんだーの樹', bgm: 'sad',
    stage: { zone: 'tree_root', at: [0, -20], face: 180, points: { tree: [0, 30, 60] } },
    lines: [
      ['n', 'ぽかぽか村の南、丘の向こう。にゃんだーの樹は、灰色の葉を、音もなく落とし続けていた。', { cam: 'look:tree', dur: 8, look: { all: 'tree' } }],
      ['tama', '……樹が……ないてる。', { f: 'sad', g: 'lookUp' }],
      ['mike', 'こんなに、弱ってたなんて……。', { f: 'sad' }],
      ['kuro', '……旅の始まりの夜。俺は、ひとりでここを調べていた。', { f: 'serious', look: { kuro: 'tree' } }],
      ['kuro', '……てっぺん近くの枝の先に、友情の実がひとつだけ、ついていた。今年、この樹に残っていた、最後の友情の実だ。', { f: 'serious', g: 'lookUp' }],
      ['kuro', '……まだ熟してもいないのに、軸がちぎれかけていた。落ちたら、割れる。……取ろうと、枝の先まで手を伸ばした。', { f: 'serious', g: 'reach' }],
      ['kuro', '……そこで、足が滑った。落ちながら、とっさに実をつかんだ。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'こ、この樹のてっぺんで！？', { f: 'surprise', g: 'lookUp', look: { mike: 'tree' } }],
      ['kuro', '……ぶら下がった俺の重さで、枝が大きくしなって——いきおいよく、はね返った。', { f: 'serious', g: 'raise' }],
      ['kuro', '……そのはずみで、軸が折れた。実ごと、空へ放り出されて……光る実にしがみついたまま、夜空を飛んで……気がついたら、お前の村の丘だった。', { f: 'serious', g: 'point' }],
      ['shiro', 'むちゃくちゃよ……。', { f: 'surprise', g: 'shrug' }],
      ['kuro', '……思ったより、遠かった。', { f: 'shy', g: 'turnAway' }],
      ['mike', '……クロ、その実を、守りたかったんだね。', { f: 'gentle', to: 'kuro' }],
      ['kuro', '……結局、割ってしまったがな。', { f: 'sad', g: 'lookDown' }],
      ['mike', 'でも、そのおかげで、ぼくたち会えたんだよ！', { f: 'joy', g: 'hop' }],
      ['kuro', '……ふん。', { f: 'shy', g: 'turnAway', r: { shiro: 'smile', tama: 'smile' } }],
      ['maou', '……根もとの南から、あの声がする。', { f: 'serious', g: 'point', look: { all: [0, 2, 40] } }],
      ['n', '【目的】根もとの南、根のトンネルの奥へ。', { cam: 'wide', dur: 5 }],
    ] },
  c7_01b: { title: '封印の扉', cast: ['e:kakera'], bgm: 'dark',
    stage: { zone: 'tree_root', at: [0, 33], face: 180, cast: { 'e:kakera': [{ at: [-1.8, 5.4], hidden: true }, { at: [1.8, 5.8], hidden: true }] }, points: { door: [0, 2.2, 7.5] },
      // follow：歩きだすタマを、一行のうしろから。front：扉の前に着いたタマと、開いていく扉を、タマのうしろから
      shots: { follow: { pos: [1.0, 1.9, -2.2], look: [0, 1.0, 4.5] }, front: { pos: [1.7, 2.9, 1.6], look: [0, 1.2, 5.8] } } },
    lines: [
      ['n', '根のトンネルの奥に、古い封印の扉があった。', { cam: 'look:door', dur: 6, look: { all: 'door' } }],
      ['maou', '……余も、あの声をたどって、ここまでは来た。だが、この扉だけは開かなんだ。', { f: 'serious', g: 'point' }],
      ['kuro', '……俺もだ。何度調べても、びくともしなかった。', { f: 'serious', g: 'nod' }],
      ['shiro', '世界中の猫が樹を調べても、何も見つからなかったわけね。……樹を守るための封印が、中に入りこんだものまで隠してたんだわ。', { f: 'serious', g: 'think' }],
      ['tama', '……この扉も、「おかえり」って、言ってる。', { f: 'gentle', g: 'reach', move: { tama: [0, 6.6] }, speed: 1.2, face: { tama: [0, 7.5] }, look: { all: 'tama', tama: 'door' }, cam: 'follow', dur: 5, later: [4.2, { cam: 'front', dur: 10 }] }],
      ['n', 'タマがふれると、封印の扉は、静かに開いた。', { waitMove: true, face: { tama: [0, 7.5] }, look: { all: 'tama', tama: 'door' }, fx: 'sparkle:tama', later: [0.9, { fx: 'seal:b', r: { mike: 'surprise', kuro: 'surprise', shiro: 'surprise' } }], cam: 'keep', r: { tama: ['neutral', 'reach'] } }],
      ['maou', '……扉の奥から、あの声がする。', { f: 'serious', g: 'point' }],
      ['n', '扉の奥から、黒いかけらがあふれ出した！　一行は、根もとの広場まで押しもどされる——', { fx: 'shadow', enter: 'e:kakera', cam: 'wide', stance: { all: 'ready' } }],
    ] },
  c7_02: { title: '樹の地下', cast: ['e:utsuro'], bgm: 'dark',
    stage: { zone: 'tree_under', at: [0, -45], face: 180, cast: { 'e:utsuro': { at: [0, 6], hidden: true } } },
    lines: [
      ['n', '封印の扉の奥。樹の根の下には、光る樹液が流れる、広い地下が広がっていた。', { cam: 'wide', dur: 7 }],
      ['shiro', '……静かすぎる。誰の声も、届かないみたい。', { f: 'worry' }],
      ['tama', '……根っこが、さむいって言ってる。……光が、ほしいって。', { f: 'sad', g: 'lookDown' }],
      ['kuro', '……来るぞ。', { f: 'serious', enter: 'e:utsuro', stance: { all: 'ready' } }],
    ] },
  c7_02b: { title: '影の回廊', bgm: 'dark',
    stage: { zone: 'tree_under_2', at: [0, -40], face: 180 },
    lines: [
      ['n', '石段を下りると、うす暗い回廊が続いていた。天井の割れ目から、ところどころ、光が差しこんでいる。', { cam: 'wide', dur: 7 }],
      ['mike', 'あれ？　ぼくの影……いま、ぼくとちがう動きをしなかった？', { f: 'surprise', g: 'point' }],
      ['shiro', '……わたしの影も、ふるえてる。まるで、足もとからはなれたがってるみたい。', { f: 'worry', g: 'recoil' }],
      ['n', '（どこからか、ささやき声がする）……ひとりで、いいよ。……ひとりなら、だれにも、きずつけられない。', { fx: 'darkness', cam: 'wide', dur: 6 }],
      ['kuro', '……この感じ。……ひとりで樹を調べていたころの、俺の気持ちに、似ている。', { f: 'serious', g: 'lookDown' }],
      ['tama', '……影は、ひとりぼっちの気持ち。……ぼくたちの中の。……はなれていっても、ちゃんと、つれて帰ってあげなきゃ。', { f: 'gentle', g: 'handChest' }],
      ['maou', '……影というものは、光をきらう。……ひだまりには、入れぬであろうな。', { f: 'serious', g: 'explain' }],
      ['mike', 'よーし！　影も、いっしょに連れていこう！', { f: 'joy', g: 'cheer' }],
      ['n', '【目的】部屋に入ると、先頭の子の影が足もとからはなれ、鏡うつしに動く。自分は金色の輪へ、影は紫の輪へ。いっしょに入れると、影がもどってくる。', { cam: 'wide', dur: 7 }],
    ] },
  c7_02c: { title: '樹の心臓', bgm: 'sad',
    stage: { zone: 'tree_under_3', at: [1, -27], face: 180, points: { heart: [0, 4.8, 14] } },
    lines: [
      ['n', '根のアーチをくぐると、天井の見えないほど高い、丸い広間に出た。……その中央で、根に吊られた大きな実のようなものが、ゆっくりと脈打っている。', { cam: 'look:heart', dur: 8, look: { all: 'heart' } }],
      ['tama', '……樹の、心臓。……どくん、どくん、って。……でも、すごく、弱い。', { f: 'sad', g: 'handChest' }],
      ['shiro', '床の根が、鼓動のたびに光ってる……。心臓から、樹じゅうに、なにかを送ってるのね。', { f: 'worry', g: 'think' }],
      ['kuro', '……世界じゅうの猫の笑いや思い出は、根をつたって、ここへ集まってくるのか。', { f: 'serious', g: 'lookUp' }],
      ['maou', '……天井の実は、みな色がぬけておる。……ここまで、届かなくなっておるのだ。', { f: 'serious', g: 'point' }],
      ['mike', '……行こう。心臓のそばに、なにかいる。', { f: 'serious', g: 'fist' }],
      ['n', '【目的】広間の奥、樹の心臓のもとへ。', { cam: 'wide', dur: 5 }],
    ] },
  c7_03: { title: 'コドク', cast: ['e:kodoku_kage'], bgm: 'boss',
    stage: { zone: 'tree_under_3', at: [0, 2], face: 180, cast: { 'e:kodoku_kage': { at: [0, 8] } }, points: { heart: [0, 3.4, 14] } },
    lines: [
      ['n', '樹の心臓の前に、黒い影がうずくまっていた。', { fx: 'darkness', cam: 'wide', dur: 7 }],
      ['e:kodoku_kage', '……来たか。つながりなどという、はかないものを抱えて。'],
      ['mike', 'きみが……樹を枯らしてるの？', { f: 'serious' }],
      ['e:kodoku_kage', '私はコドク。世界に広がった、孤独そのもの。……お前たちの心の中にも、私はいる。'],
      ['e:kodoku_kage', '両親を失った、ひとりの夜。仲間を失った、ひとりの朝。救えなかった、あの日。……遊び相手のいない、長い時間。', { r: { mike: 'pained', kuro: 'sad', shiro: 'worry', maou: 'sad' } }],
      ['shiro', '……どうして、それを……。', { f: 'surprise', g: 'bothChest' }],
      ['kuro', '……黒影洞窟の闇。……あれも、お前か。', { f: 'angry', to: 'e:kodoku_kage' }],
      ['e:kodoku_kage', 'そうだ。お前の仲間を闇に沈めたのは、私だ。……お前だけを残してな。'],
      ['kuro', '……なぜ、俺だけ。', { f: 'angry', stance: { kuro: 'ready' } }],
      ['e:kodoku_kage', 'ひとりにするためだ。……樹の上で、ひとりで調べていたお前に、私は何度もささやいた。「ひとりでいい」と。'],
      ['kuro', '……あの声は……俺の声じゃ、なかったのか。', { f: 'surprise', cam: 'kuro', close: true, r: { all: 'surprise' } }],
      ['mike', '……だから、クロ、最初に会ったとき「一人でいい」って……。', { f: 'worry', to: 'kuro' }],
      ['e:kodoku_kage', 'ひとりでいれば、傷つかない。……さあ、ひとりになれ。', { shake: 0.5 }],
      ['mike', 'ならない！', { f: 'angry', stance: { all: 'ready' } }],
    ] },
  c7_04: { title: '最後のにゃんこ', cast: ['e:kodoku_kage'], bgm: 'sad',
    stage: { zone: 'tree_under_3', at: [0, 2], face: 180, cast: { 'e:kodoku_kage': { at: [0, 9], hidden: true } }, points: { heart: [0, 3.4, 14] } },
    lines: [
      ['n', '影は散った。……だが、すぐにまた、闇が集まりはじめる。', { fx: 'shadow:heart', cam: 'wide', dur: 6 }],
      ['maou', '……倒しても、消えぬのか。', { f: 'serious' }],
      ['kuro', '……世界中の孤独が、こいつの力になっている。', { f: 'serious' }],
      ['mike', '……ぼくが、もっと強ければ……。', { f: 'pained', g: 'fist', cam: 'mike', close: true }],
      ['tama', '……ねえ、みんな。', { f: 'gentle', move: { tama: [0, 3] }, look: { all: 'tama' } }],
      ['tama', '……ぼく、わかったんだ。……ぼくが、何のために生まれてきたのか。', { f: 'gentle', g: 'lookUp', look: { tama: 'heart' } }],
      ['tama', 'ぼくが樹になればいいんだよ。', { f: 'smile', face: { tama: 'mike' }, cam: 'tama', close: true, r: { all: 'surprise' } }],
      ['tama', 'ぼくが樹にとけて、樹の心臓になれば……樹は、また元気になる。……コドクも、きっと追い払える。', { f: 'smile', g: 'handChest' }],
      ['shiro', '……なに、言ってるの……？', { f: 'surprise' }],
      ['mike', 'そんなの違う。', { f: 'angry', cam: 'mike', close: true }],
      ['mike', '仲間を犠牲にして世界を救うなんて、勇者じゃない！', { f: 'angry', g: 'fist', shake: 0.2 }],
      ['kuro', '……俺もだ。', { f: 'serious', move: { kuro: [1, 3] }, stance: { kuro: 'ready' } }],
      ['kuro', '……もう二度と、仲間はなくさない。', { f: 'serious', g: 'nod' }],
      ['shiro', 'わ、わたしも！　……わたし、昔、魔法で大切な子を救えなかった。失敗するのが怖くて、ずっと天才のふりをしてた。', { f: 'cry', g: 'bothChest' }],
      ['shiro', 'でも……失敗してもいい。何度でもやり直せばいいって、みんなが教えてくれた。……タマを犠牲にする方法なんて、失敗よりずっといや！', { f: 'cry', g: 'fist' }],
      { flag: 'shiroGrow', say: 'シロは失敗を受け入れた！（魔法が失敗しても「失敗は成功のもと」で追撃が出るようになった）' },
      ['maou', '……余は、せっかくできた遊び相手を、手放す気はない。', { f: 'smug', g: 'armsCrossed' }],
      ['tama', '……みんな……。', { f: 'cry' }],
      ['mike', '……タマ。ぼく、ずっと笑ってごまかしてた。お父さんとお母さんがいなくなって、さみしいって言ったら、止まらなくなりそうで。', { f: 'sad', g: 'handChest', to: 'tama' }],
      ['mike', 'でも、みんなといると、ほんとに笑えるんだ。……タマがいなくなったら、ぼく、もう笑えないよ。', { f: 'cry', g: 'bothChest' }],
      ['mike', 'さっき、「もっと強ければ」って思った。……でも、ちがった。', { f: 'gentle', g: 'shake' }],
      ['mike', '強いから助けるんじゃない。仲間だから助けるんだ。', { f: 'gentle', g: 'offer', to: 'tama', cam: 'mike', close: true }],
      { flag: 'mikeHero', say: 'ミケの「食いしん坊」に、仲間の数だけ強くなる力が加わった！' },
      ['e:kodoku_kage', '……ならば、その仲間ごと、ひとりにしてやろう。', { enter: 'e:kodoku_kage', fx: 'darkness', shake: 0.5, cam: 'wide' }],
      ['n', 'コドクが、一行の過去の幻を、次々に見せつける。仲間の姿が、闇に遠ざかっていく——', { cam: 'wide', dur: 7, r: { all: 'pained' } }],
      ['mike', '……みんな！　ぼくの声、聞こえる！？', { f: 'pained', g: 'reach' }],
      ['kuro', '……ああ。聞こえる。', { f: 'serious' }],
      ['shiro', '聞こえるわよ！', { f: 'cry' }],
      ['tama', '……うん。', { f: 'smile' }],
      ['maou', '……うるさいほどにな。', { f: 'smug' }],
      ['n', '互いを呼ぶ声が、幻を打ち破った。', { fx: ['dawn', 'light'], cam: 'wide', dur: 6, r: { all: 'smile' } }],
      ['e:kodoku_kage', '……くっ。だが、お前たちだけでは足りぬ。世界中の孤独は、お前たち五匹のつながりより、ずっと重い……。'],
      ['n', 'コドクは、樹の根を伝って、世界の果てへと消えていった。', { exit: 'e:kodoku_kage', cam: 'wide' }],
      ['shiro', '世界の果て……遺跡の声が言ってた、樹の根の行きつく先ね。誰の声も届かない、音も色もない場所……。', { f: 'worry', g: 'think' }],
      ['kuro', '……世界中の孤独が、根を伝って流れつく場所だ。あいつの巣には、うってつけだな。', { f: 'serious' }],
      ['tama', '……あっち。……根の先から、あの声がする。', { f: 'worry', g: 'point' }],
      ['mike', 'でも、根の先なんて、どうやって行くの？', { f: 'worry', g: 'tilt', to: 'tama' }],
      ['tama', '……根もとの東で、いちばん太い根が一本、地面から出て、果てのほうへのびてる。……その根をたどっていけば、いける。', { f: 'serious', g: 'point' }],
      ['tama', '……ぼく、樹とつながってるから、わかるの。', { f: 'gentle', g: 'handChest' }],
      ['maou', '……声が届かぬ場所なら、届くまで、もっと多くの者の声を集めればよい。', { f: 'serious', g: 'shrug' }],
      ['mike', '……そうか！　ぼくたちが旅で出会ったみんなに、力を貸してもらおう！', { f: 'joy', g: 'cheer' }],
      ['shiro', 'でも、みんな、ばらばらの場所にいるのよ。いまから一匹ずつ頼みに回ってたら……。', { f: 'worry', g: 'think' }],
      ['tama', '……根は、世界じゅうの地下に、のびてる。……ぼくが、根に声をのせてみる。', { f: 'serious', g: 'handChest', move: { tama: [0, 5] }, look: { all: 'tama' } }],
      ['n', 'タマが根にふれると、やわらかな光が、根を伝って、世界じゅうへ流れていった。', { stance: { tama: 'kneel' }, fx: 'rootcall:tama', cam: 'wide', dur: 7 }],
      ['tama', '……とどいた。……「ぽかぽか村へ来て」って。……ミケの村が、ぼくたちの旅のはじまりだから。', { f: 'smile', g: 'nod', stance: { tama: 'idle' } }],
      ['mike', 'へへっ。じゃあ、ぼくの村で待ち合わせだ！', { f: 'joy', g: 'cheer' }],
      ['kuro', '……村へ戻るぞ。そこから始める。', { f: 'serious', g: 'nod' }],
    ] },

  // ================= 第八章　みんなのにゃん力 =================
  c8_01: { title: 'ぽかぽか村の危機', cast: ['e:kagejuu'], bgm: 'dark',
    stage: { zone: 'pokapoka', at: [0, 16], face: 0,
      cast: { sonchou: { at: [-2, 4], face: 'mike' }, sakanaya: { at: [1.5, 3.4], face: 'mike', item: 'fish' }, 'e:kagejuu': [{ at: [-3, 9] }, { at: [3.2, 9.6] }] } },
    lines: [
      ['n', 'ぽかぽか村に戻ると、黒い影の獣たちが、村を取り囲んでいた。', { fx: 'darkness', cam: 'wide', dur: 7, r: { all: 'surprise' } }],
      ['kuro', '……根にのせた声を、コドクも聞きつけたか。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['sonchou', 'ミケ！　戻ってきたのか！', { f: 'surprise', g: 'surprise' }],
      ['sakanaya', 'あんたたち、下がってな！　……ほら、ミケ！', { f: 'angry', g: 'point' }],
      ['sakanaya', 'あんたに食べさせる魚くらい、いくらでも焼いてやるよ！', { f: 'smile', g: 'give', cam: 'sakanaya', close: true }],
      ['mike', 'おばちゃん……！', { f: 'cry', hold: { sakanaya: null, mike: 'fish' } }],
      ['mike', '……よし。行くよ、みんな！　村を守るんだ！', { f: 'serious', g: 'fist', stance: { all: 'ready' }, hold: { mike: null } }],
    ] },
  c8_02: { title: '集まる猫たち', bgm: 'hope', extra: ['sonchou', 'sakanaya', 'king_npc', 'piero_npc', 'nyahaha_ou', 'kurone', 'mazoku_yukyu', 'chaya'],
    stage: { zone: 'pokapoka', at: [0, 10], face: 0, host: 'sonchou',
      cast: { sonchou: { at: [0, 3], face: 'mike' }, sakanaya: { at: [-1.6, 3.4], face: 'mike' },
        king_npc: { at: [-3.4, 6.5], hidden: true, face: 'mike' }, piero_npc: { at: [3.3, 6], hidden: true, face: 'mike' }, nyahaha_ou: { at: [1.8, 7.4], hidden: true, face: 'mike' },
        kurone: { at: [-4.8, 4], hidden: true, face: 'mike' }, mazoku_yukyu: { at: [4.8, 4], hidden: true, face: 'maou' }, chaya: { at: [-1.8, 7.2], hidden: true, face: 'mike' } },
      points: { sky: [-30, 30, 120] }, wide: { pos: [-3.2, 2.2, -3], look: [0, 0.8, 4] } },
    lines: [
      ['n', '影をはらったあと。根を伝う呼び声を聞きつけて、村の広場に、見覚えのある顔が、次々と集まってきた。', { cam: 'wide', dur: 7, fx: 'dawn' }],
      ['king_npc', 'よう、勇者。……巣穴の根っこが光って、お前らの声がしたんだ。すっとんで来たぞ。', { enter: 'king_npc', move: { king_npc: [-2.4, 4.6] }, f: 'smile', look: { all: 'king_npc' } }],
      ['mike', 'キングネズミ！', { f: 'joy', g: 'surprise' }],
      ['king_npc', '魚……分けてやるよ。', { f: 'smile', g: 'give', hold: { king_npc: 'fish' } }],
      ['mike', 'え……でも、それ、大事な冬のごはんじゃ……。', { f: 'surprise' }],
      ['king_npc', '俺にとっては大事なんだ！　……あのとき、お前が分けてくれた魚がな。', { f: 'cry', g: 'fist', cam: 'king_npc', close: true }],
      ['piero_npc', 'ぼくも来たよ！　塔の下の根っこから、声が聞こえたんだ！　世界中に笑いを届けるショーの準備は、ばっちりさ！', { enter: 'piero_npc', f: 'joy', g: 'cheer', move: { piero_npc: [2.6, 4.6] } }],
      ['nyahaha_ou', 'わが国の民も、みな声を聞いた！　みな力を貸すぞ！　……ぶはははは！', { enter: 'nyahaha_ou', f: 'joy', g: 'laugh' }],
      ['kurone', '谷の根も、ひさしぶりにしゃべったよ。谷のみんなも、クロの仲間なら力になるってさ。', { enter: 'kurone', f: 'gentle', g: 'nod', r: { kuro: 'surprise' } }],
      ['mazoku_yukyu', '魔王さまー！　城の地下の根が光ったので、魔王軍一同、有給を返上して参りました！', { enter: 'mazoku_yukyu', f: 'joy', g: 'cheer' }],
      ['maou', '……お前たち。', { f: 'surprise', cam: 'maou', close: true, later: [1.5, { r: { maou: 'shy' } }] }],
      ['chaya', '街道の木の根が「ぽかぽか村へ」って呼んだのさ！　お茶も持ってきた！　ハチとブチの笛と太鼓もいっしょだ！', { enter: 'chaya', f: 'smile', g: 'wave' }],
      ['sonchou', 'ミケ。……お前が旅で結んできたつながりが、みんなをここへ連れてきたんじゃよ。', { f: 'gentle', g: 'handChest' }],
      ['mike', '……みんな……！', { f: 'cry' }],
      ['tama', '……よかった。……ちゃんと、とどいてた。', { f: 'smile', g: 'handChest' }],
      ['kuro', '……ミケ。これが、お前の力だ。', { f: 'smile', g: 'nod' }],
      ['n', '猫たちの心が重なると、遠くのにゃんだーの樹が、ほんの少し、光を取り戻した。', { fx: ['voices', 'light:sky'], cam: 'wide', dur: 8, look: { all: 'sky' } }],
      ['tama', '……樹が……わらった。', { f: 'joy', g: 'lookUp' }],
      ['shiro', 'でも……樹には届いても、果てまでは届かないのよね。', { f: 'worry', g: 'think' }],
      ['maou', '孤独は重い。根を伝って沈み、いちばん深い果てにたまる。……声は軽い。のぼって樹には届くが、底へは下りてゆかぬ。', { f: 'serious', g: 'explain' }],
      ['tama', '……果てには、いろんな所から、根がとどいてる。……この村の下からも。', { f: 'gentle', g: 'point' }],
      ['mike', 'じゃあ、みんなの声をひとつに重ねたら、底まで届くかも！', { f: 'joy', g: 'fist' }],
      ['tama', '……うん。……果てに着いたら、根で呼ぶね。……そしたら、みんなで声をそろえて。', { f: 'smile', g: 'nod' }],
      ['sonchou', 'よし。わしらは、ここで声をそろえて待っとる。', { f: 'gentle', g: 'nod' }],
      ['piero_npc', 'ハチとブチの笛と太鼓で、拍子をとろう！　世界でいちばんのショーにしてみせるよ！', { f: 'joy', g: 'cheer' }],
      ['nyahaha_ou', '国の民にも、根が光ったら、国じゅうで笑えと伝えてある！　ぶはははは！', { f: 'joy', g: 'laugh' }],
      { bond: ['all', null, 20] },
      ['mike', '行こう、世界の果てへ！　みんなの力で、コドクを止めるんだ！', { f: 'serious', g: 'fist', r: { all: ['joy', 'cheer'] } }],
    ] },
  c8_03: { title: '世界の果て', cast: ['e:kagejuu', 'e:utsuro'], bgm: 'dark',
    stage: { zone: 'world_end', at: [0, 20], face: 0, cast: { 'e:kagejuu': { at: [-2.6, 6], hidden: true }, 'e:utsuro': { at: [2.4, 6.6], hidden: true } }, points: { edge: [0, 2, 60], roots: [0, 16, 60] } },
    lines: [
      ['n', '樹の根もとの東から、地面を這う太い根をたどって、どこまでも歩いた。……やがて地面はとぎれ、根は、下へ、下へと奈落にもぐりながら、浮かぶ石の道を支えていた。', { cam: 'wide', dur: 8 }],
      ['n', '世界の果ては、音も、色もない、しずかな場所だった。', { cam: 'look:edge', dur: 7, look: { all: 'edge' } }],
      ['n', '見上げると、闇の上から、何本もの根がたれさがっていた。世界じゅうの地下をめぐった根の先が、この地の底に行きついているのだ。', { cam: 'look:roots', dur: 8, look: { all: 'roots' } }],
      ['tama', '……あの根、ぜんぶ、どこかの村や森から、のびてきてる。', { f: 'gentle', g: 'lookUp' }],
      ['shiro', '……ここ、さみしい……。', { f: 'worry' }],
      ['maou', '余が、ずっとひとりでいた場所に、よく似ている。', { f: 'sad' }],
      ['tama', '……だいじょうぶ。……今は、みんないる。', { f: 'smile', g: 'nod', to: 'maou', r: { maou: 'shy' } }],
      ['n', '闇の中から、コドクの獣たちが現れた！', { enter: ['e:kagejuu', 'e:utsuro'], cam: 'wide', stance: { all: 'ready' } }],
    ] },
  c8_04: { title: '一人じゃない', cast: ['e:kodoku'], bgm: 'boss',
    stage: { zone: 'world_end', at: [0, -21], face: 0, cast: { 'e:kodoku': { at: [0, 9.5] } } },
    lines: [
      ['e:kodoku', '……来たか。たった五匹で。', { cam: 'foe:e:kodoku', dur: 6 }],
      ['mike', '五匹じゃない！', { f: 'serious', g: 'fist' }],
      ['e:kodoku', '……？'],
      ['mike', 'ぼくたちの後ろには、旅で出会った、みんながいる！', { f: 'serious', g: 'point' }],
      ['e:kodoku', 'つながりなど、いずれ消える。……だから私は、生まれたのだ。'],
      ['kuro', '……消えない。……あいつらは、今も俺の中にいる。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['e:kodoku', 'ならば、試してみるがいい。孤独、絶望、疑心、思い出消去……すべての孤独を、受けてみろ。', { shake: 0.6, fx: 'darkness' }],
      ['n', '（最終決戦：コドクが最後の姿になると、世界中の猫たちの声が届く。友情ゲージが満ちたら「にゃんこオールスターズ」を使おう！　Cキー）', { cam: 'wide', dur: 6, stance: { all: 'ready' } }],
    ] },
  c8_05: { title: 'みんなのにゃん力', cast: ['e:kodoku'], bgm: 'hope',
    stage: { zone: 'world_end', at: [0, -21], face: 0, cast: { 'e:kodoku': { at: [0, 9.5] } }, points: { sky: [0, 30, 60] } },
    lines: [
      ['n', '光に包まれて、コドクの黒い体が、ほどけていく。', { fx: ['dawn', 'light:e:kodoku'], cam: 'foe:e:kodoku', dur: 7 }],
      ['e:kodoku', '……あたたかい……。これが……つながり、か……。'],
      ['e:kodoku', '……私も……本当は……ひとりは、いやだった……。'],
      ['mike', '……じゃあ、きみもおいでよ。', { f: 'gentle', g: 'offer' }],
      ['e:kodoku', '……ふ……。……ありがとう。', { defeat: 'e:kodoku' }],
      ['n', '孤独は、光の粒になって、空へ昇っていった。', { fx: 'voices', cam: 'wide', dur: 6 }],
      ['n', 'そして——', { fx: 'revive', cam: 'look:sky', dur: 8, look: { all: 'sky' } }],
      ['tama', '……樹が……！', { f: 'joy', g: 'cheer' }],
    ] },
  c8_05t: { title: 'よみがえる樹', bgm: 'hope',
    stage: { zone: 'tree_root', at: [0, 10], face: 180, party: [], flags: { bloom: true },
      shots: { canopy: { pos: [0, 50, -60], look: [0, 84, 45] }, fruits: { pos: [-8, 72, -32], look: [0, 80, 20] } } },
    lines: [
      ['n', 'にゃんだーの樹。灰色だった葉に、みどりが戻っていく。', { fx: 'treeBloom', cam: 'canopy', dur: 8 }],
      ['n', '枝という枝に、感情の実がふくらんでいく。笑い、友情、思い出、優しさ——。', { fx: 'fruitsGrow', cam: 'fruits', dur: 9 }],
    ] },
  c8_05b: { title: 'そのころ、ぽかぽか村', bgm: 'hope', extra: ['piero_npc', 'kurone', 'mazoku_yukyu', 'chaya'],
    stage: { zone: 'pokapoka', at: [4, 22], face: 180, party: [],
      cast: { sonchou: { at: [0, 0], face: 'tree' }, sakanaya: { at: [1.2, 0.4], face: 'tree' }, king_npc: { at: [-1.3, 0.3], face: 'tree' }, nyahaha_ou: { at: [2.5, -0.5], face: 'tree' },
        piero_npc: { at: [-2.6, -0.4], face: 'tree' }, kurone: { at: [-0.6, -1.4], face: 'tree' }, mazoku_yukyu: { at: [0.8, -1.5], face: 'tree' }, chaya: { at: [-1.9, -1.6], face: 'tree' } },
      points: { tree: [4, 50, 208] }, shots: { tree: { pos: [0.4, 1.8, -3.6], look: [4, 58, 208] } }, wide: { pos: [-2.8, 2.4, -5.2], look: [0.6, 1.6, 4] } },
    lines: [
      ['n', 'そのころ、ぽかぽか村。笛と太鼓が鳴りやみ、みんなは息をのんで、南の空を見上げていた。', { cam: 'wide', dur: 7, look: { all: 'tree' } }],
      ['n', '森の向こうで、にゃんだーの樹が、光っていた。', { cam: 'tree', dur: 9, fx: ['treeShine', 'voices'], look: { all: 'tree' } }],
      ['sakanaya', '……きれいだねえ。', { f: 'cry', g: 'bothChest', look: { sakanaya: 'tree' } }],
      ['king_npc', '……届いたんだな。俺たちの声。', { f: 'smile', g: 'nod', look: { king_npc: 'tree' } }],
      ['sonchou', '……ミケ。ようやったのう。', { f: 'cry', g: 'lookUp', look: { all: 'tree' } }],
      ['nyahaha_ou', 'ぶははははは！　今日は、世界じゅうで宴じゃ！', { f: 'joy', g: 'laugh', fx: 'laugh', r: { all: ['joy', 'cheer'] } }],
    ] },
  c8_05c: { title: 'ずっと仲間', bgm: 'hope',
    stage: { zone: 'world_end', at: [0, -21], face: 0 },
    lines: [
      ['n', '地の底にも、たれさがった根を伝って、やわらかな光が下りてきた。音も色もなかった果てに、色が戻っていく。', { fx: ['rootsLit', 'dawn'], cam: 'wide', dur: 8 }],
      ['tama', '……樹が、わらってる。……ぼくには、わかる。', { f: 'joy', g: 'handChest' }],
      ['maou', '……友達って、いいものだな。', { f: 'gentle', cam: 'maou', close: true }],
      ['kuro', '……ああ。', { f: 'smile', g: 'nod' }],
      ['tama', '……ぼく、樹にならなくて……よかったの？', { f: 'worry', g: 'tilt', to: 'mike' }],
      ['mike', '当たり前じゃん！　タマは、ぼくたちと一緒に遊ぶんだから！', { f: 'joy', g: 'hop' }],
      ['tama', '……うん！', { f: 'joy', g: 'cheer' }],
      ['mike', 'ぼくたちは——', { f: 'serious', g: 'fist', cam: 'mike', close: true }],
      ['n', '「ずっと仲間だ！」', 'みんな', { r: { all: ['joy', 'cheer'] }, cam: 'wide', dur: 7, fx: 'laugh' }],
    ] },

  // ================= エピローグ　それから =================
  c9_01: { title: 'それから', bgm: 'village', extra: ['sonchou', 'sakanaya'],
    stage: { zone: 'pokapoka', at: [12, 1.5], face: 90,
      cast: { mike: { at: [0.4, 3.6], face: [0, 0], item: 'fish' }, kuro: { at: [-2.6, 1.2], face: 'mike' }, shiro: { at: [-2.4, -0.6], face: 'mike' }, tama: { at: [-3.6, 0.2], face: 'mike' }, maou: { at: [-1.4, -1.6], face: 'mike' },
        sonchou: { at: [-1.2, 1.8], face: 'mike' }, sakanaya: { at: [3, 1.5], hidden: true, face: 'mike' } },
      wide: { pos: [-4.6, 1.8, -1.4], look: [0, 0.8, 2.6] } },
    lines: [
      ['n', '——それから、数年後。', { cam: 'wide', dur: 7 }],
      ['n', 'マオウは、魔王城を改装して、世界一の猫カフェを開いた。', { cam: 'maou', dur: 6 }],
      ['maou', 'いらっしゃいませ。……ふん、余の淹れる紅茶は、世界一だぞ。', { f: 'smug', g: 'bow' }],
      ['n', 'クロは、冒険者ギルドを作り、ひとりぼっちの冒険者たちに、仲間を紹介している。', { cam: 'kuro', dur: 6 }],
      ['kuro', '……一人で行くな。仲間を連れていけ。……それが、ギルドの決まりだ。', { f: 'smile', g: 'nod' }],
      ['n', 'シロは、魔法学校の校長になった。', { cam: 'shiro', dur: 6 }],
      ['shiro', '失敗を怖がらないこと！　それが、天才への第一歩よ！', { f: 'smug', g: 'raise' }],
      ['n', 'タマは、にゃんだーの樹の管理人として、樹の上で、のんびり暮らしている。……樹が元気になったので、もう眠りすぎることはない。ただ、昼寝が好きなだけだ。', { cam: 'tama', dur: 7 }],
      ['tama', '……きょうも、いいてんき……すぴー。', { f: 'sleepy', stance: { tama: 'sleep' } }],
      ['n', 'そして、ミケは——', { cam: 'mike', dur: 5 }],
      ['mike', 'いらっしゃい、いらっしゃい！　今日は、いい魚が入ってるよー！', { f: 'joy', g: 'wave' }],
      ['sonchou', 'なんで勇者が魚屋なんじゃ。', { f: 'serious', g: 'shake' }],
      ['mike', '魚が好きだから！', { f: 'joy', g: 'cheer', r: { all: 'smile' } }],
      ['sakanaya', 'まったく……うちのライバルになるとはねえ！', { enter: 'sakanaya', f: 'smile', g: 'laugh' }],
      ['n', 'ぽかぽか村は、今日も、ぽかぽかだ。', { cam: 'wide', dur: 8, fx: 'sparkle:mike' }],
    ] },

  // ================= おまけ　ねこ神の夢 =================
  c10_01: { title: '夢の入口', cast: ['e:sakana'], bgm: 'field',
    stage: { zone: 'dream', at: [0, 20], face: 0, cast: { 'e:sakana': { at: [0, 5], hidden: true } } },
    lines: [
      ['n', '猫神社の鳥居の奥。気がつくと、一行は、お菓子と魚の浮かぶふしぎな夢の中にいた。', { cam: 'wide', dur: 7 }],
      ['mike', 'わーっ、魚が空を泳いでる！', { f: 'joy', g: 'cheer' }],
      ['shiro', '……夢、よね？', { f: 'worry' }],
      ['kuro', '……頬をつねってみろ。', { f: 'serious' }],
      ['shiro', 'いたっ！　……なんで、わたしの頬なのよ！', { f: 'angry', g: 'fist', to: 'kuro' }],
      ['e:sakana', 'いいかい、そもそも魚というのはだね……', { enter: 'e:sakana' }],
      ['maou', '……魚がしゃべったぞ。', { f: 'surprise', stance: { all: 'ready' } }],
    ] },
  c10_02: { title: 'へんてこ回廊', cast: ['e:nisemike', 'e:kuroPlush', 'e:tamas'], bgm: 'field',
    stage: { zone: 'dream', at: [0, 6], face: 0, cast: { 'e:nisemike': { at: [-2.6, 4] }, 'e:kuroPlush': { at: [2.6, 4.4] }, 'e:tamas': { at: [0, 7] } } },
    lines: [
      ['e:nisemike', 'ぼくが、本物のミケだよ！'],
      ['mike', 'ぼくが本物だよ！？', { f: 'surprise', g: 'point' }],
      ['kuro', '……偽物のほうが、しっぽの模様が逆だ。', { f: 'serious' }],
      ['e:kuroPlush', '……めんどうだ（録音）。'],
      ['kuro', '……俺は、そんなに言ってない。', { f: 'angry' }],
      ['shiro', '言ってるわよ。', { f: 'smug', r: { mike: 'joy', maou: 'smile' } }],
      ['e:tamas', '「「「すやすや……」」」'],
      ['tama', '……ぼくが、いっぱい……。', { f: 'surprise' }],
      ['shiro', 'どれが本物のタマ！？', { f: 'surprise', g: 'recoil', stance: { all: 'ready' } }],
    ] },
  c10_03: { title: 'ねこ神', cast: ['e:nekogami'], bgm: 'boss',
    stage: { zone: 'dream', at: [0, -15], face: 0, cast: { 'e:nekogami': { at: [0, 9] } } },
    lines: [
      ['e:nekogami', 'よくぞここまで来た。', { cam: 'foe:e:nekogami', dur: 6 }],
      ['mike', '誰？', { f: 'neutral', g: 'tilt' }],
      ['e:nekogami', 'この世界を作った者だ。'],
      ['mike', 'じゃあ、世界救ってよ。', { f: 'serious' }],
      ['e:nekogami', 'それは面倒なので、お前に任せた。'],
      ['kuro', '……面倒、だと。', { f: 'angry', stance: { kuro: 'ready' } }],
      ['shiro', 'クロの親戚！？', { f: 'surprise', g: 'point' }],
      ['e:nekogami', '……まあ、ここまで来たごほうびだ。少し、遊んでやろう。', { shake: 0.4, stance: { all: 'ready' } }],
    ] },
  c10_04: { title: '夢のおわり', cast: ['e:nekogami'], bgm: 'hope',
    stage: { zone: 'dream', at: [0, -15], face: 0, cast: { 'e:nekogami': { at: [0, 9] } } },
    lines: [
      ['e:nekogami', '……ふう。お前たち、強くなったな。'],
      ['e:nekogami', '世界を救ったのは、私ではない。お前たちと、お前たちがつないだ、たくさんの心だ。……だから、任せて正解だった。'],
      ['mike', '……めんどうだっただけでしょ？', { f: 'smug' }],
      ['e:nekogami', '……ばれたか。', { r: { all: ['joy', 'laugh'] } }],
      ['n', 'ねこ神が笑うと、夢は、やさしい光にほどけていった。', { fx: 'light', cam: 'wide', dur: 7 }],
    ] },

  // ================= 友情の特別イベント（友情Lv4） =================
  b_kuro_mike: { title: '屋根の上の星', bgm: 'sad',
    stage: { zone: 'pokapoka', at: [-22, -2], face: 0, bg: 'night', party: ['mike', 'kuro'], cast: { mike: { at: [-0.6, 0] }, kuro: { at: [0.6, 0.2] } }, points: { sky: [0, 20, 30] } },
    lines: [
      ['n', '夜。ミケの家の前で、二匹は星を見上げていた。', { cam: 'wide', dur: 6, look: { all: 'sky' } }],
      ['mike', 'ねえクロ。クロが追いかけてた流れ星って、どんなだった？', { f: 'smile', to: 'kuro' }],
      ['kuro', '……きれいだった。……でも、落ちていくのを見て、思った。……ひとりで落ちていくのは、さみしいだろうなって。', { f: 'gentle', g: 'lookUp' }],
      ['mike', 'だから、追いかけたの？', { f: 'neutral', g: 'tilt' }],
      ['kuro', '……ああ。……そしたら、お前がいた。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'へへっ。じゃあ、あの流れ星に、お礼言わなきゃ！', { f: 'joy', g: 'wave', look: { mike: 'sky' } }],
      ['kuro', '……ふっ。……面倒なやつ。', { f: 'smile' }],
    ] },
  b_mike_shiro: { title: '最後の焼き魚',
    stage: { zone: 'pokapoka', at: [10, 12], face: 0, party: ['mike', 'shiro'], cast: { mike: { at: [-0.7, 0], item: 'fish' }, shiro: { at: [0.7, 0.1] } } },
    lines: [
      ['shiro', 'ちょっとミケ！　その焼き魚、最後の一匹でしょ！　わたしのよ！', { f: 'angry', g: 'point', to: 'mike' }],
      ['mike', 'ぼくが先に見つけたもん！', { f: 'pout', g: 'pout' }],
      ['shiro', 'じゃあ、魔法で二匹に増やしてあげる！　……ダブル！', { f: 'smug', g: 'raise', fx: 'spell:shiro', later: [1.2, { fx: 'poof:shiro' }] }],
      ['n', '……魚は増えなかった。かわりに、シロの毛が爆発した。', { cam: 'shiro', close: true }],
      ['mike', 'ぷっ……あははは！', { f: 'joy', g: 'laugh' }],
      ['shiro', 'わ、笑わないでよ！　……ふふっ、あははは！', { f: 'joy', g: 'laugh' }],
      ['mike', 'はい、半分こ！', { f: 'joy', g: 'give', hold: { mike: null, shiro: 'fish' } }],
      ['shiro', '……最初からそうしなさいよ。……ありがと。', { f: 'shy', g: 'turnAway' }],
    ] },
  b_mike_tama: { title: 'ミケにいちゃん', bgm: 'sad',
    stage: { zone: 'hill', at: [-11, 9], face: 0, bg: 'night', party: ['mike', 'tama'], cast: { mike: { at: [-0.5, 0], stance: 'kneel' }, tama: { at: [0.6, 0.1], stance: 'kneel' } }, points: { sky: [0, 14, 30] } },
    lines: [
      ['tama', '……ミケにいちゃん。……おとうさんと、おかあさんって、どんなの？', { f: 'sleepy', g: 'tilt', to: 'mike' }],
      ['mike', '……えっ。', { f: 'surprise' }],
      ['mike', '……あったかくて、いつも笑ってて……ぼくが魚を盗ると、すっごく怒った。', { f: 'gentle', g: 'lookUp', look: { mike: 'sky' } }],
      ['mike', '……へへ。……もう、いないんだけどね。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……ミケにいちゃん、さみしい？', { f: 'worry' }],
      ['mike', '……ちょっとだけ。でも、今はタマがいるから、へっちゃら！', { f: 'smile', g: 'nod' }],
      ['tama', '……えへへ。……ぼくも。', { f: 'gentle', stance: { tama: 'sleep' } }],
      ['n', 'タマは、ミケの肩にもたれて、すやすやと眠ってしまった。', { cam: 'wide', dur: 7 }],
    ] },
  b_maou_mike: { title: 'はじめてのかくれんぼ',
    stage: { zone: 'demon_land', at: [10, 20], face: 0, party: ['mike', 'maou'], cast: { mike: { at: [-0.8, 0] }, maou: { at: [0.8, 0.2] } } },
    lines: [
      ['maou', '勇者よ。……「かくれんぼ」とやらを、教えるがよい。', { f: 'smug', g: 'armsCrossed', to: 'mike' }],
      ['mike', 'いいよ！　ぼくが鬼ね！　いーち、にーい……', { f: 'joy', g: 'hop' }],
      ['n', '……十数えて振り返ると、マオウは、ぜんぜん隠れていなかった。', { cam: 'maou', close: true }],
      ['mike', '……マオウ、見えてるよ？', { f: 'neutral', g: 'tilt' }],
      ['maou', '……余は、見つけてほしかったのだ。……ずっと、誰かに。', { f: 'shy', g: 'turnAway' }],
      ['mike', '……じゃあ、見つけた！', { f: 'joy', g: 'point' }],
      ['maou', '……ふん。……楽しいではないか、かくれんぼ。', { f: 'smile' }],
    ] },
  b_kuro_shiro: { title: '失敗の記録',
    stage: { zone: 'nyahaha', at: [-22, 18], face: 90, party: ['kuro', 'shiro'], cast: { kuro: { at: [-0.7, 0], item: 'book' }, shiro: { at: [0.7, 0.1] } } },
    lines: [
      ['shiro', '……影の四剣の記録、読ませてもらったわ。失敗の記録も、ちゃんと全部書いてあるのね。', { f: 'serious', to: 'kuro' }],
      ['kuro', '……ハヤテの方針だ。「失敗を書かないやつは、同じ失敗をする」。', { f: 'serious' }],
      ['shiro', '……わたし、失敗を書くのが怖かった。書いたら、本当に失敗したことになる気がして。', { f: 'sad', g: 'lookDown' }],
      ['kuro', '……失敗してもいい。お前が前に出すぎたら、俺が前に立つ。', { f: 'serious', g: 'nod' }],
      ['shiro', '……クロって、真面目よね。', { f: 'smile' }],
      ['kuro', '……お前もだ。', { f: 'smile', r: { shiro: 'shy' } }],
    ] },
  b_kuro_tama: { title: 'ひだまりの番',
    stage: { zone: 'woods', at: [2, 8], face: 0, party: ['kuro', 'tama'], cast: { tama: { at: [0.5, 0.6], stance: 'sleep' }, kuro: { at: [-0.8, 0], stance: 'armsCrossed' } } },
    lines: [
      ['n', '昼下がり。タマがひだまりで眠るそばで、クロがじっと座っていた。', { cam: 'wide', dur: 7 }],
      ['tama', '……クロ……ずっと、そこにいるの……？', { f: 'sleepy' }],
      ['kuro', '……お前が寝ている間に、何かあったら困る。', { f: 'serious', g: 'turnAway' }],
      ['tama', '……クロは、やさしいね。', { f: 'gentle' }],
      ['kuro', '……別に。……面倒なだけだ。', { f: 'shy' }],
      ['tama', '……えへへ。……おやすみ、クロ。', { f: 'sleepy' }],
      ['kuro', '……ああ。……おやすみ。', { f: 'gentle', cam: 'kuro', close: true }],
    ] },
  b_shiro_tama: { title: 'まくらの芽',
    stage: { zone: 'road_rest', at: [-19, 0], face: 0, party: ['shiro', 'tama'], cast: { shiro: { at: [-0.6, 0] }, tama: { at: [0.6, 0.2] } } },
    lines: [
      ['shiro', 'ほら、タマ。頭の芽、寝ぐせでぺしゃんこよ。直してあげる。', { f: 'gentle', g: 'reach', to: 'tama' }],
      ['tama', '……ありがと、シロ。', { f: 'smile' }],
      ['shiro', '……ねえタマ。あなたが樹から生まれたとか、そういうの……わたし、ちょっと怖いの。', { f: 'worry' }],
      ['tama', '……シロ、こわいの？', { f: 'worry', g: 'tilt' }],
      ['shiro', '……あなたが、どこか遠くに行っちゃいそうで。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……どこにもいかないよ。……シロのとなりで、ねる。', { f: 'gentle', g: 'nod' }],
      ['shiro', '……もう。……それなら、いいわ。', { f: 'shy', g: 'handChest' }],
    ] },
  b_kuro_maou: { title: '……',
    stage: { zone: 'valley', at: [-10, 14], face: 0, party: ['kuro', 'maou'], cast: { kuro: { at: [-0.7, 0], stance: 'armsCrossed' }, maou: { at: [0.7, 0.1], stance: 'armsCrossed' } } },
    lines: [
      ['kuro', '……。', { f: 'serious' }],
      ['maou', '……。', { f: 'serious' }],
      ['kuro', '……いい天気だ。', { f: 'serious', g: 'lookUp' }],
      ['maou', '……うむ。', { f: 'serious', g: 'nod' }],
      ['n', '……それから一時間、二匹は並んで空を見ていた。', { cam: 'wide', dur: 7 }],
      ['maou', '……悪くない時間だった。', { f: 'smile' }],
      ['kuro', '……ああ。', { f: 'smile' }],
    ] },
  b_maou_shiro: { title: '実験台',
    stage: { zone: 'road_rest', at: [-23, -21], face: 0, party: ['shiro', 'maou'], cast: { shiro: { at: [-0.7, 0] }, maou: { at: [0.9, 0.3] } } },
    lines: [
      ['shiro', 'マオウ！　新しい魔法ができたの。ちょっと実験台になって！', { f: 'joy', g: 'point', to: 'maou' }],
      ['maou', 'ことわる。', { f: 'serious', g: 'turnAway' }],
      ['shiro', '毛並みがつやつやになる魔法よ？', { f: 'smug' }],
      ['maou', '……少しだけならよい。', { f: 'shy' }],
      ['n', '……マオウの毛並みは、つやつやのピンク色になった。', { fx: ['spell:shiro', 'sparkle:maou'], cam: 'maou', close: true }],
      ['maou', '…………。', { f: 'angry' }],
      ['shiro', '……か、かわいいわよ？', { f: 'shy', g: 'shrug' }],
      ['maou', '……ふん。……悪くない。', { f: 'smug', r: { shiro: ['joy', 'laugh'] } }],
    ] },
  b_maou_tama: { title: 'おひるね同盟',
    stage: { zone: 'hill', at: [-12, 10], face: 0, party: ['tama', 'maou'], cast: { tama: { at: [-0.4, 0.4], stance: 'sleep' }, maou: { at: [0.8, 0.2], stance: 'kneel' } } },
    lines: [
      ['tama', '……マオウも……いっしょに、おひるね……する？', { f: 'sleepy', to: 'maou' }],
      ['maou', '……余は魔王だ。昼寝など——', { f: 'smug' }],
      ['tama', '……ふかふかだよ。', { f: 'smile' }],
      ['maou', '……少しだけならな。', { f: 'shy', stance: { maou: 'sleep' } }],
      ['n', '……一時間後。二匹は仲よく、ぐっすり眠っていた。', { cam: 'wide', dur: 7 }],
      ['maou', '……すぴー……。', { f: 'sleepy' }],
    ] },
});

// 第五章〜のあらすじ
const RECAP_2 = {
  c5_01: 'くろねこ谷の北、森に埋もれた古代遺跡へ。タマは、なぜか懐かしそうにしている。',
  c5_01b: '石畳の丘の大階段を上りきると、森の奥に石の神殿のような遺跡がそびえていた。扉には光る結界。扉の前には、踏むと光る石畳。「始まりの石から、すべての石をひと筆で」。',
  c5_02: '壁画には、樹を抱いて眠る巨大な猫と、樹のまわりで手をつなぐ四匹の猫。古代文字には「つながりが絶えるとき、樹は最後のにゃんこを生む」と記されていた。',
  c5_02b: '大広間の奥の崩れた回廊。入口の間の白い水晶にタマがふれると、瓦礫でふさがれていた回廊の口が昔の姿にもどり、かわりに別の口に石の門が立った。遺跡は「今」と「昔」で、通れる道がちがう。',
  c5_03: '誰にも開けられない封印の扉は、タマがふれると、ゆっくりと奥へ開いた。扉が「おかえり」と言った、とタマは言う。回廊の古代文字を思い出したシロがつぶやく。「最後のにゃんこ」……「……ぼく？」',
  c5_03b: '扉の奥の封印の間で、祭壇の光から遺跡の守護神が姿を現す。「封印を開けられるのは、最後のにゃんこだけ……。その心、確かめさせてもらおう」',
  c5_04: '戦いを終えた遺跡の守護神は、封印の間の祭壇の前で語る。樹は猫たちの心のつながりを糧に生き、枯れかけると樹を救う子「最後のにゃんこ」を生む。タマがいつも眠っていたのは、弱った樹と心がつながっていたからだった。樹の根は世界じゅうの地下をめぐり、その先は、誰の声も届かない「世界の果て」に行きつくという。樹を枯らしているのは魔王ではなく、世界に広がった孤独だった。樹の心臓はいにしえの猫たちに封じられ、その扉も最後のにゃんこにしか開けられないという。魔王も樹の根の「何か」を知っているらしい。',
  c6_01: '魔王領は、有給をほしがる兵がいて、城では年に一度の健康診断まで行われている、妙にコミカルな場所だった。魔王は城でひとり、猫じゃらしで遊んでいるらしい。',
  c6_01b: '魔王城の受付で「面会許可証」を受け取る。魔王に会うには、健康診断の「異常なし」と、四天王四人の「通ってよし」のハンコが必要だった。……ただし、幹部の「侵入者は追い返せ」の命令は出たままで、兵たちは襲ってくる。',
  c6_02: '保健の間の健康診断で、ミケは「魚の食べすぎ」、クロは「眉間のしわ」、シロは「夜ふかし」、タマは「寝すぎ」と言われる。そこへ胃の痛い幹部が邪魔に入る。',
  c6_02b: '健康診断のハンコは「異常なし」。……ただし、魚はひかえめに。',
  c6_k1: '四天王・炎のグツグツは、台所の火の番だった。健康診断で塩分をひかえるように言われ、カレーの味に悩んでいた。',
  c6_k1b: 'ミケのすすめで、グツグツは魚の骨でだしをとることに。ハンコ、ふたつめ。',
  c6_k2: '四天王・眠りのネムネムは、静かな地下の牢屋で眠っていた。「ごはんだよ」の一言で、ようやく目をさます。',
  c6_k2b: 'まがったハンコで、みっつめ。ネムネムは、また眠ってしまった。',
  c6_k3: '四天王・風のチョキチョキは、魔王のために猫じゃらしを育てる庭師だった。「いっしょに遊ぶ相手が、おらんのじゃが」。',
  c6_k3b: 'ハンコ、よっつめ。ミケは、花壇でいちばん立派な猫じゃらしを託される。',
  c6_k4: '最後の四天王・大地のドドンは、有給の温泉から帰ったばかりのまとめ役だった。許可証をていねいに確かめ、温泉まんじゅうを配ってから勝負をいどむ。',
  c6_k4b: 'ドドンの大きなハンコで、面会許可証のハンコが五つそろう。「魔王さまは、ずっとお客を待っておられる」。',
  c6_03: '玉座の間で、魔王マオウはひとりで猫じゃらしにじゃれていた。ハンコのそろった面会許可証に驚きつつも、「余はこの世界を滅ぼす者だ」。',
  c6_04: 'マオウが世界を滅ぼそうとした理由は「余と遊んでくれる者がいない」から。魔王もまた孤独だった。「世界を滅ぼす」と言ったのも、誰かに城まで来てほしかったからだった。クロの仲間を襲ったのも魔王軍ではなく、樹の根元に巣くう黒い何かだと分かる。面会の手続きを面倒にしたのも、誰も来ないのを手続きのせいにしたかったから。一行と笑ったとき、灰色だった笑いの実は光りを取りもどした。笑いの実は、だれかといっしょに笑うと光る実だった。マオウは「退屈しのぎ」に一行へ加わり、城では三年分の有給がいっせいに通った。笑いの実は王国へ返された。',
  c7_01: 'にゃんだーの樹は、灰色の葉を落とし続けていた。旅の始まりの夜、この樹に残っていた最後の友情の実が、熟す前に落ちかけていた。取ろうと手を伸ばしたクロは足を滑らせ、落ちながらとっさに実をつかんだ。ぶら下がったクロの重さで大きくしなった枝がいきおいよくはね返り、そのはずみで実の軸が折れて、クロは実ごと空へ放り出された。夜に光る樹の実が、夜空に尾を引いて飛んでいく——ミケが見たあの流れ星は、実を守ろうとしたクロだったのだ。実は割れてしまったが、そのおかげで二匹は出会えた。',
  c7_01b: '根のトンネルの奥の封印の扉は、マオウにもクロにも開けられなかった。樹を守るための封印が、中に入りこんだものまで隠していたのだ。タマがふれると扉は開き、奥から黒いかけらがあふれ出して、一行を根もとの広場まで押しもどした。',
  c7_02: '封印の扉の奥の地下は、誰の声も届かないほど静かだった。タマは、根がさむがっている、光をほしがっていると言う。一行の前に、冷たい「虚ろ」が立ちふさがる。',
  c7_02b: 'しおれた根の洞では、灰色の感情の実が、仲間といっしょに持ち上げると光った。光る実のそばで根は目をさまし、奈落に橋をかけた。根の扉に実をそなえて下りた先は、うす暗い影の回廊。一行の影は、足もとからはなれたがっていた。「ひとりで、いいよ」というささやきの中で、タマは「はなれていっても、つれて帰ってあげなきゃ」と言う。',
  c7_02c: '影たちをつれもどして下りた先は、樹の心臓の間。根に吊られた心臓は、弱々しく脈打ち、鼓動のたびに根の血管が光った。天井に垂れる実は、みな色がぬけていた。',
  c7_03: '樹の心臓の前で、世界に広がった孤独そのもの「コドク」と対面する。コドクは、一行の心の奥の孤独を言い当て、黒影洞窟でクロの仲間を闇に沈めたのは自分だと告げた。クロだけを残したのは、ひとりにするため。樹を調べていたクロの心に「ひとりでいい」とささやいていたのも、コドクだった。',
  c7_04: 'コドクは倒しても消えない。タマは「ぼくが樹になればいいんだよ」と言う。ミケは「仲間を犠牲にして世界を救うなんて、勇者じゃない！」と拒み、ずっと笑ってごまかしてきたさみしさを打ち明けて「強いから助けるんじゃない。仲間だから助けるんだ」と言った。クロも、失敗を受け入れたシロも、マオウも、タマを守ると決めた。互いを呼ぶ声で幻を打ち破るが、コドクは樹の根の行きつく先、誰の声も届かない「世界の果て」へ逃れた。樹とつながるタマには、根もとの東からのびる太い根をたどれば、そこへ行けるとわかった。世界中の孤独が流れつくその場所で戦うには、五匹だけの声では足りない。タマは根に声をのせ、旅で出会ったみんなに「ぽかぽか村へ来て」と呼びかけた。',
  c8_01: '村に戻ると、根を伝う呼び声を聞きつけた影の獣が、村を襲っていた。魚屋のおばちゃんは「あんたに食べさせる魚くらい、いくらでも焼いてやるよ！」と言った。',
  c8_02: 'タマの呼び声を聞いて、村の広場に、旅で出会った猫たちが集まる。キングネズミは「魚……分けてやるよ。俺にとっては大事なんだ！」と魚を差し出した。小さな親切や友情が、樹をほんの少し光らせる。けれど声は軽く、孤独の沈む果てまでは下りていかない。果てに着いたらタマが根で呼び、みんなは村で声をそろえて送ることにした。',
  c8_03: '樹の根もとの東から、地面を這う太い根をたどって、音も色もない世界の果てへ。根は奈落へもぐりながら、浮かぶ石の道を支えていた。地の底には、世界じゅうの根の先が、何本もたれさがっていた。',
  c8_04: 'コドクとの最後の戦い。「五匹じゃない！　ぼくたちの後ろには、旅で出会ったみんながいる！」　各地の根から届いた声は、ひとつずつでは孤独に押しかえされた。けれど、ぽかぽか村で重ねた声が根を駆け下り、底まで届いた。',
  c8_05: '世界中の「つながり」が、コドクを光に変えた。「……私も……本当は……ひとりは、いやだった……」。孤独は光の粒になって昇り、タマは樹の目ざめを感じとった。',
  c8_05t: 'にゃんだーの樹の灰色の葉に、みどりが戻った。枝という枝に、笑い・友情・思い出・優しさの実がふくらんでいく。',
  c8_05b: 'そのころ、ぽかぽか村。声を送ったみんなが見上げる先で、にゃんだーの樹が光っていた。「……きれいだねえ」「……届いたんだな。俺たちの声」。',
  c8_05c: '地の底の果てにも、根を伝って光が下り、色が戻った。タマは樹にならずにすんだ。「ぼくたちは――」「ずっと仲間だ！」',
  c9_01: '数年後。マオウは猫カフェ、クロは冒険者ギルド、シロは魔法学校、タマは樹の管理人。そしてミケは、魚屋になった。「なんで勇者が魚屋なんじゃ」「魚が好きだから！」',
  c10_01: '猫神社の奥の、お菓子と魚の浮かぶ夢の世界へ。',
  c10_02: 'ミケの偽物、クロのぬいぐるみ、100匹のタマ。へんてこな夢はまだ続く。',
  c10_03: '夢の奥で待っていたのは、この世界を作った「ねこ神」。世界を救うのは「面倒なのでお前に任せた」らしい。',
  c10_04: 'ねこ神は、世界を救ったのは一行と、一行がつないだたくさんの心だと笑った。',
};

// ------------------------------------------------------------
//  物語の進行
//  away：その段階のあいだ、一行を離れている子（フィールドの隊列と戦闘に出ない。js/state.js の teamMembers）
// ------------------------------------------------------------
const STORY = [
  { title: '第一章　勇者、拾われる', steps: [
    { t: 'scene', id: 'c1_01', g: '魚どろぼう' },
    { t: 'scene', id: 'c1_02', g: '流れ星の夜' },
    { t: 'field', zone: 'hill', at: [0, 1], start: ['pokapoka', -17, -4], near: ['pokapoka', 'hill'], yaw: 1.3, scene: 'c1_03', g: '流れ星の落ちた、村はずれの丘へ行く' },
    { t: 'field', zone: 'pokapoka', at: [0, -9], scene: 'c1_04', g: '村に戻って、村長にクロのことを話す' },
    { t: 'field', zone: 'forest_in', at: [-2, -9], scene: 'c1_05', battle: '1-1', g: '村の南の、ほしふる森へ' },
    { t: 'field', zone: 'forest_deep', at: [-4, -5], scene: 'c1_06', battle: '1-2', g: 'ほしふる森の奥へ進む' },
    { t: 'field', zone: 'rat_nest', at: [0, -7], scene: 'c1_07', battle: '1-3', after: 'c1_08', g: '森の北、ネズミの王国をたずねる' },
    { t: 'field', zone: 'pokapoka', at: [0, 5], scene: 'c1_09', g: '村に帰って、村長に報告する' },
    { t: 'reward', niboshi: 300, g: '第一章 おしまい' },
  ] },
  { title: '第二章　にゃんこ大集合', steps: [
    { t: 'scene', id: 'c2_01', g: 'ミャオ街道へ' },
    { t: 'field', zone: 'road1', at: [1, 28], start: ['road1', -8, 42], near: ['road1', 'road_rest'], yaw: Math.PI, scene: 'c2_01b', g: '街道を北へ進む' },
    { t: 'field', zone: 'road_rest', at: [0, -1.5], scene: 'c2_02', battle: '2-1', after: 'c2_02b', g: '街道の宿場へ' },
    { t: 'field', zone: 'woods', at: [5, 6], scene: 'c2_03', g: '宿場の東、まどろみの林で眠っている子をさがす' },
    { t: 'field', zone: 'woods_valley', at: [9, 14], scene: 'c2_03g', g: '西の丘の綿毛につかまって川を越え、飛んでいった子を追って、ねむり花の谷へ' },
    { t: 'field', zone: 'woods_deep', at: [1, -19], scene: 'c2_03h', g: 'ねむり花の粉をよけながら、ねぼけ歩きの子を追って、林のいちばん奥へ' },
    { t: 'scene', id: 'c2_03i', g: 'タマ' },
    { t: 'field', zone: 'woods_valley', at: [8, 18], scene: 'c2_03j', battle: '2-2', after: 'c2_03b', g: 'タマをつれて、来た道を戻る（ねむり花の谷の花畑へ）' },
    { t: 'scene', id: 'c2_03c', g: '宿場の夜' },
    { t: 'scene', id: 'c2_03d', g: 'いなくなったシロ' },
    { t: 'field', zone: 'road1', at: [8, -2], start: ['road_rest', 1, 0], near: ['road_rest', 'road1'], away: ['shiro'], scene: 'c2_03e', battle: '2-3', after: 'c2_03f', g: '宿場の南、街道の風車の畑でシロをさがす' },
    { t: 'field', zone: 'road2', at: [0, -31], scene: 'c2_04', battle: '2-4', after: 'c2_05', g: '宿場の北、ごろごろ岩をよけて、ごろごろ切り通しを抜ける' },
    { t: 'field', zone: 'sekisho', at: [0, 28], scene: 'c2_04a', g: '切り通しの北、なかよし関所へ' },
    { t: 'field', zone: 'sekisho', at: [0, -28], scene: 'c2_06', g: '仲間のわざでなかよし関所のからくりを解き、北の大門へ' },
    { t: 'reward', niboshi: 400, g: '第二章 おしまい' },
  ] },
  { title: '第三章　笑わない街', steps: [
    { t: 'field', zone: 'nyahaha', at: [0, 22], scene: 'c3_01', g: 'ニャハハ王国に入る' },
    { t: 'field', zone: 'castle_in', at: [0, -6], scene: 'c3_02', g: '町の北、ニャハハ城の玉座の間で王さまに会う' },
    { t: 'field', zone: 'tower', at: [0, 14], scene: 'c3_03', battle: '3-1', g: '町の北東、笑顔の塔へ' },
    { t: 'field', zone: 'tower', at: [0, -9], scene: 'c3_03a', g: '大ロビーの奥、階段の間へ' },
    { t: 'field', zone: 'tower_2f', at: [0, 2], scene: 'c3_03c', g: '玉のりのリングで、三つの大玉をスポットライトの下にそろえて「むすっと幕」を上げ、二階の楽屋へ' },
    { t: 'field', zone: 'tower_3f', at: [0, 6], scene: 'c3_03b', battle: '3-2', after: 'c3_03d', g: '出し物のびっくり箱を、ちょうどの回数だけ巻いて開け、三階の空中ブランコの間へ' },
    { t: 'field', zone: 'tower_top', at: [0, -22], scene: 'c3_04', battle: '3-3', after: 'c3_05', g: 'トランポリンで島づたいに北の桟敷へ跳んで、塔の最上階・大舞台へ' },
    { t: 'scene', id: 'c3_06', g: '笑顔のかけら' },
    { t: 'reward', niboshi: 500, g: '第三章 おしまい' },
  ] },
  { title: '第四章　黒猫の過去', steps: [
    { t: 'field', zone: 'valley_village', at: [-12, 1], scene: 'c4_01', g: '城下町の東、くろねこ谷を抜けて谷の集落へ' },
    { t: 'field', zone: 'valley', at: [-16, -8], scene: 'c4_02', battle: '4-1', after: 'c4_02b', g: '谷の丘の上の墓標へ' },
    { t: 'field', zone: 'valley', at: [18, -5], scene: 'c4_02c', g: '谷の北東、川のほとりの野営あとで、影の四剣の記録をさがす' },
    { t: 'field', zone: 'cave', at: [0, 37], scene: 'c4_03', battle: '4-2', g: '谷の北、黒影洞窟へ' },
    { t: 'field', zone: 'cave', at: [2, -15], scene: 'c4_03b', g: '黒影洞窟の奥へ進む' },
    { t: 'field', zone: 'cave_lake', at: [-11, 15], scene: 'c4_03c', g: '光の水晶を三つ灯し、大水晶の光を光の鏡で影の壁まで導いて、洞窟の下の階へ' },
    { t: 'field', zone: 'cave_deep', at: [0, 35], scene: 'c4_03d', g: '最初の光が消える前に光の水晶を三つとも灯して橋の影の壁を消し、洞窟の最深部へ' },
    { t: 'field', zone: 'cave_deep', at: [0, -30], scene: 'c4_04', battle: '4-3', after: 'c4_05', g: '影の四剣が集まった順に記憶のかけらにふれて闇の扉を開き、三本の剣の眠る大広間へ' },
    { t: 'reward', niboshi: 600, g: '第四章 おしまい' },
  ] },
  { title: '第五章　眠れる子猫', steps: [
    { t: 'field', zone: 'ruins_out', at: [-6, 20], scene: 'c5_01', battle: '5-1', g: '谷の北西、古代遺跡へ' },
    { t: 'field', zone: 'ruins_hill', at: [0, -12.5], scene: 'c5_01b', g: '外庭の北、石畳の丘を上って、遺跡の入口へ' },
    { t: 'field', zone: 'ruins_in', at: [0, -4], scene: 'c5_02', clear: '5-2', g: '高台の「つながりの石畳」をひと筆でつないで入口の結界を消し、遺跡の中へ' },
    { t: 'field', zone: 'ruins_maze', at: [-18, 35], scene: 'c5_02b', g: '大広間の奥、崩れた回廊へ。入口の間の、白く光る水晶のもとへ' },
    { t: 'field', zone: 'ruins_maze', at: [0, -36], scene: 'c5_03', g: '時の水晶で「今」と「昔」を切りかえながら、小部屋をめぐって、回廊の奥の封印の扉へ' },
    { t: 'field', zone: 'ruins_seal', at: [0, 1], scene: 'c5_03b', battle: '5-3', after: 'c5_04', g: '開いた扉の奥、封印の間へ' },
    { t: 'reward', niboshi: 700, g: '第五章 おしまい' },
  ] },
  { title: '第六章　魔王城へ', steps: [
    { t: 'field', zone: 'demon_land', at: [-2, 24], scene: 'c6_01', battle: '6-1', g: '遺跡の東、魔王領へ' },
    { t: 'field', zone: 'demon_castle', at: [1, 14.2], scene: 'c6_01b', g: '魔王城に入り、大広間の受付へ' },
    { t: 'field', zone: 'demon_clinic', at: [-12, 8], scene: 'c6_02', battle: '6-2', after: 'c6_02b', g: '面会許可証のハンコ（0/5）：大広間の西、保健の間で健康診断を受ける' },
    { t: 'field', zone: 'demon_barracks', at: [-11, -23.5], scene: 'c6_k1', battle: '6-k1', after: 'c6_k1b', g: 'ハンコ（1/5）：大広間の東、兵の詰め所の奥の厨房で、四天王・炎のグツグツに会う' },
    { t: 'field', zone: 'demon_cellar', at: [-23.5, -18], scene: 'c6_k2', battle: '6-k2', after: 'c6_k2b', g: 'ハンコ（2/5）：大広間の北東の階段から地下倉庫へ。牢屋で眠る四天王・眠りのネムネムを起こす' },
    { t: 'field', zone: 'demon_court', at: [17, -5], scene: 'c6_k3', battle: '6-k3', after: 'c6_k3b', g: 'ハンコ（3/5）：大広間の北、中庭の花壇で、四天王・風のチョキチョキに会う' },
    { t: 'field', zone: 'demon_castle_2f', at: [0, -15.2], scene: 'c6_k4', battle: '6-k4', after: 'c6_k4b', g: 'ハンコ（4/5）：中庭の奥の高台から2Fの回廊へ。三階への階段の前で、最後の四天王に会う' },
    { t: 'field', zone: 'demon_throne', at: [0, -11], scene: 'c6_03', battle: '6-3', after: 'c6_04', g: 'ハンコ（5/5）：三階の玉座の間で、魔王に会う' },
    { t: 'reward', niboshi: 800, g: '第六章 おしまい' },
  ] },
  { title: '第七章　最後のにゃんこ', steps: [
    { t: 'field', zone: 'tree_root', at: [0, -20], start: ['tree_root', 0, -38], near: ['tree_root', 'tree_under', 'forest_deep'], scene: 'c7_01', g: 'にゃんだーの樹の根もとへ' },
    { t: 'field', zone: 'tree_root', at: [0, 33], scene: 'c7_01b', battle: '7-1', g: '根もとの南、根のトンネルの奥の扉へ' },
    { t: 'field', zone: 'tree_under', at: [0, -45], scene: 'c7_02', battle: '7-2', g: '封印の扉の奥、樹の地下へ' },
    { t: 'field', zone: 'tree_under_2', at: [0, -40], scene: 'c7_02b', g: '灰色の実を持ち上げて光らせ、しおれた根をよみがえらせて、奥の根の扉に実をそなえ、下の階へ' },
    { t: 'field', zone: 'tree_under_3', at: [1, -27], scene: 'c7_02c', g: '足もとからはなれた影を鏡うつしに動かして、自分と影を同時に光の輪へ入れ、下の階へ' },
    { t: 'field', zone: 'tree_under_3', at: [0, 2], scene: 'c7_03', battle: '7-3', after: 'c7_04', g: '広間の奥、樹の心臓のもとへ' },
    { t: 'reward', niboshi: 900, g: '第七章 おしまい' },
  ] },
  { title: '第八章　みんなのにゃん力', steps: [
    { t: 'scene', id: 'c8_01', g: 'ぽかぽか村の危機' },
    { t: 'battle', stage: '8-1', after: 'c8_02', g: '村を守る' },
    { t: 'field', zone: 'world_end', at: [0, 20], start: ['tree_root', 30, 14], near: ['tree_root', 'world_end'], scene: 'c8_03', battle: '8-2', g: '樹の根もとの東から、太い根をたどって世界の果てへ' },
    { t: 'field', zone: 'world_end', at: [0, -21], scene: 'c8_04', battle: '8-3', after: 'c8_05', g: 'コドクと決着をつける' },
    { t: 'scene', id: 'c8_05t', g: 'よみがえる樹' },
    { t: 'scene', id: 'c8_05b', g: 'そのころ、ぽかぽか村' },
    { t: 'scene', id: 'c8_05c', g: 'ずっと仲間' },
    { t: 'reward', niboshi: 1500, g: '第八章 おしまい' },
  ] },
  { title: 'エピローグ　それから', steps: [
    { t: 'scene', id: 'c9_01', g: 'それから' },
    { t: 'ending', g: 'Fin' },
  ] },
  { title: 'おまけ　ねこ神の夢', hidden: true, steps: [
    { t: 'field', zone: 'dream', at: [0, 20], scene: 'c10_01', battle: '9-1', g: '猫神社の奥から、夢の世界へ' },
    { t: 'field', zone: 'dream', at: [0, 6], scene: 'c10_02', battle: '9-2', g: 'へんてこ回廊を進む' },
    { t: 'field', zone: 'dream', at: [0, -15], scene: 'c10_03', battle: '9-3', after: 'c10_04', g: '夢の玉座へ' },
    { t: 'reward', niboshi: 2000, g: 'おまけ おしまい' },
  ] },
];
const STORY_MAIN = 8;

// シーンに章の名前を付け、舞台（stage）を集める
const SCENE_STAGES = {};
STORY.forEach(ch => ch.steps.forEach(st => [st.id, st.scene, st.after].filter(Boolean).forEach(id => { if (SCENES[id]) SCENES[id].chapter = ch.title.split('　')[0]; })));
for (const [id, sc] of Object.entries(SCENES)) { if (sc.stage) SCENE_STAGES[id] = sc.stage; if (!sc.chapter && id.startsWith('b_')) sc.chapter = '友情の特別イベント'; }

const RECAP = {
  chapters: [
    'ミャオニアの世界。にゃんだーの樹が見えるぽかぽか村から、三毛猫ミケの冒険が始まる。',
    '世界の異変を調べる旅。ミャオ街道で、ふしぎな仲間たちと出会う。',
    '「笑いの国」ニャハハ王国は、誰も笑わない街になっていた。',
    'クロの故郷、くろねこ谷。黒影洞窟の奥に、クロの過去が眠っている。',
    '古代遺跡の壁画が、世界の歴史と、にゃんだーの樹の秘密を語る。',
    '怖い場所のはずなのに、妙にコミカルな魔王領。魔王の城へ。',
    'ぽかぽか村の南にそびえる、にゃんだーの樹。その根元に、黒い何かがいる。',
    '旅で出会った猫たちが集まる。世界中のつながりで、最後の戦いへ。',
    'それから、数年後。',
    'クリア後に見つかる、ふしぎな夢の世界。',
  ],
  scenes: { ...RECAP_1, ...RECAP_2 },
};

// 物語の戦闘の場所（ステージ → 区画の戦場。at は地形マップの区画ならマス座標）
const BATTLE_SETS = {
  '1-1': { zone: 'forest_in', at: [-2, -18], face: 0 },
  '1-2': { zone: 'forest_deep', at: [-4, 0], face: 0 },
  '1-3': { zone: 'rat_nest', at: [0, -2], face: 0 },
  '2-1': { zone: 'road_rest', at: [0, -4], face: 0 },
  '2-2': { zone: 'woods_valley', at: [8, 18], face: 180 },
  '2-3': { zone: 'road1', at: [12, -2], face: 90 },
  '2-4': { zone: 'road2', at: [0, -27], face: 0 },
  '3-1': { zone: 'tower', at: [0, 16], face: 0 },
  '3-2': { zone: 'tower_3f', at: [0, 4], face: 0 },
  '3-3': { zone: 'tower_top', at: [0, -26], face: 0 },
  '4-1': { zone: 'valley', at: [-4, -12], face: 90 },
  '4-2': { zone: 'cave', at: [0, 39], face: 0 },
  '4-3': { zone: 'cave_deep', at: [0, -33], face: 0 },
  '5-1': { zone: 'ruins_out', at: [-2, 6], face: 0 },
  '5-2': { zone: 'ruins_in', at: [0, -12], face: 0 },
  '5-3': { zone: 'ruins_seal', at: [0, 1], face: 0 },
  '6-1': { zone: 'demon_land', at: [0, -8], face: 0 },
  '6-2': { zone: 'demon_clinic', at: [-12, 0], face: 0 },
  '6-k1': { zone: 'demon_barracks', at: [-11, -26.5], face: 0 },
  '6-k2': { zone: 'demon_cellar', at: [2, -4], face: 0 },
  '6-k3': { zone: 'demon_court', at: [0, 2], face: 0 },
  '6-k4': { zone: 'demon_castle_2f', at: [0, -18], face: 0 },
  '6-3': { zone: 'demon_throne', at: [0, -14], face: 0 },
  '7-1': { zone: 'tree_root', at: [0, -10], face: 180 },
  '7-2': { zone: 'tree_under', at: [0, -45], face: 180 },
  '7-3': { zone: 'tree_under_3', at: [0, 3], face: 180 },
  '8-1': { zone: 'pokapoka', at: [0, 12], face: 0 },
  '8-2': { zone: 'world_end', at: [0, 16], face: 0 },
  '8-3': { zone: 'world_end', at: [0, -26], face: 0 },
  '9-1': { zone: 'dream', at: [0, 10], face: 0 },
  '9-2': { zone: 'dream', at: [0, -2], face: 0 },
  '9-3': { zone: 'dream', at: [0, -14], face: 0 },
};

// 最終決戦：コドクが最後の姿になると、タマが根で呼び、世界じゅうの声が根を伝って届く。
// [名前, 台詞, 声が伝ってくる根（世界の果ての根の先）]。voices は各地の根から（ひとつずつでは押しかえされる）、chorus はぽかぽか村で重ねた声
CHAPTERS[7].stages[2].final = {
  voices: [
    ['タマ', '「……根から、声が……！　みんなの声が、とどいてる！」'],
    ['ネズミの王国の子ネズミたち', '「勇者さーん！　がんばれー！」', 'rat'],
    ['ニャハハ王国の民', '「わっはっは！　国じゅうで笑ってるぞー！」', 'kingdom'],
    ['くろねこ谷の猫たち', '「クロの仲間なら、谷の仲間だ！」', 'valley'],
    ['魔王城の四天王', '「魔王さま！　お客人がた！　負けてはなりませんぞ！」', 'castle'],
  ],
  push: ['コドク', '「……か細い声だ。ひとつずつでは、この底までは届かぬ」'],
  chorus: [
    ['ピエロとハチとブチ', '「笛と太鼓で、さあ、ショーのはじまりだ！」', 'village'],
    ['村長', '「ミケ！　みんな！　一人じゃないぞ！」', 'village'],
    ['魚屋のおばちゃん', '「帰ってきたら、焼き魚いくらでも食べさせてやるよ！」', 'village'],
    ['キングネズミ', '「魚……分けてやるって言っただろ！　負けるな、勇者！」', 'village'],
    ['ニャハハ王', '「笑え、笑うのじゃ！　ぶははははは！」', 'village'],
    ['クロネ婆', '「クロ！　もう、ひとりで背負うんじゃないよ！」', 'village'],
    ['魔族兵のベル', '「魔王さまーっ！　有給、ありがとうございましたーっ！」', 'village'],
    ['ハヤテ・リン・ゴロウ', '「クロ！　みんな！　行けーーっ！」'],
  ],
};

// 友情の特別イベント（友情Lv4）と、組み合わせのひとこと紹介
const BOND_EVENTS = {
  'kuro|mike': 'b_kuro_mike', 'mike|shiro': 'b_mike_shiro', 'mike|tama': 'b_mike_tama', 'maou|mike': 'b_maou_mike', 'kuro|shiro': 'b_kuro_shiro',
  'kuro|tama': 'b_kuro_tama', 'shiro|tama': 'b_shiro_tama', 'kuro|maou': 'b_kuro_maou', 'maou|shiro': 'b_maou_shiro', 'maou|tama': 'b_maou_tama',
};
const BOND_TAGS = {
  'kuro|mike': 'ボケとツッコミ', 'mike|shiro': '子ども同士の口げんか', 'mike|tama': '兄弟のよう', 'maou|mike': '勇者と元魔王', 'kuro|shiro': '真面目な二匹',
  'kuro|tama': 'クロがいちばん気にかけている', 'shiro|tama': 'シロが面倒を見る', 'kuro|maou': '無口同士で会話が短い', 'maou|shiro': 'シロの実験台', 'maou|tama': 'おひるね同盟',
};
