'use strict';
// ============================================================
//  にゃんこファンタジー 台本（第一章〜第四章）
//  行：[話者, 本文, 表示名(省略可), 演出(省略可)]  話者 'n' = ナレーション、'e:敵' = 敵
//  選択肢：{ c: [[ミケの台詞, [応答の行...], 演出], ...] }
//  { give: 'キャラ' } 仲間になる ／ { flag: '名前', say: '知らせ' } 物語のフラグ ／ { bond: [a, b, 点] } 友情
//  演出（js/stage.js）：f 表情 / g 身振り / to 相手 / r 周りの反応 / look 視線 / face 体の向き / stance 立ち方 /
//    move 歩く / hold 小物 / enter 登場 / exit 退場 / defeat 撃破 / fx 効果 / cam カメラ / later [秒, 演出] / bgm 曲
//  stage：どの区画のどこで演じるか（zone / at / face。at は地形マップの区画ならマス座標）。
//    仲間はその場面までに加わった子が自動で隊列を組み、ほかの人物は向かいに立つ。cast で個別に上書き
// ============================================================
const SCENES = {
  // ================= 第一章　勇者、拾われる =================
  c1_01: { title: '魚どろぼう', bgm: 'village',
    stage: { zone: 'pokapoka', at: [12, 1.5], face: 90, host: 'sakanaya',
      cast: { mike: { at: [0, 0], item: 'fish' }, sakanaya: { at: [0.2, 2.6], face: 'mike' }, sonchou: { at: [-2.5, -5], hidden: true, face: 'mike' } },
      points: { tree: [120, 30, 20] }, wide: { pos: [-3.4, 2.1, -4.4], look: [0.7, 0.6, 1.8] } },
    lines: [
      ['n', 'ミャオニアの世界。南の丘の向こうに、大きな「にゃんだーの樹」が見える、ぽかぽか村。……今日も、平和な朝。', { cam: 'wide', dur: 7, r: { mike: 'joy' } }],
      ['n', '……のはずだった。', { cam: 'mike', close: true, r: { mike: ['smile', 'hop'] } }],
      ['sakanaya', 'あっ！　ミケ！　また魚盗ったね！', { f: 'angry', g: 'point', to: 'mike', r: { mike: ['surprise', 'recoil'] } }],
      ['mike', 'と、盗ってないよ！　ちょっと持ってるだけ！', { f: 'surprise', g: 'shrug' }],
      ['sonchou', 'ミケ！　また魚を盗ったな！', { enter: 'sonchou', move: { sonchou: [[-2, -2], [-1.3, 1.2]] }, speed: 3, f: 'angry', g: 'shake', look: { mike: 'sonchou' } }],
      ['mike', '違うよ！　これは味見！', { f: 'joy', g: 'raise', to: 'sonchou' }],
      ['sonchou', '昨日も味見していただろ！', { f: 'angry', g: 'point', r: { sakanaya: ['angry', 'nod'] } }],
      ['sakanaya', 'おとといもだよ！', { f: 'angry', g: 'fist' }],
      { c: [
        ['……ごめんなさい。', [['sakanaya', '……まったく。ちゃんと謝れるなら、今回だけは許してあげるよ。', { f: 'gentle', g: 'nod' }], ['sonchou', 'ミケや、腹が減ったら、ちゃんと言いなさい。村のみんなは家族みたいなもんじゃ。', { f: 'gentle', g: 'handChest' }]], { f: 'sad', g: 'bow' }],
        ['でも、すっごくおいしかったよ！', [['sakanaya', '感想は聞いてないよ！', { f: 'angry', g: 'fist' }], ['sonchou', '……ほっほっ。……いや、笑っとる場合か。', { f: 'smile', g: 'shake' }]], { f: 'joy', g: 'cheer' }],
      ] },
      ['sonchou', '今年は、にゃんだーの樹の実りがとても悪い。村の魚も、いつもより大事にせんとな。', { f: 'worry', g: 'explain', look: { all: 'tree' } }],
      ['mike', '樹の実り……？', { f: 'neutral', g: 'tilt' }],
      ['n', 'こうして、いつものように叱られたミケ。……その夜、空に、大きな流れ星が走った。', { cam: 'wide', dur: 7 }],
    ] },
  c1_02: { title: '流れ星の夜', bgm: 'sad',
    stage: { zone: 'hill', at: [0, 12], face: 0, bg: 'night',
      cast: { mike: { at: [0, 0], stance: 'kneel', f: 'gentle' } },
      points: { crater: [0, 0.5, 16], sky: [0, 8, 30] },
      wide: { pos: [-2.6, 1.0, -3.4], look: [0.4, 0.8, 5] } },
    lines: [
      ['n', 'その夜。村はずれの丘で、ミケはひとり、星を見ていた。', { cam: 'wide', dur: 8, look: { mike: 'sky' } }],
      ['mike', '……お父さん、お母さん。ぼく、今日も元気だよ。', { f: 'gentle', g: 'lookUp', look: { mike: 'sky' } }],
      ['mike', '……今日も魚、おいしかった。……へへ。', { f: 'smile', look: { mike: 'sky' } }],
      ['n', 'ミケは、小さいころに両親をモンスターに奪われている。……そのことを思い出すと、胸の奥がちくりと痛む。だから、いつも笑っていることにしていた。', { cam: 'mike', close: true, dur: 8, r: { mike: 'sad' } }],
      ['n', 'そのとき——', { fx: 'meteor:crater', cam: 'look:crater', dur: 6, stance: { mike: 'idle' }, look: { mike: 'crater' } }],
      ['mike', 'わっ、わわっ！？　流れ星が……こっちに落ちてくるーーっ！！', { f: 'surprise', g: 'recoil', later: [0.6, { shake: 0.4 }] }],
      ['n', 'すさまじい光と音。丘の向こうに、何かが落ちた。', { cam: 'wide', dur: 6, r: { mike: ['surprise', 'recoil'] } }],
      ['mike', '……こ、こわくないし！　明日の朝、ちょっと見に行くだけだし！', { f: 'worry', g: 'fist' }],
    ] },
  c1_03: { title: '空から来た黒猫', bgm: 'village',
    stage: { zone: 'hill', at: [0, 6], face: 0,
      cast: { mike: { at: [0, 0] }, kuro: { at: [0.4, 9.4], stance: 'down', f: 'pained', face: 'mike' } },
      points: { rock: [0, 1, 10], tree: [10, 30, -120] },
      wide: { pos: [-3.2, 2.2, 0.6], look: [0.2, 0.4, 8.5] } },
    lines: [
      ['n', '翌朝。流れ星の落ちたところへ行ってみると……', { cam: 'wide', dur: 7 }],
      ['mike', '……だ、だれか倒れてる！？', { f: 'surprise', g: 'surprise', move: { mike: [0, 7.4] }, speed: 2.8 }],
      ['mike', 'ねえ、だいじょうぶ？　生きてる？', { f: 'worry', g: 'offer', to: 'kuro' }],
      ['kuro', '……………', { f: 'pained', stance: { kuro: 'weak' } }],
      ['kuro', '……世界が滅びる。', { f: 'serious', stance: { kuro: 'idle' }, look: { kuro: 'mike' }, r: { mike: 'surprise' } }],
      ['mike', 'その前に、腹減ってない？', { f: 'smile', g: 'offer', hold: { mike: 'fish' }, to: 'kuro' }],
      ['kuro', '……は？', { f: 'surprise', g: 'tilt' }],
      ['n', 'ぐうぅ〜〜〜。……黒猫のおなかが、盛大に鳴った。', { cam: 'kuro', close: true, r: { kuro: 'shy' } }],
      ['kuro', '……面倒だ。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'へへっ、はい、半分こ！　ぼくはミケ。きみは？', { f: 'joy', g: 'give', r: { kuro: 'surprise' } }],
      ['kuro', '……クロだ。', { f: 'serious', hold: { mike: null, kuro: 'fish' } }],
      ['kuro', '……星を追っていた。……いや、あれは星じゃない。にゃんだーの樹の、「友情の実」だ。……樹の実は、夜になると光る。', { f: 'serious', g: 'point', look: { kuro: 'rock', mike: 'rock' }, cam: 'look:rock', dur: 6 }],
      ['mike', '実！？　食べられる！？', { f: 'joy', g: 'hop', look: { mike: 'rock' } }],
      ['kuro', '……落ちて、割れた。……まだ、熟してもいなかった。', { f: 'serious', r: { mike: ['sad', 'lookDown'] } }],
      ['kuro', '樹は弱ると、熟す前の実を落とす。……世界中で、猫たちの心のつながりが消えかけている。……このままだと、世界が滅びる。', { f: 'serious', g: 'explain', look: { kuro: 'tree' } }],
      ['mike', 'よくわかんないけど……それって、大変ってこと？', { f: 'worry', g: 'tilt' }],
      ['kuro', '……ああ。大変だ。', { f: 'serious', g: 'nod' }],
      { c: [
        ['じゃあ、いっしょに何とかしようよ！', [['kuro', '……俺は、一人でいい。', { f: 'serious', g: 'turnAway' }], ['mike', 'ぼくが勝手についていくから、いいでしょ？', { f: 'joy', g: 'hop' }], ['kuro', '……好きにしろ。', { f: 'shy', g: 'shrug' }]], { f: 'joy', g: 'fist', bond: ['mike', 'kuro', 6] }],
        ['それより、魚もう一匹食べる？', [['kuro', '……話を聞け。', { f: 'angry', g: 'shake' }], ['kuro', '……もらう。', { f: 'shy' }]], { f: 'smile', g: 'offer', bond: ['mike', 'kuro', 3] }],
      ] },
      { give: 'kuro' },
      ['mike', 'まずは村長に知らせなきゃ！　村に戻ろう、クロ！', { f: 'joy', g: 'point', face: { mike: [0, -8] } }],
      ['kuro', '……引っぱるな。', { f: 'serious', move: { kuro: [1.1, 6] } }],
    ] },
  c1_04: { title: '村長の頼み',
    stage: { zone: 'pokapoka', at: [0, -7], face: 0, host: 'sonchou', cast: { sonchou: { at: [0, 2.6], face: 'mike' } } },
    lines: [
      ['sonchou', '空から猫が落ちてきた、じゃと？', { f: 'surprise', g: 'surprise', to: 'mike' }],
      ['kuro', '……クロだ。', { f: 'serious', g: 'nod', to: 'sonchou' }],
      ['sonchou', '……ふむ。わしも気になっておった。今年は、にゃんだーの樹の実りがとても悪い。森の木の実も、ほとんど実らなかった。', { f: 'worry', g: 'explain' }],
      ['sonchou', 'そのせいかのう。ほしふる森のネズミどもが、夜な夜な村の食べ物を持っていくんじゃ。', { f: 'worry', g: 'point', look: { all: 'forest' } }],
      ['mike', 'ネズミ！？　ぼくの魚も！？', { f: 'angry', g: 'fist' }],
      ['sonchou', '……お前の魚は、お前が盗ったんじゃろうが。', { f: 'serious', g: 'shake' }],
      ['kuro', '……盗ったのか。', { f: 'serious', g: 'tilt', to: 'mike' }],
      ['mike', '味見！', { f: 'joy', g: 'raise' }],
      ['sonchou', '森の奥に、ネズミの王国があるらしい。ミケ、クロどの。様子を見てきてはくれんか。……無理はするでないぞ。', { f: 'gentle', g: 'offer' }],
      ['mike', '任せて！　行こう、クロ！', { f: 'joy', g: 'fist', to: 'kuro' }],
      ['kuro', '……面倒だ。', { f: 'serious', g: 'turnAway', later: [1.6, { r: { kuro: ['neutral', 'nod'] } }] }],
      ['n', '【目的】村の東から、ほしふる森へ。（村の武器屋では「にぼし」で武器を鍛えられる。宿屋で休むとHPが回復する）', { cam: 'wide', dur: 6 }],
    ] },
  c1_05: { title: 'ほしふる森', cast: ['e:slime'], bgm: 'field',
    stage: { zone: 'forest_in', at: [-2, -8], face: 0,
      cast: { 'e:slime': [{ at: [-1.4, 5.6], hidden: true }, { at: [1.3, 6.2], hidden: true }] },
      points: { sky: [0, 10, 12] } },
    lines: [
      ['n', 'ほしふる森。夜になると、空から小さな星が降るという森。昼間でも、光の粒がきらきらと舞っている。', { cam: 'wide', dur: 7, look: { all: 'sky' } }],
      ['mike', 'わあ……！　きらきらしてる！', { f: 'joy', g: 'cheer' }],
      ['kuro', '……はしゃぐな。何か来る。', { f: 'serious', stance: { kuro: 'ready' }, look: { kuro: [0, 1, 6] } }],
      ['e:slime', 'ぷにーっ！', { enter: 'e:slime', r: { mike: 'surprise' } }],
      ['mike', 'スライムだ！　よーし、ぼくが——', { f: 'joy', g: 'fist', stance: { mike: 'ready' } }],
      ['kuro', '……下がってろ。俺一人でいい。', { f: 'serious', g: 'turnAway', move: { kuro: [0.4, 1.4] } }],
      ['mike', 'なんで！？　二人のほうが強いに決まってるじゃん！', { f: 'angry', g: 'fist', to: 'kuro' }],
      ['n', '（ヒント：敵の頭の上に出ている属性が弱点。弱点で攻撃すると、白い「靭性ゲージ」が減って「弱点撃破」できる）', { cam: 'wide', dur: 6 }],
    ] },
  c1_06: { title: '森の奥で', cast: ['e:risu', 'e:nezumi'], bgm: 'field',
    stage: { zone: 'forest_deep', at: [-4, -4], face: 0,
      cast: { 'e:risu': [{ at: [-1.6, 6], hidden: true }, { at: [1.6, 6.4], hidden: true }], 'e:nezumi': { at: [0, 7], hidden: true } } },
    lines: [
      ['kuro', '……勝手に前に出るな。危ないだろ。', { f: 'angry', g: 'shake', to: 'mike' }],
      ['mike', 'クロだって、ひとりで突っこんでたじゃん！', { f: 'pout', g: 'point' }],
      ['kuro', '……俺は、いいんだ。', { f: 'sad', g: 'lookDown' }],
      ['mike', 'よくないよ！', { f: 'angry', g: 'fist' }],
      ['n', '言い合う二人の前に、怒ったリスたちが飛び出してきた！', { enter: ['e:risu', 'e:nezumi'], cam: 'wide', r: { all: 'surprise' } }],
      ['e:risu', 'ここから先は通さないぞ！　ぼくたちのどんぐりは、あげないんだから！'],
      ['mike', 'どんぐりなんていらないよ！　……ちょっと食べてみたいけど。', { f: 'smile', g: 'shrug' }],
      ['kuro', '……来るぞ。', { f: 'serious', stance: { all: 'ready' } }],
    ] },
  c1_07: { title: 'ネズミの王国', cast: ['e:king_nezumi'], bgm: 'boss',
    stage: { zone: 'rat_nest', at: [0, -6], face: 0, cast: { 'e:king_nezumi': { at: [0, 9.5] } }, points: { food: [-10, 1, 2] } },
    lines: [
      ['n', '大きな木の根の下に、ネズミたちの王国があった。村から持ってきた食べ物が、山のように積まれている。', { cam: 'wide', dur: 7, look: { all: 'food' } }],
      ['mike', 'あーっ！　村の食べ物！　……あれ？　ぜんぜん食べてない？', { f: 'surprise', g: 'point', look: { mike: 'food' } }],
      ['e:king_nezumi', '……誰だ。俺の王国に、勝手に入ってくるやつは。', { look: { all: 'e:king_nezumi' } }],
      ['kuro', '……村の食べ物を、返してもらう。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['e:king_nezumi', '返さん！　これは……これは、みんなの冬のぶんだ！'],
      ['mike', 'ねえ、話を聞いて——', { f: 'worry', g: 'offer' }],
      ['e:king_nezumi', '問答無用！　かかってこい！', { shake: 0.4 }],
      ['kuro', '……来い。', { f: 'angry', stance: { all: 'ready' }, cam: 'wide' }],
    ] },
  c1_08: { title: '「食べたかったんだよ」', bgm: 'sad', extra: ['kodomo_nezumi'],
    stage: { zone: 'rat_nest', at: [0, -6], face: 0, host: 'king_npc',
      cast: { king_npc: { at: [0, 3.4], stance: 'kneel', face: 'mike', f: 'sad' }, kodomo_nezumi: { at: [3, 6], hidden: true, face: 'king_npc' } } },
    lines: [
      ['king_npc', '……くそっ……。', { f: 'sad', g: 'lookDown' }],
      ['king_npc', '俺だって……食べたかったんだよ……。', { f: 'cry', g: 'bothChest', r: { mike: 'sad', kuro: 'serious' } }],
      ['king_npc', '今年は、森のどんぐりが、ぜんぜん実らなかった。子どもたちに……食わせてやれなくて……。', { f: 'cry', g: 'lookDown' }],
      ['kodomo_nezumi', '王さま！', { enter: 'kodomo_nezumi', move: { kodomo_nezumi: [1.1, 4.2] }, speed: 3, f: 'worry' }],
      ['king_npc', 'だから、村の食べ物に手を出した。……でも、盗んだものを子どもに食わせるのは、どうしても……できなかった。', { f: 'sad', g: 'shake' }],
      ['mike', '…………。', { f: 'sad', look: { mike: 'king_npc' } }],
      ['mike', '……じゃあ、これ。ぼくの魚、分けてあげる。', { f: 'gentle', g: 'give', hold: { mike: 'fish' }, to: 'king_npc' }],
      ['king_npc', '……いいのか。お前だって、腹が減ってるんだろ。', { f: 'surprise', g: 'surprise' }],
      ['mike', 'おなかが減ってるときに、ひとりで食べても、おいしくないもん！', { f: 'joy', g: 'hop', hold: { mike: null, king_npc: 'fish' }, r: { kuro: 'surprise' } }],
      ['kuro', '……（こいつ……）', { f: 'surprise', cam: 'kuro', close: true }],
      { bond: ['mike', 'kuro', 8] },
      ['king_npc', '……恩に着る。村の食べ物は、ちゃんと返そう。……この借りは、いつか必ず返す。', { f: 'gentle', g: 'bow', stance: { king_npc: 'idle' } }],
      ['kuro', '……木の実が実らないのは、この森だけじゃない。にゃんだーの樹が、弱っているんだ。', { f: 'serious', g: 'explain', to: 'mike' }],
      ['n', 'ミケはまだ知らなかった。この小さな出来事が、ずっと先で、世界を救う力になることを。', { cam: 'wide', dur: 7 }],
    ] },
  c1_09: { title: '旅立ち', bgm: 'hope',
    stage: { zone: 'pokapoka', at: [0, 10], face: 0, host: 'sonchou',
      cast: { sonchou: { at: [-0.8, 2.6], face: 'mike' }, sakanaya: { at: [4, 5], hidden: true, face: 'mike' } } },
    lines: [
      ['sonchou', 'そうか……ネズミたちも、腹をすかせておったのか。', { f: 'sad', g: 'lookDown' }],
      ['sonchou', '……実はな、旅の商人から妙な噂を聞いた。北のニャハハ王国では、誰も笑わなくなったそうじゃ。', { f: 'worry', g: 'explain' }],
      ['sonchou', '笑い声も、どこでも少しずつ減っておる。けんかしたまま口をきかなくなる猫や、思い出話をしなくなる猫も、あちこちで増えておるらしい。', { f: 'worry', g: 'shake' }],
      ['kuro', '……やはりな。世界中で、心のつながりが消えかけている。', { f: 'serious', g: 'nod' }],
      ['mike', 'それって、魔王のしわざ？　北の魔王領には、「世界を滅ぼす」って言ってる魔王がいるんでしょ？', { f: 'worry', g: 'tilt' }],
      ['sonchou', '……そう言うておるらしいがの。じゃが、魔王に何かされたという話は、とんと聞かん。怖がられておるだけの、ふしぎな王さまじゃよ。', { f: 'neutral', g: 'shake' }],
      ['kuro', '……。', { f: 'serious', g: 'turnAway', cam: 'kuro', close: true }],
      ['mike', '……つながりが消えたら、みんな、ひとりぼっちになっちゃうんだよね。', { f: 'sad', g: 'lookDown' }],
      ['mike', '……ひとりぼっちは、さみしいよ。', { f: 'sad', cam: 'mike', close: true, r: { kuro: 'surprise' } }],
      ['mike', 'よーし！　じゃあ、ぼくたちが原因を調べてくる！', { f: 'joy', g: 'fist' }],
      ['kuro', '……「たち」？', { f: 'surprise', g: 'tilt' }],
      ['mike', 'ぼくとクロ！', { f: 'joy', g: 'point', to: 'kuro' }],
      ['kuro', '……面倒だ。', { f: 'shy', g: 'turnAway', r: { mike: ['joy', 'laugh'] } }],
      ['sakanaya', 'ミケ！', { enter: 'sakanaya', move: { sakanaya: [1.2, 2.4] }, speed: 3, look: { all: 'sakanaya' } }],
      ['sakanaya', '……ほら、弁当。焼き魚、入れといたよ。', { f: 'gentle', g: 'give', hold: { sakanaya: 'fish' } }],
      ['mike', 'おばちゃん……！', { f: 'joy', g: 'cheer' }],
      ['sakanaya', 'お代は、ちゃんと帰ってきてから払いな！', { f: 'smile', g: 'point', hold: { sakanaya: null, mike: 'fish' } }],
      ['sonchou', '北のミャオ街道を進めば、ニャハハ王国じゃ。……気をつけて行っておいで。', { f: 'gentle', g: 'wave' }],
      ['n', 'こうして、ミケとクロの冒険が始まった。', { cam: 'wide', dur: 7, r: { mike: ['joy', 'wave'] } }],
    ] },

  // ================= 第二章　にゃんこ大集合 =================
  c2_01: { title: 'ミャオ街道', bgm: 'field',
    stage: { zone: 'road1', at: [-4, 30], face: 0 },
    lines: [
      ['n', 'ミャオ街道。ぽかぽか村から北へ続く、長い長い道。', { cam: 'wide', dur: 7 }],
      ['mike', 'ねえクロ、クロってどこから来たの？', { f: 'smile', g: 'tilt', to: 'kuro' }],
      ['kuro', '……遠くだ。', { f: 'serious' }],
      ['mike', '遠くって？', { f: 'neutral', g: 'tilt' }],
      ['kuro', '……遠くは、遠くだ。', { f: 'serious', g: 'turnAway' }],
      ['mike', 'ふーん。じゃあ、好きな食べ物は？', { f: 'smile' }],
      ['kuro', '……しつこい。', { f: 'angry', g: 'shake' }],
      ['mike', 'ぼくは魚！', { f: 'joy', g: 'raise' }],
      ['kuro', '……聞いてない。', { f: 'serious', r: { mike: ['joy', 'laugh'] } }],
      { bond: ['mike', 'kuro', 5] },
      ['n', '【目的】街道を北へ進もう。', { cam: 'wide', dur: 5 }],
    ] },
  c2_01b: { title: 'けんかした二匹', bgm: 'village',
    stage: { zone: 'road1', at: [1, 27], face: 0,
      cast: { hachi: { at: [-1.2, 3.2], face: [-8, 3.2] }, buchi: { at: [1.4, 3.6], face: [8, 3.6] } } },
    lines: [
      ['n', '道しるべの手前で、二匹の猫が、たがいにそっぽを向いて立っていた。', { cam: 'wide', dur: 6 }],
      ['hachi', '……ここでお別れだな。おれは北へ行く。', { f: 'angry', g: 'armsCrossed' }],
      ['buchi', '勝手にすれば。あたしは西の池のほうへ行くから。', { f: 'pout', g: 'turnAway' }],
      ['mike', 'ねえねえ、けんか？', { f: 'neutral', g: 'tilt', move: { mike: [0, 1.2] } }],
      ['kuro', '……首をつっこむな。', { f: 'serious', to: 'mike' }],
      ['hachi', '……旅芸人のハチだ。こっちは相棒の……いや、元・相棒のブチ。', { f: 'serious', g: 'point', face: { hachi: 'mike' } }],
      ['buchi', '「元」って言った！？　……ふん、いいけどさ。', { f: 'angry', g: 'fist', face: { buchi: 'hachi' } }],
      ['mike', 'なんでけんかしたの？', { f: 'worry', g: 'tilt' }],
      ['hachi', 'なんでって……そりゃあ……。', { f: 'serious', g: 'think' }],
      ['buchi', '……あれ？　なんでだっけ。', { f: 'surprise', g: 'tilt', look: { buchi: 'hachi' } }],
      ['hachi', '……わからん。ただ、最近なんだか、いっしょにいるのが……面倒になってな。', { f: 'sad', g: 'lookDown' }],
      ['kuro', '…………。', { f: 'serious', cam: 'kuro', close: true }],
      ['buchi', 'あたしもだよ。十年もいっしょに旅してきたのにさ。……楽しかったこと、ぜんぜん思い出せないんだ。', { f: 'sad', g: 'shake', face: { buchi: 'mike' } }],
      ['mike', 'ええっ、十年も！？　じゃあ、ふたりがはじめて会ったのは？', { f: 'surprise', g: 'surprise' }],
      ['buchi', 'はじめて……？', { f: 'neutral', g: 'think' }],
      ['hachi', '……ひょうたん池だ。池のほとりで笛の練習をしてたら、へたくそだって、こいつが太鼓で合わせてきて……。', { f: 'gentle', g: 'lookUp', look: { hachi: [-12, 2] } }],
      ['buchi', '……そうだ。夕焼けの中で、日が暮れるまで、ふたりで鳴らしてた。', { f: 'gentle', g: 'handChest' }],
      ['mike', 'その曲、聞かせてよ！　ぼく、聞いてみたい！', { f: 'joy', g: 'offer' }],
      ['buchi', '……しょうがないね。一曲だけだよ。', { f: 'shy', g: 'shrug', face: { buchi: 'hachi', hachi: 'buchi' } }],
      ['n', 'ぴいひゃら、とん、とん。……笛と太鼓は、はじめはぎこちなく、やがて、ぴたりと重なった。', { cam: 'wide', dur: 7, r: { mike: ['joy', 'cheer'], kuro: 'gentle' } }],
      ['hachi', '……ははっ。……なんだ、まだ合うじゃないか。', { f: 'smile', g: 'laugh', to: 'buchi' }],
      ['buchi', '……ばか。あんたが走りすぎなんだよ。', { f: 'smile', g: 'laugh' }],
      ['hachi', '……もう少しだけ、いっしょに行くか。池に寄ってから、北へな。', { f: 'gentle', g: 'nod' }],
      ['buchi', '……うん。', { f: 'gentle', g: 'nod' }],
      ['hachi', 'ありがとな、小さい旅人さん。宿場の茶屋のおやじに、よろしく言っといてくれ。', { f: 'smile', g: 'wave', face: { hachi: 'mike' } }],
      ['n', '二匹は、並んで池のほうへ歩いていった。', { exit: ['hachi', 'buchi'], cam: 'wide' }],
      ['mike', 'よかったあ！　仲直りできたね！', { f: 'joy', g: 'hop' }],
      ['kuro', '……十年いっしょにいた相棒が、けんかの理由も、楽しかったことも忘れる。……ふつうじゃない。', { f: 'serious', g: 'explain' }],
      ['kuro', '……世界中で、つながりが薄れている。思い出まで、消えかけているんだ。', { f: 'serious', g: 'lookDown' }],
      ['mike', 'でも、ちょっと思い出したら、ちゃんと戻ったよ？', { f: 'smile', g: 'tilt', to: 'kuro' }],
      ['kuro', '……（いっしょにいるのが、面倒になった……か）', { f: 'sad', g: 'turnAway', cam: 'kuro', close: true }],
      ['mike', 'クロ？　どうしたの？', { f: 'neutral', g: 'tilt' }],
      ['kuro', '……なんでもない。行くぞ。', { f: 'serious', g: 'shake' }],
      { bond: ['mike', 'kuro', 4] },
      ['n', '【目的】街道の宿場をめざそう。', { cam: 'wide', dur: 5 }],
    ] },
  c2_02: { title: '自称・天才魔法使い', cast: ['e:karasu', 'e:noraInu'], extra: ['tabibito_a', 'tabibito_b'],
    stage: { zone: 'road_rest', at: [0, 5.5], face: 0, host: 'shiro',
      cast: { shiro: { at: [0, 3], face: [0, 0], stance: 'hipHand' }, tabibito_a: { at: [-2.6, 3.4], face: 'shiro' }, tabibito_b: { at: [2.5, 3.2], face: 'shiro' },
        'e:karasu': { at: [-3, 7], hidden: true }, 'e:noraInu': { at: [2.6, 7.4], hidden: true } } },
    lines: [
      ['n', '宿場の広場に、人だかりができている。その真ん中で、白い猫が胸を張っていた。', { cam: 'wide', dur: 7, look: { all: 'shiro' } }],
      ['shiro', 'さあさあ、よってらっしゃい！　世界一の天才魔法使い、シロさまの魔法をお見せするわ！', { f: 'smug', g: 'raise' }],
      ['mike', '天才魔法使い！？　すごーい！', { f: 'joy', g: 'cheer' }],
      ['kuro', '……自分で言うやつほど、あやしい。', { f: 'serious', to: 'mike' }],
      ['shiro', 'そこ！　聞こえてるわよ！　……見てなさい。ファイア！', { f: 'angry', g: 'point', to: 'kuro', later: [1.4, { fx: ['spell:shiro', 'fishRain:shiro'] }] }],
      ['n', '……空から、魚が降ってきた。', { cam: 'wide', dur: 5, r: { all: 'surprise' } }],
      ['mike', 'わーい！　魚だーー！！', { f: 'joy', g: 'cheer', r: { tabibito_b: ['surprise', 'recoil'] } }],
      ['shiro', 'ち、ちがっ……今のは、その……わざとよ！　魚をおいしく焼く前の、準備の魔法なの！', { f: 'shy', g: 'shrug' }],
      ['kuro', '……失敗だろ。', { f: 'serious' }],
      ['shiro', '失敗じゃない！　わたしは天才だから、失敗なんかしないの！', { f: 'angry', g: 'fist' }],
      ['n', 'そのとき、カラスとのら犬の群れが、降ってきた魚をねらって飛びこんできた！', { enter: ['e:karasu', 'e:noraInu'], shake: 0.3, r: { all: 'surprise' } }],
      ['shiro', 'ちょうどいいわ！　天才の実力、見せてあげる！', { f: 'smug', stance: { shiro: 'ready' }, face: { shiro: 'e:karasu' } }],
      ['mike', 'いっしょにやろう、シロ！', { f: 'joy', stance: { all: 'ready' } }],
    ] },
  c2_02b: { title: 'シロ', extra: ['chaya'],
    stage: { zone: 'road_rest', at: [0, 5.5], face: 0, host: 'shiro',
      cast: { shiro: { at: [0, 2.6], face: 'mike' }, chaya: { at: [-3.5, 4], hidden: true, face: 'mike' } } },
    lines: [
      ['shiro', 'ま、まあ、なかなかやるじゃない。わたしほどじゃないけど。', { f: 'smug', g: 'hipHand' }],
      ['mike', 'シロの雷、すごかった！', { f: 'joy', g: 'cheer' }],
      ['shiro', 'で、でしょ？　……あなたたち、こんなところで何してるの？', { f: 'shy', g: 'tilt' }],
      ['mike', '世界がおかしくなってる原因を、調べてるんだ！　シロも一緒に来ない？', { f: 'smile', g: 'offer' }],
      ['shiro', '……ふーん。まあ、天才のわたしがいないと困るでしょうし？　ニャハハ王国の大図書館にも、行ってみたかったし？', { f: 'shy', g: 'turnAway' }],
      ['kuro', '……素直に来たいと言え。', { f: 'serious' }],
      ['shiro', 'うるさいわね！', { f: 'angry', g: 'fist', to: 'kuro' }],
      { give: 'shiro' },
      ['chaya', 'あんたたち、ちょっといいかい。', { enter: 'chaya', move: { chaya: [-2, 3] }, look: { all: 'chaya' } }],
      ['chaya', '東の「まどろみの林」でね、ずーっと眠ってる子がいるんだ。もう何日も起きなくて……心配でねえ。', { f: 'worry', g: 'point' }],
      ['shiro', '何日も！？　それは大変！　……べ、別に心配してるわけじゃないけど、行くわよ！', { f: 'worry', g: 'point' }],
      ['n', '【目的】宿場の東、「まどろみの林」へ。', { cam: 'wide', dur: 5 }],
    ] },
  // まどろみの林：眠ったままの子猫が、ハプニングに次々と巻きこまれていく（綿毛で飛ぶ → ねむり花 → どんぐりにまちがえられる）
  c2_03: { title: '綿毛の上の子猫', bgm: 'village',
    stage: { zone: 'woods', at: [5, 7], face: 0, host: 'tama',
      cast: { tama: { at: [0, 6], y: 5.6, stance: 'sleep', f: 'sleepy', face: [0, 0] } },
      points: { top: [0, 5, 6], far: [-6, 9, 36], hill: [-24, 3, 18] },
      // 綿毛のてっぺんを見上げる／飛んでいく綿毛を追う
      shots: { up: { pos: [3.4, 1.6, 0.6], look: [0, 5.2, 6] }, lift: { pos: [4.5, 2, -1.5], look: [0, 8.2, 6] }, fly: { pos: [3, 1.8, 1], look: [-2.5, 8, 16] } } },
    lines: [
      ['n', 'たんぽぽの原のまん中に、見上げるほど大きなたんぽぽが一本、すっくと立っていた。', { cam: 'up', dur: 6, look: { all: 'top' } }],
      ['n', '……そのまんまるい綿毛のてっぺんで、小さな猫が、丸くなって眠っていた。', { cam: 'up', dur: 7, look: { all: 'tama' } }],
      ['mike', '……ほんとに寝てる。しかも、あんな高いところで！', { f: 'surprise', g: 'lookUp', move: { mike: [0, 2.6] }, speed: 1.6 }],
      ['kuro', '……頭に、芽が生えている。', { f: 'surprise', look: { kuro: 'tama' } }],
      ['mike', 'ほんとだ！　かわいい！', { f: 'joy', g: 'hop' }],
      ['tama', '……すぴー……。', { f: 'sleepy', fx: 'zzz:tama', cam: 'up', dur: 4 }],
      ['shiro', 'ちょっと、起きなさい！　そんなところで寝てたら、落っこちるわよ！', { f: 'worry', g: 'offer', to: 'tama', move: { shiro: [1.4, 2.6] } }],
      ['tama', '……すぴー……。', { f: 'sleepy', fx: 'zzz:tama', cam: 'up', dur: 4 }],
      ['shiro', 'もう！　……すうっ……。', { f: 'pout', g: 'handChest', to: 'tama' }],
      ['shiro', 'おーきーなーさーいーーっ！！', { f: 'angry', g: 'raise', to: 'tama', shake: 0.25, cam: 'wide', r: { mike: ['surprise', 'recoil'], kuro: 'surprise' } }],
      ['n', 'シロの大声に、綿毛がぶるぶるとふるえた。……そこへ、ひゅうっと、春風がふきぬけて——', { fx: 'gust', cam: 'up', dur: 5 }],
      ['n', 'ふわっ。', { fx: 'fluff:tama', lift: { tama: 7.4 }, cam: 'lift', dur: 4 }],
      ['tama', '……すぴー……。', { f: 'sleepy', move: { tama: [[-2, 14], [-6, 36]] }, speed: 2.4, look: { all: 'tama' }, cam: 'fly', dur: 5 }],
      ['mike', '飛んだーーっ！？', { f: 'surprise', g: 'recoil', cam: 'wide' }],
      ['shiro', 'う、うそでしょ！？　わ、わたしのせいじゃないわよね！？　風のせいよね！？', { f: 'shy', g: 'shrug' }],
      ['kuro', '……お前の声のせいだ。', { f: 'serious', to: 'shiro' }],
      ['shiro', 'うっ……。', { f: 'pout', g: 'lookDown' }],
      ['n', '綿毛は、眠る子猫をぶら下げたまま、ねむり川をこえて、林の奥へ流されていった。', { exit: 'tama', cam: 'look:far', dur: 6, look: { all: 'far' } }],
      ['mike', '追いかけなきゃ！　……でも、橋がこわれてる！', { f: 'worry', g: 'point' }],
      ['mike', 'あっ！　あっちの丘にも、大きなたんぽぽがあるよ！', { f: 'surprise', g: 'point', look: { all: 'hill' }, face: { mike: 'hill' } }],
      ['kuro', '……綿毛につかまって、川を越えるつもりか。', { f: 'serious', to: 'mike' }],
      ['mike', 'うん！　あの子にできたんだから、ぼくたちにもできるよ！', { f: 'joy', g: 'fist', face: { mike: 'kuro' } }],
      ['kuro', '……あいつは、寝ていただけだ。', { f: 'serious', r: { shiro: ['smile', 'laugh'] } }],
      ['shiro', '……待ってなさいよ。今度こそ、ちゃんと起こしてあげるんだから！', { f: 'serious', g: 'fist', look: { shiro: 'far' } }],
      ['n', '【目的】西の綿毛の丘で、大きなたんぽぽの綿毛につかまって（F）ねむり川を越え、林の奥へ。', { cam: 'wide', dur: 5 }],
    ] },
  c2_03g: { title: 'ねむり花の谷', bgm: 'village',
    stage: { zone: 'woods_valley', at: [9, 13], face: 0, host: 'tama',
      cast: { tama: { at: [0, 4], y: 1.15, stance: 'sleep', f: 'sleepy', face: [0, 0] } },
      points: { flower: [0, 1.4, 4], trail: [-2.5, 0, 9], north: [-9, 2, 30] },
      // 花のベッドをのぞきこむ
      shots: { bed: { pos: [3.2, 3.6, -1], look: [0, 1.2, 4] } } },
    lines: [
      ['n', '谷の花畑。人の背たけほどもある大きな花のまん中で、あの子猫が、すやすやと眠っていた。', { cam: 'bed', dur: 7, look: { all: 'tama' } }],
      ['mike', 'いたーっ！　……お花のベッドで寝てる！', { f: 'joy', g: 'point', move: { mike: [0, 1.8] }, speed: 1.8 }],
      ['shiro', '綿毛ごと、花の上に落ちたのね。……ふう、ケガはないみたい。', { f: 'worry', g: 'handChest', move: { shiro: [1.2, 1.9] } }],
      ['tama', '……すぴー……。', { f: 'sleepy', fx: 'zzz:tama', cam: 'bed', dur: 4 }],
      ['kuro', '……待て。この花……どこかで聞いた気がする。', { f: 'serious', g: 'think', look: { kuro: 'flower' } }],
      ['n', 'そのとき、大きな花が、ふくらむように息を吸いこみ——', { cam: 'bed', dur: 4, r: { all: 'surprise' } }],
      ['n', 'ふわぁ〜〜っ……と、桃色の粉をはき出した。', { fx: 'pollen:flower', cam: 'wide', dur: 5 }],
      ['mike', 'けほっ……なんだか……あまい……におい……ふあ……。', { f: 'sleepy', g: 'tilt' }],
      ['shiro', 'ちょっと、ミケ……こんなところで……寝たら……だめ……すぅ……。', { f: 'sleepy', stance: { mike: 'sleep' } }],
      ['kuro', '……思い出した。……ねむり花……だ……。……不覚……。', { f: 'sleepy', stance: { shiro: 'sleep' } }],
      ['n', '……すやすや。……すやすや。', { stance: { kuro: 'sleep' }, fx: ['zzz:all', 'darkness'], cam: 'wide', dur: 6 }],
      ['mike', '……むにゃ……さかな……もう、たべられない……。', { f: 'sleepy', fx: 'zzz:mike' }],
      ['shiro', '……むにゃ……わたしは……天才……ぜったい……しっぱい……しない……。', { f: 'sleepy', fx: 'zzz:shiro' }],
      ['kuro', '……………………すぅ。', { f: 'sleepy', fx: 'zzz:kuro' }],
      ['n', '……しばらくして。', { fx: 'dawn', exit: 'tama', cam: 'wide', dur: 4 }],
      ['kuro', '……っ！', { f: 'surprise', stance: { kuro: 'armsCrossed' }, cam: 'kuro', close: true }],
      ['mike', 'ふあ〜、よく寝た……って、あれ！？　あの子がいない！', { f: 'surprise', stance: { mike: 'idle', shiro: 'hipHand' }, g: 'recoil', look: { all: 'flower' } }],
      ['shiro', 'ええっ！？　さっきまで、ここで寝てたのに！', { f: 'surprise', g: 'surprise' }],
      ['n', '花の中には、綿毛がひとつ、引っかかっているだけだった。……その先に、小さな足あとが、ふらふらと続いている。', { cam: 'look:trail', dur: 6, look: { all: 'trail' } }],
      ['kuro', '……足あとが、右へ左へよろけている。……寝たまま、歩いているな。', { f: 'serious', g: 'point' }],
      ['mike', '寝ながら歩けるの！？　すごい！', { f: 'joy', g: 'hop' }],
      ['shiro', '感心してる場合じゃないでしょ！　ねぼけて谷に落ちたらどうするのよ！', { f: 'angry', g: 'point', to: 'mike' }],
      ['shiro', '……っていうか、あの子、ねむり花の粉をあびても平気だったのね……。', { f: 'worry', g: 'tilt' }],
      ['kuro', '……もともと寝ているやつに、眠り薬は効かない。', { f: 'serious', g: 'armsCrossed' }],
      ['mike', 'なるほど！', { f: 'joy', g: 'nod', r: { shiro: 'pout' } }],
      ['kuro', '……ねむり花は、ふくらんでから粉をはく。しぼんでいるあいだに、そばを駆け抜けろ。', { f: 'serious', g: 'explain', look: { all: 'north' } }],
      ['n', '【目的】ねむり花の粉をよけながら、ねぼけ歩きの足あとを追って、林の奥へ。', { cam: 'wide', dur: 5 }],
    ] },
  c2_03h: { title: 'でっかいどんぐり', cast: ['e:risu'], bgm: 'village',
    stage: { zone: 'woods_deep', at: [1, -19], face: 0, host: 'tama',
      cast: { tama: { at: [0, 5], stance: 'sleep', f: 'sleepy', face: [0, 0] },
        'e:risu': [{ at: [0.3, 3.9], face: [0, 5] }, { at: [-1.4, 5.7], face: [0, 5] }, { at: [1.4, 5.9], face: [0, 5] }] },
      points: { hollow: [0, 1.9, 8.2] }, wide: { pos: [3.6, 2.2, -1.6], look: [0, 1.5, 6.5] } },
    lines: [
      ['n', '林のいちばん奥。大きな木のうろの前で、リスたちが、まるいものを「よいしょ、よいしょ」と押していた。', { cam: 'wide', dur: 7, look: { all: 'tama' } }],
      ['e:risu', 'よいしょ！　よいしょ！　こんなにでっかいどんぐり、はじめて見た！', { move: { tama: [0, 6.2], 'e:risu': [0.3, 5.1], 'e:risu#1': [-1.4, 6.9], 'e:risu#2': [1.4, 7.1] }, speed: 0.8 }],
      ['mike', 'あーっ！　あの子だ！', { f: 'surprise', g: 'point', cam: 'mike', close: true }],
      ['e:risu', 'しかも、ほら！　ちゃんと、ぼうしまでついてる！'],
      ['kuro', '……それは、ぼうしじゃない。芽だ。', { f: 'serious', to: 'e:risu' }],
      ['shiro', 'ちょっと、あなたたち！　その子は、どんぐりじゃなくて猫よ！', { f: 'angry', g: 'point', move: { shiro: [1.2, 1.8] } }],
      ['e:risu', 'うそだ！　こんなにまるくて、ぽかぽかあったかいどんぐり、ほかにないもん！'],
      ['kuro', '……あったかいのは、生きているからだ。', { f: 'serious', g: 'armsCrossed' }],
      ['e:risu', '冬のたくわえが、ぜんぜん足りないの！　これは、うちのうろにしまうんだから！', { look: { all: 'hollow' } }],
      ['tama', '……むにゃ……ぼく……どんぐり……？', { f: 'sleepy', fx: 'zzz:tama', look: { all: 'tama' } }],
      ['e:risu', '……え？'],
      ['tama', '……どんぐりじゃ……ない……。……にゃあ……。', { f: 'sleepy', meow: { tama: 1 } }],
      ['e:risu', 'しゃ、しゃべったーーっ！？　どんぐりが、「にゃあ」って言ったーーっ！！', { shake: 0.2 }],
      ['n', 'リスたちは、しっぽをぼわっとふくらませて、大あわてで木の上へ逃げていった。……一匹だけ、逃げおくれて、ぷるぷるふるえている。', { exit: ['e:risu#1', 'e:risu#2'], cam: 'wide', dur: 6 }],
      ['mike', '……寝ごとで、追い払っちゃった。', { f: 'surprise', g: 'tilt' }],
      ['shiro', 'もう！　こっちは、綿毛で飛んだり、花の粉で寝ちゃったり、林じゅう走り回ったっていうのに！', { f: 'angry', g: 'fist' }],
      ['kuro', '……で、本人は、まだ寝ている。', { f: 'serious', look: { kuro: 'tama' } }],
      ['e:risu', '……ご、ごめんなさい。……どんぐりにしては、ぽかぽかあったかいなって、思ったの……。'],
      ['mike', 'いいよ、いいよ！　ぼくも、まるいもの見ると、おまんじゅうかなって思うもん！', { f: 'joy', g: 'nod' }],
      ['kuro', '……思わないだろ。', { f: 'serious', r: { shiro: ['smile', 'laugh'] } }],
      ['e:risu', '……冬のどんぐり、集めても集めても、足りないの。森の木が、ちっとも実をつけなくて……。'],
      ['kuro', '……（ここでも、木の実が……）', { f: 'serious', g: 'lookDown', cam: 'kuro', close: true }],
      ['n', '小さなリスは、おわびのしるしに、子猫の鼻先を、ふさふさのしっぽでそっとなでた。', { move: { 'e:risu': [0.5, 5.5] }, cam: 'look:tama', dur: 5 }],
      ['tama', '……ふ……ふぁ……', { f: 'sleepy' }],
      ['tama', '……くしゅんっ！', { f: 'surprise', fx: 'poof:tama', stance: { tama: 'idle' }, r: { all: 'surprise' } }],
      ['n', '子猫は、ぱちりと目を開けた。', { cam: 'tama', close: true }],
    ] },
  c2_03i: { title: 'タマ', cast: ['e:risu'], bgm: 'village',
    stage: { zone: 'woods_deep', at: [1, -19], face: 0, host: 'tama',
      cast: { tama: { at: [0, 4.8], face: [0, 0] }, 'e:risu': { at: [1.3, 5.6], face: 'tama' } } },
    lines: [
      ['tama', '……ん……あさ……？', { f: 'sleepy', g: 'lookUp' }],
      ['tama', '……だれ……？', { f: 'sleepy', g: 'tilt', to: 'mike' }],
      ['mike', 'ぼくはミケ！　こっちがクロと、シロ。きみは？', { f: 'smile', g: 'present' }],
      ['tama', '……タマ。……たぶん。', { f: 'sleepy', g: 'tilt' }],
      ['shiro', 'たぶんって何よ。どこから来たの？　おうちは？', { f: 'worry', g: 'tilt' }],
      ['tama', '……わかんない。……気がついたら、この林で寝てた。', { f: 'sleepy', g: 'shake' }],
      ['kuro', '……種族も、年も、わからないのか。', { f: 'serious' }],
      ['tama', '……うん。……でも、ふしぎな夢、みた。', { f: 'smile', g: 'lookUp' }],
      ['tama', '……おそらを、ふわふわとんで……おはなのベッドで、ねて……さいごは、どんぐりになってた。', { f: 'smile', g: 'tilt' }],
      ['mike', 'それ、ぜんぶ本当にあったことだよ！', { f: 'joy', g: 'point', r: { shiro: ['smile', 'laugh'], kuro: 'smile' } }],
      ['tama', '……？', { f: 'surprise', g: 'tilt' }],
      ['e:risu', 'ほんとだよ。……ごめんね、どんぐりにしちゃって。'],
      ['tama', '……ううん。……しっぽ、ふかふかだった。……ありがと。', { f: 'gentle', face: { tama: 'e:risu' } }],
      ['n', '小さなリスは、ぺこりと頭を下げると、どんぐりをひとつ置いて、木の上へ帰っていった。', { exit: 'e:risu', cam: 'wide', dur: 5 }],
      ['tama', '……みんな、ぼくを、さがしてくれてたの……？', { f: 'neutral', face: { tama: 'mike' }, to: 'mike' }],
      ['mike', 'うん！　林の入口から、ずーっと！', { f: 'joy', g: 'nod' }],
      ['tama', '……そっか。……えへへ。……ぼく、みんなと……あそびたい。', { f: 'smile', g: 'lookUp', r: { mike: 'gentle', shiro: 'shy' } }],
      { c: [
        ['いっしょに行こう、タマ！', [['tama', '……うん。……いく。', { f: 'smile', g: 'nod' }]], { f: 'joy', g: 'offer', bond: ['mike', 'tama', 6] }],
        ['……（そっと、頭をなでる）', [['tama', '……えへへ。……あったかい。', { f: 'gentle' }]], { f: 'gentle', g: 'reach', bond: ['mike', 'tama', 9] }],
      ] },
      ['shiro', 'しかたないわね。わたしが、ちゃーんと面倒を見てあげる！　……もう、どこにも飛んでいかないように！', { f: 'smug', g: 'handChest', to: 'tama' }],
      { bond: ['shiro', 'tama', 8] },
      ['kuro', '……迷子になるなよ。', { f: 'serious', g: 'turnAway', to: 'tama' }],
      ['tama', '……うん。……クロのしっぽ、つかんでる。', { f: 'smile', r: { kuro: 'shy', mike: ['joy', 'laugh'] } }],
      { give: 'tama' },
      ['n', '【目的】タマをつれて、来た道を戻ろう。まずは、ねむり花の谷の花畑まで。', { cam: 'wide', dur: 5 }],
    ] },
  c2_03j: { title: '帰り道', cast: ['e:noraInu', 'e:iwa'], bgm: 'village',
    stage: { zone: 'woods_valley', at: [8, 17], face: 180,
      cast: { 'e:noraInu': { at: [-4, 5], hidden: true, face: [0, 0] }, 'e:iwa': { at: [4, 5.5], hidden: true, face: [0, 0] } },
      points: { flower: [-1, 1.5, -8] } },
    lines: [
      ['n', '帰り道。ねむり花の谷の花畑を、四匹がならんで歩いていく。', { cam: 'wide', dur: 6 }],
      ['mike', 'ねえタマ、たんぽぽの上とか、お花の中とか、いつもあんなところで寝てるの？', { f: 'smile', g: 'tilt', to: 'tama' }],
      ['tama', '……うーん。……木のうろとか、おはなとか、くさのうえとか……。……いろんなところで、寝てた。', { f: 'sleepy', g: 'tilt' }],
      ['shiro', 'いろんなところで寝すぎよ！', { f: 'pout', g: 'point', to: 'tama' }],
      ['tama', '……ねむり花の粉……いいにおい……。', { f: 'sleepy', look: { tama: 'flower' }, face: { tama: 'flower' } }],
      ['shiro', 'だめ！　あの花に近づいたら、わたしたちまで寝ちゃうでしょ！', { f: 'angry', g: 'shake' }],
      ['kuro', '……止まれ。', { f: 'serious', stance: { kuro: 'ready' }, cam: 'kuro', close: true }],
      ['kuro', '……囲まれてる。', { f: 'serious', enter: ['e:noraInu', 'e:iwa'], look: { all: 'e:noraInu' }, cam: 'wide' }],
      ['e:noraInu', 'グルル……。いいにおいがすると思ったら、ちっこいのが四匹か。'],
      ['mike', 'タマ、うしろに下がってて！', { f: 'serious', g: 'fist', stance: { mike: 'ready' } }],
      ['tama', '……すぅ……。', { f: 'sleepy', stance: { tama: 'sleep' }, fx: 'zzz:tama' }],
      ['mike', '寝てるーーっ！？', { f: 'surprise', g: 'recoil', cam: 'wide' }],
      ['shiro', 'もう！　いいわ、タマのぶんまで、わたしががんばるんだから！', { f: 'angry', g: 'fist', stance: { shiro: 'ready' } }],
    ] },
  c2_03b: { title: '樹の声', bgm: 'village',
    stage: { zone: 'woods_valley', at: [8, 17], face: 180,
      cast: { tama: { at: [0.2, 2.4], face: [0, 0] } },
      points: { far: [105, 30, 218] } },
    lines: [
      ['n', '戦いが終わると、タマが大きなあくびをした。', { cam: 'look:tama', dur: 5 }],
      ['tama', '……ふあ……。……おわった？', { f: 'sleepy', g: 'tilt' }],
      ['shiro', '「おわった？」じゃないわよ！　あなた、戦いの間じゅう、ずーっと寝てたでしょ！', { f: 'angry', g: 'point', to: 'tama' }],
      ['tama', '……ゆめのなかで、おうえんしてた。', { f: 'smile', g: 'nod' }],
      ['mike', 'ゆめの中なら、しかたないね！', { f: 'joy', g: 'laugh' }],
      ['kuro', '……しかたなくない。', { f: 'serious', r: { shiro: ['smile', 'laugh'] } }],
      ['n', 'そのとき、タマが、ふと南の空を見上げた。', { look: { tama: 'far' }, face: { tama: 'far' }, cam: 'tama', close: true }],
      ['tama', '……あっちの、おおきな木……。……ないてる。', { f: 'sad', g: 'lookUp', look: { tama: 'far' } }],
      ['mike', 'おおきな木って……にゃんだーの樹？　あんなに遠いのに？', { f: 'surprise', g: 'tilt', look: { mike: 'far' } }],
      ['tama', '……わかんない。……でも、ずっと、さみしいって……いってる気がする。', { f: 'sad', g: 'shake' }],
      ['kuro', '……！', { f: 'surprise', cam: 'kuro', close: true, look: { kuro: 'tama' } }],
      ['kuro', '……（樹の声が、聞こえるのか……？）', { f: 'serious', look: { kuro: 'far' } }],
      ['shiro', 'ちょっと、何よ二匹とも。こわい顔しちゃって。', { f: 'worry', g: 'shrug' }],
      ['tama', '……ふあ……。……ねむい。', { f: 'sleepy', stance: { tama: 'sleep' } }],
      ['shiro', 'また寝るの！？　……もう、しかたないわね。宿場まで、わたしがおぶってあげる。', { f: 'worry', g: 'reach' }],
      ['kuro', '……俺が運ぶ。お前は、杖で手がふさがっている。', { f: 'serious', g: 'turnAway', move: { kuro: [0, 1.8] }, r: { mike: 'surprise', shiro: 'surprise' } }],
      ['mike', '……クロって、やっぱりやさしいよね。', { f: 'smile', to: 'shiro' }],
      ['shiro', '……ふーん。', { f: 'smug', g: 'hipHand' }],
      { bond: ['kuro', 'tama', 6] },
    ] },
  c2_03c: { title: '宿場の夜', bgm: 'sad', extra: ['chaya'],
    stage: { zone: 'road_rest', at: [-4, 8], face: 0, bg: 'night',
      cast: { mike: { at: [0, 0], stance: 'kneel' }, shiro: { at: [1.3, 0.3], stance: 'kneel' }, kuro: { at: [-2.8, 1] }, tama: { at: [-2.2, 0.4], stance: 'sleep' },
        chaya: { at: [-0.8, 4.5], hidden: true, face: 'mike' } },
      points: { sky: [0, 20, 30] } },
    lines: [
      ['n', 'その夜。一行は、宿場の茶屋「ねこじゃらし」で、夕ごはんを食べていた。', { cam: 'wide', dur: 7 }],
      ['chaya', 'はいよ、焼き魚定食、四つ！　眠ってた子を連れてきてくれたお礼だ。お代はいらないよ。', { enter: 'chaya', move: { chaya: [-0.3, 2.2] }, f: 'smile', g: 'give' }],
      ['mike', 'やったー！　いただきまーす！', { f: 'joy', g: 'cheer', hold: { mike: 'fish' } }],
      ['chaya', 'それにしても、今夜はしずかだねえ。前は、旅の猫たちが夜通し歌ったり笑ったりしてたもんだが……。', { f: 'sad', g: 'lookDown' }],
      ['chaya', '最近は、みんな、ひとりで飯を食って、ひとりで寝ちまう。……ま、年寄りのぐちさ。ごゆっくり。', { f: 'gentle', g: 'wave' }],
      ['mike', '……クロー！　そんな端っこにいないで、こっち来なよ！', { f: 'smile', g: 'wave', to: 'kuro', exit: 'chaya' }],
      ['kuro', '……ここでいい。', { f: 'serious', g: 'turnAway' }],
      ['mike', 'でも、タマ、クロのしっぽの上で寝てるよ？', { f: 'smile', g: 'point', look: { mike: 'tama' } }],
      ['kuro', '……っ。……動けないだけだ。', { f: 'shy', look: { kuro: 'tama' }, r: { mike: ['joy', 'laugh'] } }],
      ['n', 'シロだけは、さっきから杖をじっと見つめたまま、魚に手をつけていなかった。', { cam: 'shiro', close: true }],
      ['mike', 'シロ？　食べないの？　食べないなら、ぼくが——', { f: 'neutral', g: 'reach', to: 'shiro' }],
      ['shiro', 'た、食べるわよ！', { f: 'angry', g: 'fist' }],
      ['shiro', '……ねえ。あなたたち、失敗したこと、ある？', { f: 'worry', g: 'lookDown' }],
      ['mike', 'あるある！　毎日ある！　今日も、おばちゃんのお弁当、朝ごはんの前に全部食べちゃったし！', { f: 'joy', g: 'raise' }],
      ['shiro', '……そういうのじゃなくて。', { f: 'pout' }],
      ['kuro', '……ある。取り返しのつかない失敗が、な。', { f: 'sad', g: 'lookDown', cam: 'kuro', close: true, r: { mike: 'surprise', shiro: 'surprise' } }],
      ['shiro', '……そう。', { f: 'sad' }],
      ['mike', 'シロ……？', { f: 'worry', g: 'tilt', to: 'shiro' }],
      ['shiro', '……わたしはね、失敗しちゃいけないの。失敗したら……取り返しのつかないことになるから。', { f: 'sad', g: 'handChest' }],
      { c: [
        ['失敗したって、へっちゃらだよ！', [['shiro', '……あなたは、のんきでいいわね。', { f: 'pout', g: 'turnAway' }]], { f: 'joy', g: 'fist', bond: ['mike', 'shiro', 4] }],
        ['……（となりで、いっしょに星を見上げる）', [['shiro', '…………。……ありがと。', { f: 'shy', look: { shiro: 'sky' } }]], { f: 'gentle', look: { mike: 'sky' }, bond: ['mike', 'shiro', 7] }],
      ] },
      ['shiro', '……な、なんでもないわ！　天才は、明日も早いの。もう寝るわよ！', { f: 'smug', g: 'hipHand', stance: { shiro: 'idle' } }],
      ['n', '宿場の夜は、しずかにふけていった。', { cam: 'wide', dur: 6, look: { all: 'sky' } }],
    ] },
  c2_03d: { title: 'いなくなったシロ', bgm: 'village',
    stage: { zone: 'road_rest', at: [2, 6], face: 180, cast: { shiro: null } },
    lines: [
      ['n', '次の朝。', { cam: 'wide', dur: 4 }],
      ['mike', 'ふあー、よく寝た！　……あれ？　シロは？', { f: 'smile', g: 'lookUp' }],
      ['kuro', '……夜明け前に、ひとりで出ていった。', { f: 'serious', g: 'armsCrossed' }],
      ['mike', '見てたの！？　なんで止めないのさ！', { f: 'angry', g: 'fist', to: 'kuro' }],
      ['kuro', '……あいつが、ひとりで決めたことだ。', { f: 'serious', g: 'turnAway' }],
      ['mike', 'ひとりで決めたからって、ひとりにしていいわけじゃないよ！', { f: 'angry', g: 'shake' }],
      ['kuro', '…………。', { f: 'surprise', cam: 'kuro', close: true }],
      ['tama', '……シロ……みなみのほう……。……おさかなの、におい、する。', { f: 'sleepy', g: 'point', look: { tama: [0, 20] } }],
      ['mike', '魚のにおい……ってことは！', { f: 'surprise', g: 'surprise' }],
      ['kuro', '……また、失敗しているな。', { f: 'serious', g: 'nod' }],
      ['mike', '行こう、クロ、タマ！', { f: 'serious', g: 'fist' }],
      ['kuro', '……面倒だ。', { f: 'serious', g: 'shake', move: { kuro: [-0.6, 3] }, r: { mike: 'surprise' } }],
      ['mike', '……って、先に行ってるし！', { f: 'joy', g: 'point', to: 'kuro', r: { tama: 'smile' } }],
      ['n', '【目的】宿場の南、街道の風車の畑で、シロをさがそう。', { cam: 'wide', dur: 5 }],
    ] },
  c2_03e: { title: 'ひみつの特訓', cast: ['e:karasu', 'e:noraInu'], bgm: 'field',
    stage: { zone: 'road1', at: [9, -2], face: 90,
      cast: { shiro: { at: [0.3, 4.2], face: [0.3, 12] },
        'e:karasu': [{ at: [-2.6, 9], hidden: true }, { at: [2.4, 9.4], hidden: true }], 'e:noraInu': { at: [0, 10], hidden: true } },
      points: { mill: [-11.5, 5, 9] } },
    lines: [
      ['n', '風車のまわる畑のすみで、白い猫が、ひとりで杖をかまえていた。', { cam: 'look:shiro', dur: 6, look: { all: 'shiro' } }],
      ['shiro', '……ファイア！', { f: 'serious', g: 'raise', later: [1.2, { fx: ['spell:shiro', 'fishRain:shiro'] }] }],
      ['shiro', '……また魚。……もう一回。……ファイア！', { f: 'worry', g: 'raise', later: [1.2, { fx: ['spell:shiro', 'poof:shiro'] }] }],
      ['shiro', '……っ。……失敗しちゃ、だめなのに。……今度こそ、今度こそ……。', { f: 'cry', g: 'lookDown', cam: 'shiro', close: true }],
      ['mike', 'シロー！', { f: 'joy', g: 'wave', face: { shiro: 'mike' }, r: { shiro: ['surprise', 'recoil'] } }],
      ['shiro', 'な、なな、なんでいるのよ！？　……見てたの！？', { f: 'shy', g: 'recoil', to: 'mike' }],
      ['mike', '魚のにおいで、すぐわかったよ！', { f: 'joy', g: 'point' }],
      ['shiro', 'い、今のは失敗じゃないわ！　ええと、その……みんなの朝ごはんを用意する魔法よ！', { f: 'shy', g: 'shrug' }],
      ['kuro', '……ひとりで、こんなところで何をしている。', { f: 'serious', to: 'shiro' }],
      ['shiro', '……見ればわかるでしょ。特訓よ。……天才はね、人の見ていないところで努力するものなの。', { f: 'smug', g: 'hipHand' }],
      ['tama', '……おさかな……。', { f: 'sleepy', g: 'lookDown' }],
      ['n', 'そのとき、畑に散らばった魚をねらって、カラスとのら犬が集まってきた！', { enter: ['e:karasu', 'e:noraInu'], shake: 0.3, cam: 'wide', r: { all: 'surprise' } }],
      ['shiro', 'こ、来ないで！　……わたしひとりで、なんとかするんだから！', { f: 'worry', stance: { shiro: 'ready' }, face: { shiro: 'e:noraInu' } }],
      ['kuro', '……ひとりで、無茶をするな。', { f: 'angry', to: 'shiro', stance: { kuro: 'ready' }, move: { kuro: [0.9, 3] } }],
      ['mike', '……それ、クロが言う！？', { f: 'surprise', g: 'point', to: 'kuro', r: { tama: 'smile' } }],
      ['kuro', '……うるさい。来るぞ！', { f: 'shy', stance: { all: 'ready' }, cam: 'wide' }],
    ] },
  c2_03f: { title: '天才の約束', bgm: 'hope',
    stage: { zone: 'road1', at: [9, -2], face: 90, cast: { shiro: { at: [0.3, 2.6], face: 'mike' } }, points: { mill: [-11.5, 5, 9] } },
    lines: [
      ['shiro', '……はあ、はあ……。', { f: 'worry', g: 'lookDown' }],
      ['mike', 'やったね！　最後のシロの雷、ドカーンって！', { f: 'joy', g: 'cheer' }],
      ['shiro', '……その前の二回は、また魚だったわ。クロが前に立ってくれなかったら、今ごろ……。', { f: 'sad', g: 'lookDown' }],
      ['shiro', '……天才はね、失敗しちゃいけないの。……失敗したら、だれかが、いなくなっちゃうかもしれないから。', { f: 'sad', g: 'bothChest', cam: 'shiro', close: true, r: { kuro: 'surprise' } }],
      ['mike', '……じゃあさ、シロが失敗したら、ぼくたちがなんとかする！', { f: 'smile', g: 'fist' }],
      ['shiro', '……え？', { f: 'surprise' }],
      ['mike', 'ぼくが失敗したら、シロがなんとかして！　クロが失敗したら、タマが……えっと、寝てる！', { f: 'joy', g: 'present' }],
      ['tama', '……ねてる。', { f: 'sleepy', g: 'nod', r: { shiro: 'smile' } }],
      ['mike', 'ほら、四匹もいるんだもん。だれかが失敗しても、なんとかなるよ！　だって、仲間じゃん！', { f: 'joy', g: 'cheer' }],
      ['shiro', '……っ。', { f: 'shy', g: 'turnAway' }],
      ['shiro', '……ふ、ふん！　天才のわたしが、失敗なんかするわけないでしょ！', { f: 'shy', g: 'hipHand' }],
      ['shiro', '……でも。……もし、万が一、億が一、失敗したら……そのときは、よろしく。', { f: 'shy', g: 'lookDown', r: { mike: ['joy', 'hop'] } }],
      { bond: ['mike', 'shiro', 8] },
      { bond: ['kuro', 'shiro', 5] },
      ['mike', 'クロもだよ！　ひとりで前に出るの、なしだからね！', { f: 'pout', g: 'point', to: 'kuro' }],
      ['kuro', '……それは、約束できない。', { f: 'serious', g: 'turnAway' }],
      ['mike', 'えーっ！', { f: 'pout', g: 'pout' }],
      ['kuro', '……前に立つのは、俺の役目だ。……それだけだ。', { f: 'serious', cam: 'kuro', close: true }],
      ['n', '朝日の畑に、四匹ぶんの影が、並んでのびていた。', { cam: 'wide', dur: 7, look: { all: 'mill' } }],
      ['n', '【目的】宿場の北、なかよし関所を越えて、ニャハハ王国へ。', { cam: 'wide', dur: 5 }],
    ] },
  c2_04a: { title: 'なかよし関所', extra: ['gonji'], bgm: 'village',
    stage: { zone: 'sekisho', at: [0, 27], face: 0,
      cast: { gonji: { at: [0.4, 4.6], hidden: true, face: 'mike' } },
      points: { gate: [0, 3, 13], pads: [-15, 0.5, 10] } },
    lines: [
      ['n', 'ころころ岩の谷を抜けると、古い石の砦が、道をまるごとふさいでいた。……ニャハハ王国への関所だ。', { cam: 'look:gate', dur: 7, look: { all: 'gate' } }],
      ['mike', 'ここを抜ければ、ニャハハ王国だね！　……あれ？　門が閉まってる。', { f: 'surprise', g: 'tilt', move: { mike: [0, 1.8] } }],
      ['kuro', '……だれもいないな。', { f: 'serious', g: 'armsCrossed' }],
      ['gonji', '待たれい、待たれーい！', { enter: 'gonji', move: { gonji: [0.4, 3.4] }, speed: 1.4, r: { all: 'surprise' }, look: { all: 'gonji' } }],
      ['gonji', 'ここは、ニャハハ王国の「なかよし関所」。……わしは、関所番のゴンじゃ。みんなは、ゴン爺と呼ぶ。', { f: 'serious', g: 'nod' }],
      ['shiro', 'なかよし関所？　聞いたことないわね。', { f: 'smug', g: 'hipHand' }],
      ['gonji', 'むかしの王さまが作った関所でな。「一匹では通れぬ」というのが、決まりなのじゃ。', { f: 'serious', g: 'explain' }],
      ['gonji', '門には、それぞれからくりがあってのう。力、魔法、こもりうた……。それに、ふたつの足を合わせねば開かぬ門もある。', { f: 'serious', g: 'point', look: { all: 'gate' } }],
      ['kuro', '……からくりなど、壊して通ればいい。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['gonji', 'ばかもーん！　壊したら、直すのはわしじゃぞ！', { f: 'angry', g: 'fist', shake: 0.15, r: { kuro: 'surprise', mike: ['surprise', 'recoil'] }, stance: { kuro: 'armsCrossed' } }],
      ['mike', 'じゃあ、ぼくが全部やる！　ぼく、勇者だし！', { f: 'joy', g: 'fist' }],
      ['kuro', '……俺一人で十分だ。', { f: 'serious', g: 'turnAway' }],
      ['shiro', '天才のわたしにまかせなさい！　からくりなんて、魔法でちょちょいのちょいよ！', { f: 'smug', g: 'raise' }],
      ['tama', '……すぴー。', { f: 'sleepy', stance: { tama: 'sleep' }, fx: 'zzz:tama' }],
      ['gonji', '…………。……まとまりのない一行じゃのう。', { f: 'worry', g: 'shake', cam: 'gonji', close: true }],
      ['gonji', 'むかしはな、この関所も、にぎやかじゃった。旅の猫たちが声をかけあって、からくりを解いていったもんじゃ。', { f: 'gentle', g: 'lookUp' }],
      ['gonji', '……じゃが近ごろは、通る者もおらん。みんな、ひとりで旅をして、ひとりで引き返してしまう。', { f: 'sad', g: 'lookDown', stance: { tama: 'idle' } }],
      ['gonji', 'おまけに、北の大門の外には、はらぺこのイノシシが居ついてしもうてな……。わしひとりでは、もう、どうにもならん。', { f: 'sad', g: 'shake' }],
      ['mike', 'だいじょうぶ！　ぼくたち、四匹もいるもん！', { f: 'joy', g: 'cheer' }],
      ['gonji', '……ふん。口だけなら、なんとでも言えるわい。まずは、そこの「二匹の門」からじゃ。', { f: 'serious', g: 'point', look: { all: 'pads' } }],
      ['gonji', 'ふたつの踏み板を、同時に踏んでみせよ。……ひとりで、両方は踏めんぞ。', { f: 'smug', g: 'nod' }],
      ['n', '【目的】なかよし関所のからくりを解いて、北の大門へ。踏み板の上で F を押すと、仲間に「ここで待ってて」とたのめる。1〜4で先頭の子を交代すると、その子の得意なわざが使える。', { cam: 'wide', dur: 6 }],
    ] },
  c2_04: { title: 'まとまりのないパーティ', cast: ['e:inoshishi'], extra: ['gonji'], bgm: 'boss',
    stage: { zone: 'sekisho', at: [0, -28], face: 0,
      cast: { mike: { at: [0, 2] }, gonji: { at: [-3.2, -1.4], face: 'mike' }, 'e:inoshishi': { at: [0, 9], hidden: true } }, points: { gate: [0, 3, 12] } },
    lines: [
      ['n', '大門の鉄格子が上がると、北の広場のむこうに、ニャハハ王国の旗が見えた。', { cam: 'look:gate', dur: 6 }],
      ['gonji', '……見事じゃ。力、魔法、こもりうた、それに二匹の足。……よくぞ、からくりを解いたのう。', { f: 'gentle', g: 'nod', to: 'mike' }],
      ['mike', 'えへへ！　みんなのおかげ！', { f: 'joy', g: 'cheer' }],
      ['mike', 'よーし、ニャハハ王国まで、もうすぐだ！　みんな、はやくはやくー！', { f: 'joy', g: 'wave', move: { mike: [0, 4] } }],
      ['shiro', 'ミケ、勝手に先に行かないで！', { f: 'angry', g: 'point' }],
      ['kuro', '……タマが寝た。', { f: 'serious', stance: { tama: 'sleep' }, look: { kuro: 'tama' } }],
      ['shiro', 'またぁ！？', { f: 'surprise', g: 'recoil' }],
      ['n', 'ドドドドド……！　地面が揺れ、大きなイノシシが、北の道から突っこんできた！', { enter: 'e:inoshishi', shake: 0.6, sfx: 'slam', cam: 'wide', r: { all: ['surprise', 'recoil'] }, stance: { tama: 'idle' } }],
      ['e:inoshishi', 'ブヒィィ！　ここはおれさまの食べ場だ！　食べ物を置いていけ！'],
      ['gonji', 'で、出おったな！　……お前たち、下がっておれ！　ここは関所番のわしが——', { f: 'angry', g: 'fist', stance: { gonji: 'ready' } }],
      ['mike', 'ぼくのお弁当はあげないよ！', { f: 'angry', g: 'fist' }],
      ['kuro', '……俺がやる。下がってろ。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['shiro', '待って、ここはわたしの魔法で——', { f: 'smug', g: 'point' }],
      ['tama', '……すぴー。', { f: 'sleepy' }],
      ['gonji', '……わしの話を聞けーい！', { f: 'angry', g: 'shake', r: { mike: 'surprise' } }],
      ['mike', '……ぼくたち、ぜんぜんまとまってないね！？', { f: 'surprise', g: 'shrug', cam: 'wide' }],
      ['kuro', '……来るぞ！', { f: 'angry', stance: { all: 'ready' } }],
    ] },
  c2_05: { title: 'はじめての連携', cast: ['e:inoshishi'], extra: ['gonji'], bgm: 'hope',
    stage: { zone: 'sekisho', at: [0, -28], face: 0, cast: { gonji: { at: [-3.2, -1.4], face: 'mike' }, 'e:inoshishi': { at: [0, 9] } } },
    lines: [
      ['e:inoshishi', '……ブヒ。冬ごもりの食べ物が、どこにも見つからなかったんだ……。'],
      ['gonji', '……そうか。お前も、ひとりぼっちで、腹をすかせておったのか。', { f: 'sad', g: 'lookDown', move: { gonji: [-1.6, 3.2] } }],
      ['gonji', '番小屋に、干したどんぐりが少しある。……持っていけ。もう門に体当たりするでないぞ。', { f: 'gentle', g: 'give' }],
      ['n', 'イノシシは、なんどもふり返りながら、森へ帰っていった。', { exit: 'e:inoshishi', cam: 'wide' }],
      ['mike', '……みんな、おなかすいてるんだね。', { f: 'sad', g: 'lookDown' }],
      ['kuro', '……木の実が実らない。樹が弱っているせいだ。', { f: 'serious' }],
      ['shiro', '……でも、さっきの戦い、最後はちょっとだけ息が合ってたんじゃない？', { f: 'smile', g: 'tilt' }],
      ['mike', 'うん！　クロが守って、シロが魔法で、タマが……えっと……寝てた！', { f: 'joy', g: 'cheer' }],
      ['tama', '……がんばって、寝てた。', { f: 'smile', g: 'nod' }],
      ['kuro', '……ふっ。', { f: 'smile', cam: 'kuro', close: true, r: { all: 'surprise' } }],
      ['mike', 'あっ！　クロが笑った！', { f: 'joy', g: 'point', to: 'kuro' }],
      ['kuro', '……笑ってない。', { f: 'shy', g: 'turnAway', r: { shiro: ['joy', 'laugh'], tama: 'smile' } }],
      ['gonji', 'ほっほっほ。……関所のからくりはな、仲間のわざを知るためのものなんじゃ。', { f: 'smile', g: 'laugh', face: { gonji: 'mike' } }],
      ['gonji', 'じゃが、ほんとうの試しは、最後にお前たちがやったことよ。……仲間を信じて、背中をあずけることじゃ。', { f: 'gentle', g: 'handChest', cam: 'gonji', close: true }],
      ['gonji', 'ほれ、通行手形じゃ。……なかよし関所、合格じゃ！', { f: 'joy', g: 'give', to: 'mike', r: { mike: ['joy', 'cheer'] } }],
      { bond: ['all', null, 8] },
      ['n', 'まとまりのないパーティ。でも、旅を続けるうちに、少しずつ協力できるようになっていく。', { cam: 'wide', dur: 7 }],
      ['gonji', 'この先がニャハハ王国じゃ。……もとは「笑いの国」と呼ばれておったが、近ごろは、どうも様子がおかしいと聞く。気をつけてな。', { f: 'worry', g: 'point', look: { all: [0, 15] } }],
      ['shiro', '「笑いの国」……。きっと、楽しいところよ！　……たぶん。', { f: 'smile', g: 'point', look: { all: [0, 15] } }],
    ] },

  // ================= 第三章　笑わない街 =================
  c3_01: { title: '笑わない街', bgm: 'sad',
    stage: { zone: 'nyahaha', at: [0, 22], face: 0, cast: { shimin_a: { at: [-1.2, 2.8], face: 'mike', f: 'sad' }, shimin_b: { at: [1.6, 3.4], face: 'mike', f: 'sad' } } },
    lines: [
      ['n', 'ニャハハ王国。……名前とは正反対に、街はしんと静まりかえっていた。', { cam: 'wide', dur: 7 }],
      ['mike', '……あれ？　「笑いの国」なんだよね？', { f: 'worry', g: 'tilt' }],
      ['shimin_a', '……いらっしゃい。', { f: 'sad' }],
      ['mike', 'こんにちは！　ねえねえ、面白い話してあげる！　この前、魚だと思ってかじったら、クロのしっぽだった！', { f: 'joy', g: 'cheer', to: 'shimin_a' }],
      ['shimin_a', '……そう。', { f: 'sad', g: 'lookDown' }],
      ['kuro', '……それは本当の話だ。痛かった。', { f: 'angry', g: 'shake' }],
      ['shiro', 'こ、これは重症ね……。', { f: 'worry', g: 'shrug' }],
      ['shimin_b', '……この国の宝、「笑いの実」が盗まれてから、誰も笑えなくなったんだ。……王さまに会ってみるといい。', { f: 'sad', g: 'point', look: { all: [-10, 3, 40] } }],
      ['n', '【目的】町の北、ニャハハ城の中庭へ。', { cam: 'wide', dur: 5 }],
    ] },
  c3_02: { title: 'ニャハハ王', bgm: 'sad', extra: ['daijin'],
    stage: { zone: 'castle_in', at: [0, -6], face: 0, host: 'nyahaha_ou', cast: { nyahaha_ou: { at: [0, 3.4], face: 'mike' }, daijin: { at: [-2, 3], face: 'mike' } } },
    lines: [
      ['nyahaha_ou', '……よく来たな、旅の者たち。わしが、ニャハハ王じゃ。', { f: 'sad', g: 'nod' }],
      ['nyahaha_ou', 'この国では昔から、にゃんだーの樹に実る「笑いの実」を大切にしてきた。祭りのたびに実を分け合って、国じゅうで笑うのじゃ。', { f: 'sad', g: 'explain' }],
      ['nyahaha_ou', '……それを何百年も続けるうちに、わしらは、実がなければ笑えぬ国になっておった。……じゃが、樹が弱ってから、実はほとんど実らなくなった。', { f: 'sad', g: 'lookDown' }],
      ['nyahaha_ou', '残った最後の一つを、国の宝として守っておったのじゃが……魔王軍に、盗まれてしもうた。', { f: 'cry', g: 'lookDown' }],
      ['daijin', 'それからというもの、国じゅうの猫が、笑い方ごと忘れてしまいました……。', { f: 'worry', g: 'shake' }],
      ['kuro', '……魔王軍。', { f: 'serious', cam: 'kuro', close: true }],
      ['shiro', 'クロ？　どうしたの？', { f: 'worry', to: 'kuro' }],
      ['kuro', '……なんでもない。', { f: 'serious', g: 'turnAway' }],
      ['shiro', '……ほかの土地でも、笑い声は減ってるって聞くけど……ここまでなのは、この国だけね。', { f: 'worry', g: 'think', to: 'nyahaha_ou' }],
      ['nyahaha_ou', 'さらに困ったことに……笑顔の塔に、泣いてばかりのピエロが住みついてしもうた。笑い声のような、泣き声のような声が響いて、民が怖がっておる。', { f: 'worry', g: 'point', look: { all: [20, 6, 30] } }],
      ['mike', '困ってるなら、助ければいいじゃん！　ぼくたちが、見てくる！', { f: 'serious', g: 'fist' }],
      ['nyahaha_ou', '……頼む。あのピエロは、昔はこの国いちばんの人気者じゃったのじゃ。', { f: 'sad', g: 'bow' }],
      ['n', '【目的】城下町の北東、笑顔の塔へ。', { cam: 'wide', dur: 5 }],
    ] },
  c3_03: { title: '笑顔の塔', cast: ['e:ghost'], bgm: 'dark',
    stage: { zone: 'tower', at: [0, 10], face: 0, cast: { 'e:ghost': [{ at: [-2.4, 5], hidden: true }, { at: [2.2, 5.6], hidden: true }] }, points: { top: [0, 9, 18] } },
    lines: [
      ['n', '笑顔の塔。色あせたポスター、しぼんだ風船。……舞台のほうから、笑い声のような声が聞こえる。', { cam: 'look:top', dur: 7 }],
      ['e:ghost', 'ゲラ……ゲラゲラ……', { enter: 'e:ghost', r: { all: 'surprise' } }],
      ['shiro', 'お、おばけ！？　べ、別に怖くないけど！', { f: 'worry', g: 'recoil', move: { shiro: [-0.6, -0.6] } }],
      ['kuro', '……笑ってるのに、楽しそうじゃない。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['mike', 'なんか……さみしそう。', { f: 'sad' }],
      ['tama', '……ないてる、みたい。', { f: 'sad', g: 'tilt' }],
    ] },
  c3_03a: { title: 'むすっと幕', bgm: 'dark',
    stage: { zone: 'tower', at: [0, -10], face: 0, points: { curtain: [0, 2.5, 7], maze: [-30, 1, -10], balloon: [32, 1, -7], ticket: [-27, 1, 19] } },
    lines: [
      ['n', '大ロビーの奥。階段の間へ続く通路を、分厚い幕がふさいでいた。幕には、大きな「むすっ」とした顔が描いてある。', { cam: 'look:curtain', dur: 7, look: { all: 'curtain' } }],
      ['mike', 'うわあ、すっごい不機嫌そう……。', { f: 'surprise', g: 'recoil' }],
      ['shiro', 'ちょっと！　通しなさいよ！', { f: 'angry', g: 'point' }],
      ['n', '……幕は、ぴくりとも動かない。', { cam: 'look:curtain', dur: 4 }],
      ['kuro', '……押しても引いても、だめだな。', { f: 'serious', g: 'think' }],
      ['tama', '……このこ……わらったら、あくかも。', { f: 'sleepy', g: 'tilt' }],
      ['mike', '笑ったら？', { f: 'neutral', g: 'tilt', to: 'tama' }],
      ['tama', '……あっちと、こっちと、そっちに……わらいぶくろ、あった。', { f: 'sleepy', g: 'point', look: { all: 'maze' } }],
      ['shiro', '笑い袋？　押すと「ワハハ」って笑う、あのおもちゃ？', { f: 'neutral', g: 'think', look: { shiro: 'balloon' } }],
      ['kuro', '……笑い声が三つそろえば、こいつもつられて笑う……のかもしれん。', { f: 'serious', g: 'nod', look: { kuro: 'ticket' } }],
      ['n', '（1Fのあちこちにある「笑い袋」を三つ笑わせると、むすっと幕が上がる。袋の前で F。ミニマップに黄色の点で出る）', { cam: 'wide', dur: 7 }],
    ] },
  c3_03c: { title: 'ピエロの楽屋', bgm: 'sad',
    stage: { zone: 'tower_2f', at: [0, 3], face: 180, points: { desk: [0, 1.2, 11], boxW: [28, 1.5, -3], boxE: [-28, 1.5, -3] } },
    lines: [
      ['n', '二階のまん中の、ひときわ大きな楽屋。鏡台の上に、ぼろぼろのノートが一冊、置きっぱなしになっていた。', { cam: 'look:desk', dur: 7, look: { all: 'desk' } }],
      ['shiro', '……「ピエロのネタ帳」ですって。', { f: 'neutral', g: 'think' }],
      ['mike', '読んでみよう！　えっと……「ふとんが、ふっとんだ」。', { f: 'joy' }],
      ['n', '…………。', { dur: 3 }],
      ['mike', '……「ねこが、ねころんだ」。', { f: 'smile', g: 'hop' }],
      ['kuro', '……俺たちのことか。', { f: 'serious', to: 'mike' }],
      ['tama', '……ねころぶの……すき……。', { f: 'sleepy', g: 'tilt' }],
      ['shiro', 'どれも、上から線で消してあるわ。……「だれも、わらわなかった」って。', { f: 'sad', g: 'lookDown' }],
      ['mike', '……ピエロさん、ひとりで、ずっと練習してたんだね。', { f: 'sad' }],
      ['kuro', '……笑わせる側が笑えないんじゃ、笑いは生まれない。', { f: 'serious', g: 'lookDown' }],
      ['n', 'そのとき——廊下のほうから「ばあっ！」と大きな音が響いた。', { shake: 0.3, r: { all: 'surprise' }, look: { all: 'boxW' } }],
      ['shiro', 'な、なに今の！？　べ、別にびっくりしてないけど！', { f: 'worry', g: 'recoil' }],
      ['kuro', '……廊下のびっくり箱だ。上へ行く道を、ふさいでいる。', { f: 'serious', g: 'point', look: { kuro: 'boxE' } }],
      ['n', '（東か西の廊下をふさぐ巨大びっくり箱を、攻撃で開けよう。……床のブーブークッションにも、気をつけて）', { cam: 'wide', dur: 6 }],
    ] },
  c3_03b: { title: '空中ブランコの間', cast: ['e:mimic', 'e:ghost'], bgm: 'dark',
    stage: { zone: 'tower_3f', at: [0, 6], face: 0, cast: { 'e:mimic': { at: [-2, 5.2], hidden: true }, 'e:ghost': { at: [2.2, 5.8], hidden: true } }, points: { trapeze: [0, 4, 13] } },
    lines: [
      ['n', '三階は、底の見えない吹き抜けだった。だれも乗っていないのに、空中ブランコだけが、ゆらゆらとゆれている。', { cam: 'look:trapeze', dur: 7, look: { all: 'trapeze' } }],
      ['shiro', 'だ、だれも乗ってないのに……！？', { f: 'worry', g: 'recoil' }],
      ['mike', '……昔は、ここでショーをやってたのかな。', { f: 'sad', g: 'lookUp' }],
      ['tama', '……ブランコ……だれかを、まってるみたい。', { f: 'sad', g: 'tilt' }],
      ['e:mimic', 'クスクス……お客さん？　ひさしぶりの、お客さんだ……！', { enter: ['e:mimic', 'e:ghost'], shake: 0.3, r: { all: 'surprise' } }],
      ['e:ghost', 'ゲラゲラ……ショーを、見ていってよ……！'],
      ['kuro', '……来るぞ。', { f: 'serious', stance: { all: 'ready' }, cam: 'wide' }],
    ] },
  c3_03d: { title: 'ぼよよん', bgm: 'village',
    stage: { zone: 'tower_3f', at: [0, 6], face: 0, points: { tramp: [0, 0.3, 12], plat: [0, 3, 24], balcony: [0, 6, 40], west: [-19, 1, 7] } },
    lines: [
      ['n', 'ミミックたちを追い払うと、吹き抜けの向こう、北の高い桟敷に、上へ続く階段が見えた。', { cam: 'look:balcony', dur: 7, look: { all: 'balcony' } }],
      ['mike', 'あんなに高いところ、どうやって行くの！？', { f: 'surprise', g: 'lookUp' }],
      ['tama', '……これ。', { f: 'sleepy', g: 'point', look: { all: 'tramp' } }],
      ['n', '舞台のはしに、サーカスのトランポリンが置いてある。', { cam: 'look:tramp', dur: 5 }],
      ['shiro', 'じょ、冗談でしょ！？　あんなのではねたら、落っこちちゃうじゃない！', { f: 'worry', g: 'recoil' }],
      ['kuro', '……ブランコの足場を中継ぎにすれば、届く。', { f: 'serious', g: 'think', look: { kuro: 'plat' } }],
      ['tama', '……ぼよよーん……たのしそう。', { f: 'joy', g: 'hop' }],
      ['mike', 'よーし、みんなで跳ぼう！　シロ、手つないであげようか？', { f: 'joy', g: 'cheer', to: 'shiro' }],
      ['shiro', 'い、いらないわよっ！　……でも、先に跳んでよね。', { f: 'angry', g: 'turnAway' }],
      ['n', '（トランポリンに乗ると、ぼよよーんと跳ぶ。舞台 → ブランコの足場 → 北の桟敷へ。東西の小島にも跳べる）', { cam: 'wide', dur: 7, look: { all: 'west' } }],
    ] },
  c3_04: { title: '泣き虫ピエロ', cast: ['e:piero'], bgm: 'boss',
    stage: { zone: 'tower_top', at: [0, -22], face: 0, cast: { 'e:piero': { at: [0, 4.2] } }, wide: { pos: [-3, 1.8, -2], look: [0, 1.2, 4] } },
    lines: [
      ['n', '塔の最上階は、大きなサーカスの舞台だった。……客席には、板に描いたお客さんが、ずらりと並んでいるだけだった。', { cam: 'wide', dur: 7 }],
      ['e:piero', '……いらっしゃい、いらっしゃい！　ピエロのショーの始まりだよ！'],
      ['e:piero', 'ほら、笑って！　笑ってよ！　……どうして、誰も笑ってくれないの……？'],
      ['mike', 'ピエロさん……。', { f: 'sad' }],
      ['e:piero', '笑ってくれないなら……無理やりにでも、笑わせてあげる！　わらいガスだよ！！', { shake: 0.4 }],
      ['shiro', 'むちゃくちゃよ！', { f: 'angry', stance: { shiro: 'ready' } }],
      ['kuro', '……止めるぞ。', { f: 'serious', stance: { all: 'ready' } }],
    ] },
  c3_05: { title: '「笑いたかったんだ」', bgm: 'sad',
    stage: { zone: 'tower_top', at: [0, -22], face: 0, host: 'piero_npc', cast: { piero_npc: { at: [0, 3.2], stance: 'kneel', face: 'mike', f: 'cry' } } },
    lines: [
      ['piero_npc', '……どうして……ぼくのショーじゃ、誰も笑ってくれないんだ……。', { f: 'cry', g: 'lookDown' }],
      ['piero_npc', '笑いの実がなくなって、みんなの笑顔が消えて……ぼくは、みんなを笑わせるのが仕事なのに……。', { f: 'cry', g: 'bothChest' }],
      ['piero_npc', '僕だって……笑いたかったんだ。', { f: 'cry', cam: 'piero_npc', close: true, r: { all: 'sad' } }],
      ['tama', '……ピエロさん……ないてる……。', { f: 'sad', move: { tama: [0.5, 2.4] } }],
      ['tama', '……いいこ、いいこ。', { f: 'gentle', g: 'reach' }],
      ['shiro', 'タマ……。', { f: 'worry' }],
      ['n', '……タマは、ピエロのひざに頭をのせると、そのまま、すやすやと眠ってしまった。', { stance: { tama: 'sleep' }, cam: 'wide', dur: 6 }],
      ['piero_npc', '……え、ええ？　ね、寝ちゃった……？', { f: 'surprise', g: 'surprise' }],
      ['mike', 'ぷっ……あははは！', { f: 'joy', g: 'laugh' }],
      ['shiro', 'ふふっ……もう、タマったら！', { f: 'joy', g: 'laugh' }],
      ['kuro', '……くっ。', { f: 'smile', g: 'turnAway' }],
      ['piero_npc', '……ふふ……あはははは！', { f: 'joy', g: 'laugh', fx: 'laugh' }],
      ['n', '塔に、ひさしぶりの笑い声が響いた。', { cam: 'wide', dur: 6, bgm: 'hope' }],
      ['piero_npc', '……ありがとう。笑うって、こういうことだったね。', { f: 'smile', g: 'handChest' }],
      ['mike', '戦うだけじゃなくて、ちゃんと話を聞くのも、大事なんだね。', { f: 'gentle', g: 'nod' }],
      { flag: 'talk', say: '戦闘中に「はなす」ができるようになった！（Rキー）　敵に話しかけると、気持ちを聞いて、なごませられる。' },
      ['piero_npc', 'そうだ……笑いの実を盗んだ魔王軍の兵が、この塔を通っていったよ。「黒い谷を抜けて、北の魔王領へ」って……。', { f: 'serious', g: 'point' }],
      ['kuro', '……黒い谷。', { f: 'serious', cam: 'kuro', close: true }],
    ] },
  c3_06: { title: '笑顔のかけら', bgm: 'hope', extra: ['shimin_a', 'shimin_b'],
    stage: { zone: 'nyahaha', at: [0, 8], face: 0, host: 'nyahaha_ou',
      cast: { nyahaha_ou: { at: [0, 3], face: 'mike' }, shimin_a: { at: [-2.6, 3.6], face: 'mike', f: 'smile' }, shimin_b: { at: [2.6, 3.8], face: 'mike', f: 'smile' } } },
    lines: [
      ['nyahaha_ou', 'おお……民が、笑っておる……！', { f: 'joy', g: 'cheer', r: { shimin_a: ['joy', 'laugh'] } }],
      ['nyahaha_ou', '笑いの実はまだ戻らぬが……笑いは、実だけから生まれるものではなかったのじゃな。', { f: 'gentle', g: 'handChest' }],
      ['shiro', '……でも、樹が弱ったままだと、この国の笑いは、またしぼんでしまうわ。', { f: 'worry' }],
      ['kuro', '……この国だけの問題じゃない。世界中で、同じことが起きている。', { f: 'serious' }],
      ['mike', 'クロ？', { f: 'neutral', g: 'tilt', to: 'kuro' }],
      ['kuro', '……昔、俺の仲間たちが、この異変を調べていた。……その記録が、俺の故郷、くろねこ谷に残っているはずだ。', { f: 'sad', g: 'lookDown' }],
      ['mike', 'クロの故郷！？　行ってみたい！', { f: 'joy', g: 'hop' }],
      ['kuro', '……面倒だ。……でも、行くしかない。', { f: 'serious', g: 'nod' }],
      ['n', '【目的】城下町の東から、くろねこ谷の集落へ。', { cam: 'wide', dur: 5 }],
    ] },

  // ================= 第四章　黒猫の過去 =================
  c4_01: { title: 'くろねこ谷', bgm: 'sad',
    stage: { zone: 'valley_village', at: [-12, 1], face: 90, host: 'kurone', cast: { kurone: { at: [0, 2.8], face: 'kuro' } } },
    lines: [
      ['n', 'くろねこ谷の奥の、小さな集落。夕焼けの色が、いつまでも消えない谷。', { cam: 'wide', dur: 7 }],
      ['kurone', '……クロ。クロじゃないか。', { f: 'surprise', g: 'surprise', to: 'kuro' }],
      ['kuro', '……ただいま、クロネ婆。', { f: 'sad', g: 'nod' }],
      ['kurone', 'おかえり。……そっちの子たちは？', { f: 'gentle', g: 'tilt' }],
      ['mike', 'ぼくたち、クロの仲間！', { f: 'joy', g: 'cheer' }],
      ['kurone', '……仲間、かい。', { f: 'gentle', look: { kurone: 'kuro' } }],
      ['kuro', '……。', { f: 'serious', g: 'turnAway' }],
      ['kurone', '……あの子たちの墓は、谷の丘の上だよ。会っておいき。', { f: 'gentle', g: 'point', look: { all: [-12, 4, -18] } }],
      ['n', '【目的】谷の丘の上の墓標へ。', { cam: 'wide', dur: 5 }],
    ] },
  c4_02: { title: '墓標', cast: ['e:kageneko'], bgm: 'sad',
    stage: { zone: 'valley', at: [-16, -7.5], face: 0,
      cast: { kuro: { at: [0, 1.4] }, mike: { at: [-1.2, 0.2] }, 'e:kageneko': [{ at: [-3.4, 5], hidden: true }, { at: [3.2, 5.4], hidden: true }] },
      points: { graves: [0, 1, 8.5] } },
    lines: [
      ['n', '丘の上に、三つの墓と、名前のない石がひとつ。', { cam: 'look:graves', dur: 7, look: { all: 'graves' } }],
      ['kuro', '……ハヤテ、リン、ゴロウ。……俺の、昔の仲間だ。', { f: 'sad', g: 'lookDown', look: { kuro: 'graves' } }],
      ['kuro', '「影の四剣」。四人で、世界じゅうで起きている異変を調べていた。……異変の陰に魔王軍がいると思って、あとを追った。そして、闇の中で襲われて……俺以外、全員いなくなった。', { f: 'sad', g: 'bothChest' }],
      ['shiro', '……四つ目の石は？', { f: 'worry' }],
      ['kuro', '……俺の分だ。……あのとき、俺も一緒にいなくなるべきだった。', { f: 'pained', cam: 'kuro', close: true, r: { all: 'surprise' } }],
      ['mike', 'そんなの、ダメだよ！', { f: 'angry', g: 'fist', to: 'kuro' }],
      ['kuro', '……だから、もう仲間は作らない。……失うのは、もうたくさんだ。', { f: 'sad', g: 'turnAway' }],
      ['mike', '……ぼくも、ちっちゃいころに、お父さんとお母さんがいなくなった。', { f: 'sad', g: 'lookDown', r: { kuro: 'surprise' } }],
      ['mike', 'だから、失うのがこわいの、ちょっとわかるよ。', { f: 'sad', g: 'handChest' }],
      ['mike', '……でも、ぼくたち、もう仲間じゃん。', { f: 'sad', g: 'offer' }],
      ['kuro', '…………。', { f: 'serious', g: 'lookDown' }],
      ['n', 'そのとき、墓のまわりに、黒い影がわき上がった。', { fx: 'shadow:graves', enter: 'e:kageneko', shake: 0.3, cam: 'wide' }],
      ['kuro', '……影ども。ここを荒らすな！', { f: 'angry', stance: { all: 'ready' }, face: { kuro: 'e:kageneko' } }],
    ] },
  c4_02b: { title: '最後の夜の記録', bgm: 'sad',
    stage: { zone: 'valley', at: [-16, -7.5], face: 0, cast: { kuro: { at: [0, 1.4] }, mike: { at: [-1.2, 0.2] } }, points: { graves: [0, 1, 8.5], camp: [34, 1, 1.5] } },
    lines: [
      ['n', '影は、墓標のまわりから、すうっと消えていった。', { cam: 'look:graves', dur: 6, look: { all: 'graves' } }],
      ['kuro', '……今の影。……俺たちが追っていた「異変」と、同じにおいがした。', { f: 'serious', look: { kuro: 'graves' } }],
      ['mike', 'クロの仲間が、何を調べてたのか……わかればいいのに。', { f: 'worry', to: 'kuro' }],
      ['kuro', '……記録だ。', { f: 'surprise', g: 'surprise', r: { all: 'surprise' } }],
      ['kuro', '……ハヤテは、毎晩、野営のテントで調査の記録をつけていた。……最後の夜のテントが、まだ川のほとりに残っているかもしれない。', { f: 'serious', g: 'point', look: { all: 'camp' } }],
      ['tama', '……さがしに、いこ。', { f: 'smile', g: 'nod', to: 'kuro' }],
      ['n', '【目的】谷の北東、川のほとりの野営あとで、影の四剣の記録をさがす。', { cam: 'wide', dur: 5 }],
    ] },
  c4_02c: { title: '主のいないテント', bgm: 'sad',
    stage: { zone: 'valley', at: [20.5, -7], face: -90, points: { tent: [2, 1.1, 2.5] } },
    lines: [
      ['n', '谷の北東、川のほとりの野営あと。雨ざらしの古いテントが、ぽつんと残っていた。', { cam: 'look:tent', dur: 7, look: { all: 'tent' } }],
      ['kuro', '……ここで、最後の夜を過ごした。……あいつらと。', { f: 'sad', g: 'lookDown', look: { kuro: 'tent' } }],
      ['n', 'テントの中には、色あせた毛布と、四つの荷物。……けれど、記録の手帳は、どこにもなかった。', { cam: 'wide', dur: 6 }],
      ['shiro', '……ないわね。どこか、ほかの場所にしまったのかしら。', { f: 'worry', g: 'think', to: 'kuro' }],
      ['kuro', '……いや。……思い出した。あの朝、ハヤテは手帳を懐に入れて、テントを出た。', { f: 'serious', g: 'lookDown', cam: 'kuro', close: true }],
      ['mike', 'じゃあ、手帳は……。', { f: 'worry', to: 'kuro' }],
      ['kuro', '……黒影洞窟。……俺たちが、全滅した場所だ。', { f: 'serious' }],
      ['tama', '……どうくつ、いくの？', { f: 'worry', to: 'kuro' }],
      ['kuro', '……ああ。あいつらの記録を、あそこに置いたままにはしておけない。', { f: 'serious', g: 'nod', r: { mike: 'serious' } }],
      ['n', '【目的】谷の北、黒影洞窟へ。', { cam: 'wide', dur: 5 }],
    ] },
  c4_03: { title: '黒影洞窟', cast: ['e:kageneko', 'e:yoroi'], bgm: 'dark',
    stage: { zone: 'cave', at: [0, 39], face: 0, cast: { 'e:kageneko': { at: [-2.4, 4.6], hidden: true }, 'e:yoroi': { at: [2, 5.6], hidden: true } }, points: { deep: [0, 2, 16] } },
    lines: [
      ['n', 'ハヤテが手帳を持って入った、最後の場所——黒影洞窟。ひんやりとした闇が、奥へ奥へと続いている。', { cam: 'wide', dur: 7 }],
      ['kuro', '……あの日と、同じにおいがする。', { f: 'serious', g: 'lookDown' }],
      ['hayate', '（声）……クロ。……こっちだ。', { look: { all: 'deep' } }],
      ['kuro', '……ハヤテ！？', { f: 'surprise', g: 'surprise', look: { kuro: 'deep' } }],
      ['shiro', '……まぼろしよ。気をつけて。', { f: 'serious', stance: { shiro: 'ready' } }],
      ['tama', '……でも……やさしい声、だった。', { f: 'worry', g: 'tilt' }],
      ['n', '闇の中から、影と、さまよう鎧が現れた！', { enter: ['e:kageneko', 'e:yoroi'], cam: 'wide', stance: { all: 'ready' } }],
    ] },
  c4_03b: { title: '影の壁', bgm: 'dark',
    stage: { zone: 'cave', at: [2, -15], face: 0, points: { wall: [0, 2, 10], west: [-33, 1, 28], east: [49, 1, -28] } },
    lines: [
      ['n', '大空洞の奥。北へ続く坑道を、黒い霧のような壁がふさいでいた。', { cam: 'look:wall', dur: 7, look: { all: 'wall' } }],
      ['mike', 'なにこれ……さわると、つめたい！', { f: 'surprise', g: 'recoil' }],
      ['shiro', '闇の魔力が、こり固まってるのね。……こういうのは、強い光に弱いはずよ。', { f: 'serious', g: 'think' }],
      ['kuro', '……光の水晶だ。この洞窟には、光をためこむ水晶がある。……あの日、リンがそれを灯して、道を開いた。', { f: 'serious', g: 'lookDown' }],
      ['tama', '……あっちにも、こっちにも……ちいさく、ひかってる。', { f: 'sleepy', g: 'point', look: { all: 'west' } }],
      ['kuro', '……三つだ。三つの光を、大空洞の大水晶に集める。', { f: 'serious', g: 'nod', look: { kuro: 'east' } }],
      ['kuro', '……だが、それだけでは足りない。大水晶の光は、まっすぐにしか進まない。……リンは、水晶の鏡の向きを変えて、光の筋をこの壁まで導いた。', { f: 'serious', g: 'explain' }],
      ['shiro', '光の鏡……。鏡で光を曲げて、壁の前の受けの水晶に当てるのね。……ふふん、天才の出番じゃない。', { f: 'smug', g: 'hipHand' }],
      ['kuro', '……気をつけろ。鏡は、同じ色どうしが根もとでつながっている。一枚回すと、同じ色の鏡がみんな回る。', { f: 'serious', g: 'shake' }],
      ['kuro', '……あの日、ゴロウは目の前の鏡ばかり回して、光を三度も迷子にした。……光がどこを通るか、先まで考えろ。', { f: 'serious', g: 'lookDown' }],
      ['mike', 'ぼく、鏡に顔うつして遊ぶのは得意！', { f: 'joy', g: 'raise', r: { kuro: 'serious' } }],
      ['n', '（洞窟のあちこちにある「光の水晶」を三つ灯すと、大空洞の南の大水晶が光を放つ。「光の鏡」の前で F を押すと、その色の鏡がみんな回る。五色の鏡の向きを組み合わせて、光の筋をこの坑道の受けの水晶まで導こう）', { cam: 'wide', dur: 8 }],
    ] },
  c4_03c: { title: '割れた盾', bgm: 'sad',
    stage: { zone: 'cave_lake', at: [-11, 16], face: 0, points: { relics: [-2.4, 0.5, 3], wall: [11, 2, 8], east: [62, 3, 39] } },
    lines: [
      ['n', '地底湖のほとり。岸の岩に、割れた盾と、色あせたリボンが引っかかっていた。', { cam: 'look:relics', dur: 7, look: { all: 'relics' } }],
      ['kuro', '……ゴロウの盾。……それに、リンのリボンだ。', { f: 'sad', g: 'reach', look: { kuro: 'relics' } }],
      ['kuro', '……ここで、影に囲まれた。リンが光の水晶を灯して、橋への道を開いた。ゴロウは、そのリンをかばって、盾を割られた。', { f: 'pained', g: 'lookDown' }],
      ['kuro', '……ハヤテが先に橋を渡って、ゴロウとリンも、あとを追った。', { f: 'sad' }],
      ['mike', '……クロは？', { f: 'worry', to: 'kuro' }],
      ['kuro', '……俺は、しんがりで、うしろの影を食い止めて……気がついたら、ひとりで、この岸に倒れていた。……橋の向こうに、あいつらの姿は、もうなかった。', { f: 'sad', g: 'lookDown', r: { all: 'sad' } }],
      ['shiro', '……橋のたもとにも、あの影の壁があるわ。', { f: 'serious', g: 'point', look: { all: 'wall' } }],
      ['tama', '……ひかりの、すいしょう……また、さがそ。', { f: 'gentle', g: 'nod', to: 'kuro' }],
      ['kuro', '……気をつけろ。ここの影は、腹をすかせている。水晶の光も、長くはもたない。……リンは、三つの水晶を、ひと息に灯してまわった。', { f: 'serious', g: 'explain' }],
      ['mike', 'ひとつ灯したら、すぐに次のところまで走るんだね！', { f: 'serious', g: 'fist' }],
      ['shiro', '……回る順番も、考えたほうがよさそうね。遠回りしたら、きっと間に合わないわ。', { f: 'serious', g: 'think' }],
      ['n', '（岸の光の水晶を三つ灯して、橋の影の壁を消そう。一つめを灯すと、その光は 32 秒で消えてしまう。三つとも灯すまでに、最初の光が消えたら、やりなおし。Shift で走れる）', { cam: 'wide', dur: 8, look: { all: 'east' } }],
    ] },
  c4_03d: { title: '闇の淵', bgm: 'dark',
    stage: { zone: 'cave_deep', at: [0, 36], face: 0, points: { abyss: [0, -3, 10], memW: [-44, 1, 33], memI: [1, 1, 30], memE: [44.6, 1, 25] } },
    lines: [
      ['n', '洞窟の最深部。足もとには、底の見えない闇の淵が、大きく口を開けていた。', { cam: 'look:abyss', dur: 7, look: { all: 'abyss' } }],
      ['shiro', '……深い。落ちたら、きっと戻れないわ。', { f: 'worry', g: 'recoil' }],
      ['hayate', '（声）……クロ。……思い出せ。', { look: { all: 'memI' } }],
      ['kuro', '……ハヤテ……？', { f: 'surprise', g: 'surprise', look: { kuro: 'memI' } }],
      ['tama', '……あっちにも、こっちにも……あったかい、ひかり。', { f: 'gentle', g: 'point', look: { all: 'memW' } }],
      ['kuro', '……あいつらの、においがする。……俺は、ずっと、あいつらのことを、忘れようとしてきた。', { f: 'sad', g: 'lookDown' }],
      ['mike', 'じゃあ、今度は、ちゃんと思い出そうよ。みんなで。', { f: 'gentle', g: 'offer', to: 'kuro' }],
      ['hayate', '（声）……クロ。……俺たちが、どんな順で集まったか……覚えているか。', { look: { all: 'memI' } }],
      ['kuro', '……。……順番を、まちがえれば、また闇にのまれる……そういうことか。', { f: 'serious', g: 'lookDown' }],
      ['kuro', '……俺は、いちばんあとから来た。……それ以外は……思い出せない。', { f: 'sad', g: 'shake' }],
      ['n', '（闇の淵のまわりにある三つの「記憶のかけら」に、影の四剣が集まった順にふれると、北の闇の扉が開く。まちがえると、光は消えて、この岩棚まで押しもどされる。手がかりは、この最深部のどこかに）', { cam: 'wide', dur: 8, look: { all: 'memE' } }],
    ] },
  c4_04: { title: '過去の影', cast: ['e:kako_kuro'], bgm: 'boss',
    stage: { zone: 'cave_deep', at: [0, -32], face: 0, cast: { 'e:kako_kuro': { at: [0, 3.6] } } },
    lines: [
      ['n', '洞窟の最深部。三本の古い剣が、地面に突き立っている。……ハヤテ、リン、ゴロウの剣だ。', { cam: 'wide', dur: 6 }],
      ['kuro', '……あいつら、ここまで来ていたのか。', { f: 'sad', g: 'reach' }],
      ['e:kako_kuro', '……来たのか。また、仲間なんか連れて。'],
      ['mike', 'クロが、もう一匹！？', { f: 'surprise', g: 'recoil' }],
      ['e:kako_kuro', '俺は、お前の後悔だ。……仲間なんていらない。失うくらいなら、最初からひとりでいればいい。'],
      ['kuro', '……そうだ。俺は、ずっとそう思っていた。', { f: 'sad', g: 'lookDown' }],
      ['mike', 'クロ！', { f: 'worry', g: 'reach', to: 'kuro' }],
      ['kuro', '……でも。', { f: 'serious', look: { kuro: 'mike' } }],
      ['kuro', '……こいつらは、勝手についてくる。……面倒な連中だ。', { f: 'smile', g: 'shrug', r: { mike: 'joy', shiro: 'smile' } }],
      ['e:kako_kuro', '……なら、また失え！', { shake: 0.4, cam: 'wide' }],
      ['kuro', '……失わない。今度は、守る！', { f: 'angry', stance: { all: 'ready' } }],
    ] },
  c4_05: { title: '「もういいんだ」', bgm: 'sad',
    stage: { zone: 'cave_deep', at: [0, -32], face: 0,
      cast: { kuro: { at: [0, 0.6] }, mike: { at: [-1.3, 0] }, hayate: { at: [0, 4.2], hidden: true, face: 'kuro' }, rin: { at: [-1.4, 4], hidden: true, face: 'kuro' }, gorou: { at: [1.5, 4.1], hidden: true, face: 'kuro' } } },
    lines: [
      ['n', '影が消えると、淡い光の中に、三匹の猫が立っていた。', { fx: 'light:hayate', enter: ['hayate', 'rin', 'gorou'], cam: 'wide', dur: 7, r: { all: 'surprise' } }],
      ['kuro', '……ハヤテ……リン……ゴロウ……。', { f: 'surprise', g: 'reach' }],
      ['hayate', 'よう、クロ。……ずいぶん、にぎやかな仲間ができたな。', { f: 'smile', g: 'wave' }],
      ['kuro', '……すまない。俺だけ、生き残って……。', { f: 'cry', stance: { kuro: 'kneel' } }],
      ['rin', 'ばかね。あなたが生きていてくれて、私たち、うれしいのよ。', { f: 'gentle', g: 'handChest' }],
      ['gorou', 'そうそう！　おれたちの分まで、腹いっぱい食えよ！', { f: 'joy', g: 'laugh' }],
      ['hayate', 'クロ、もういいんだ。', { f: 'gentle', cam: 'hayate', close: true }],
      ['hayate', '俺たちの分まで、生きろ。', { f: 'smile', g: 'nod' }],
      ['kuro', '…………ああ。', { f: 'cry', g: 'nod' }],
      ['rin', '新しい仲間を、今度はちゃんと守ってあげてね。……あなたなら、できる。', { f: 'smile', g: 'wave' }],
      ['n', '三匹は、笑って、光の中に消えていった。', { exit: ['hayate', 'rin', 'gorou'], fx: 'sparkle:rin', cam: 'wide', dur: 6 }],
      ['kuro', '……ミケ。シロ。タマ。', { f: 'serious', stance: { kuro: 'idle' }, face: { kuro: 'mike' } }],
      ['kuro', '……今度は、全員で行く。', { f: 'smile', g: 'nod', cam: 'kuro', close: true, r: { mike: ['joy', 'cheer'], shiro: 'smile', tama: 'smile' } }],
      { flag: 'kuroGuard', say: 'クロは「守護」の力を覚えた！（戦闘スキルが、味方全体を守るわざに変わった）' },
      { bond: ['mike', 'kuro', 20] },
      ['kuro', '……それと、これだ。剣の根もとに、ハヤテの手帳が残っていた。……最後の頁に、こう書いてある。', { hold: { kuro: 'book' }, g: 'give' }],
      ['kuro', '「世界の感情が消える異変は、にゃんだーの樹とつながっている。手がかりは、谷の北の古代遺跡」', { f: 'serious', g: 'explain' }],
      ['shiro', '古代遺跡……！　天才の出番ね！', { f: 'smug', g: 'raise' }],
      ['tama', '……いせき……なんだか、なつかしい……。', { f: 'sleepy', g: 'tilt', cam: 'tama', close: true }],
    ] },
};

// 第一章〜第四章のあらすじ
const RECAP_1 = {
  c1_01: 'ぽかぽか村の三毛猫ミケは、今日も魚屋から魚を「味見」して、村長と魚屋のおばちゃんに叱られる。村長は、今年はにゃんだーの樹の実りが悪いと心配していた。',
  c1_02: 'その夜、村はずれの丘で星を見ていたミケの目の前に、大きな流れ星が落ちた。',
  c1_03: '翌朝、流れ星の落ちた場所で、ミケは倒れていた黒猫クロを見つける。「世界が滅びる」とつぶやくクロに、ミケは「その前に腹減ってない？」と魚を分けた。流れ星に見えたのは、にゃんだーの樹の「友情の実」。弱った樹が、熟す前に落としてしまった実だった。クロはそれを追ってきたという。',
  c1_04: '村長によれば、樹の実りが悪い今年、ほしふる森のネズミたちが村の食べ物を持っていくらしい。二匹は森の奥のネズミの王国をたずねることに。',
  c1_05: 'ほしふる森で、クロは「一人でいい」と言ってスライムに向かっていく。',
  c1_06: '森の奥で言い合う二匹の前に、どんぐりを守るリスたちが立ちはだかる。',
  c1_07: 'ネズミの王国では、キングネズミが村の食べ物を「みんなの冬のぶん」だと守っていた。',
  c1_08: '「俺だって……食べたかったんだよ……」。森のどんぐりが実らず、子どもたちを食べさせられなかったキングネズミに、ミケは自分の魚を分けた。キングネズミは「この借りは必ず返す」と約束する。',
  c1_09: '世界中で笑いや友情が失われつつあると知り、「ひとりぼっちは、さみしいよ」とつぶやいたミケは、クロと旅立つ。北の魔王は「世界を滅ぼす」と言っているが、実際に何かされたという話はないらしい。魚屋のおばちゃんは、焼き魚のお弁当を持たせてくれた。',
  c2_01: 'ミャオ街道を北へ。ミケの質問攻めに、クロは「しつこい」とあきれる。',
  c2_01b: '道しるべの手前で、けんか別れしかけた旅芸人のハチとブチに出会う。十年いっしょに旅してきたのに、けんかの理由も、楽しかった思い出も覚えていない。はじめて会った日のことを思い出して一曲合わせると、二匹はもう少しいっしょに行くことにした。世界では、つながりや思い出まで薄れはじめていた。',
  c2_02: '街道の宿場で、自称・天才魔法使いのシロと出会う。ファイアを唱えたはずが、空から魚が降ってきた。「わたしは天才だから失敗しない」と言い張るシロと一緒に、カラスとのら犬を追い払う。',
  c2_02b: 'シロが仲間になった。茶屋のおやじから、東の林でずっと眠っている子の話を聞く。',
  c2_03: 'まどろみの林のたんぽぽの原で、大きなたんぽぽの綿毛のてっぺんに眠る、頭に芽の生えた子猫を見つける。シロが大声で起こそうとしたとたん、春風がふいて、子猫は綿毛ごと川のむこうへ飛んでいってしまった。',
  c2_03g: '綿毛につかまって川を越えると、子猫はねむり花の谷の大きな花の中で眠っていた。ところが花が眠りの粉をはき、一行はそろって眠りこんでしまう。目をさますと子猫の姿はなく、ふらふらの足あとが林の奥へ続いていた。',
  c2_03h: 'ねぼけ歩きの子猫を追って、林のいちばん奥へ。大樹の前で、リスたちが子猫を「でっかいどんぐり」とまちがえて、うろへ運ぼうとしていた。寝ごとの「にゃあ」にリスたちは大あわて。小さなリスのしっぽに鼻をくすぐられて、子猫はついに目をさました。',
  c2_03i: '子猫の名前はタマ。どこから来たのかも分からないが、「空をとんで、花のベッドで寝て、どんぐりになる夢を見た」という。——それ、ぜんぶ本当にあったことだよ。タマは「みんなとあそびたい」と一行に加わった。',
  c2_03j: '帰り道、ねむり花の谷の花畑で、のら犬ところころ岩に囲まれる。タマは、戦いがはじまる前に眠ってしまった。',
  c2_03b: '戦いの間じゅう眠っていたタマは、目をさますと南の空を見上げて「おおきな木が、ないてる」とつぶやいた。また眠ってしまったタマを、クロが宿場まで運んだ。',
  c2_03c: '宿場の茶屋で夕ごはん。おやじは、旅の猫たちが笑い合わなくなったとこぼす。シロは「失敗しちゃいけないの」と杖を見つめていた。クロも、取り返しのつかない失敗をしたことがあるという。',
  c2_03d: '次の朝、シロがひとりでいなくなっていた。「ひとりで決めたからって、ひとりにしていいわけじゃないよ！」。魚のにおいをたどって、一行は宿場の南へ。',
  c2_03e: '風車の畑で、シロはひとりで魔法の特訓をしていた。失敗して降らせた魚をねらって、カラスとのら犬が集まってくる。',
  c2_03f: '「失敗したら、だれかがいなくなっちゃうかもしれない」と言うシロに、ミケは「シロが失敗したら、ぼくたちがなんとかする。仲間じゃん！」と笑った。シロは「万が一失敗したら、そのときはよろしく」と小さく答える。クロだけは「前に立つのは、俺の役目だ」とゆずらなかった。',
  c2_04a: 'ころころ岩の谷を抜けると、「一匹では通れぬ」なかよし関所。関所番のゴン爺は、からくりの門を仲間のわざで開けてみせよという。……ところが一行は、てんでばらばら。',
  c2_04: '二匹の門、力の門、番犬の庭、のろし台。仲間のわざでからくりを解き、大門が開いたとたん、はらぺこのイノシシが突っこんでくる。勝手に動くミケ、一人で戦うクロ、失敗するシロ、寝ているタマ。まとまりのないパーティ。',
  c2_05: 'イノシシもまた、食べ物を見つけられずにいた。戦いの最後には少しだけ息が合い、クロがはじめて小さく笑った。ゴン爺は「ほんとうの試しは、仲間を信じて背中をあずけること」と、通行手形をくれた。',
  c3_01: 'ニャハハ王国は、誰も笑わない街になっていた。',
  c3_02: 'ニャハハ王国では、祭りのたびに「笑いの実」を分け合って笑ううちに、実がなければ笑えない国になっていた。最後の実が魔王軍に盗まれて、国じゅうの猫が笑い方ごと忘れてしまったという。笑顔の塔には、泣いてばかりのピエロが住みついていた。',
  c3_03: '笑顔の塔には、笑っているのに楽しそうではない、ゲラゲラゴーストたちがいた。',
  c3_03a: '大ロビーの奥の通路を、「むすっ」とした顔の幕がふさいでいた。笑い声が三つそろえば、幕もつられて笑うかもしれない。一行は、1Fのあちこちにある笑い袋をさがす。',
  c3_03c: '二階のピエロの楽屋で、ピエロのネタ帳を見つけた。どのギャグにも「だれも、わらわなかった」と書いてあった。上への道は、巨大なびっくり箱がふさいでいる。',
  c3_03b: '三階の空中ブランコの間では、だれも乗っていないブランコがゆれていた。久しぶりの「お客さん」に、クスクスミミックたちが飛びかかってきた。',
  c3_03d: 'ミミックたちを追い払うと、北の高い桟敷に上への階段が見えた。一行は、サーカスのトランポリンでブランコの足場を中継ぎにして、桟敷へ跳ぶ。',
  c3_04: '塔の最上階の大舞台で、泣き虫ピエロが「無理やりにでも笑わせてあげる」と襲いかかる。',
  c3_05: '「僕だって……笑いたかったんだ」。泣くピエロのひざで、タマが眠ってしまい、みんなが思わず笑い出す。塔にひさしぶりの笑い声が響き、一行は「話す」ことの大切さを知った。',
  c3_06: '王国にほんの少し笑顔が戻る。けれど、樹が弱ったままではまた笑いはしぼんでしまう。クロは、昔の仲間の記録が残る故郷、くろねこ谷へ行くと決める。',
  c4_01: 'くろねこ谷の奥の集落で、長老のクロネ婆がクロを迎える。',
  c4_02: '丘の上の墓標。クロのかつての仲間「影の四剣」は、魔王軍を追う途中、闇の中で襲われて全滅していた。四つ目の石は、クロ自身の分だった。ミケは、自分も幼いころに両親を失ったことを、はじめてクロに打ち明けた。',
  c4_02b: '墓標にわいた影を追い払ったあと、クロは思い出す。ハヤテは毎晩、野営のテントで調査の記録をつけていた。最後の夜のテントが、まだ川のほとりに残っているかもしれない。',
  c4_02c: '川のほとりの野営あとの古いテントに、記録の手帳はなかった。クロは思い出す。あの朝、ハヤテは手帳を懐に入れて出ていった——仲間たちが全滅した、黒影洞窟へ。',
  c4_03: 'ハヤテの手帳を探しに、仲間たちが全滅した黒影洞窟へ。なつかしい声が、クロを呼んでいた。',
  c4_03b: '大空洞の奥の坑道を、闇の魔力がこり固まった「影の壁」がふさいでいた。あの日、リンが光の水晶を灯して道を開いたことを、クロは思い出す。',
  c4_03c: '地底湖の岸で、ゴロウの割れた盾とリンのリボンを見つけた。あの日、影の四剣はここで影に囲まれた。リンが光の水晶で道を開き、ゴロウはリンをかばって盾を割られた。三匹は橋の向こうへ進み、しんがりでうしろの影を食い止めたクロだけが、ひとり岸に倒れていた。橋のたもとにも、影の壁がある。',
  c4_03d: '洞窟の最深部には、底の見えない闇の淵が口を開けていた。ハヤテの声が「思い出せ」とクロを呼ぶ。淵のまわりの三つの記憶のかけらに、影の四剣が集まった順にふれ、クロは、忘れようとしてきた仲間たちの思い出と向き合う。',
  c4_04: '洞窟の最深部で、クロの後悔が「過去の影」として立ちはだかる。',
  c4_05: '影を越えた先で、かつての仲間たちの幻が「クロ、もういいんだ。俺たちの分まで、生きろ」と告げる。過去を受け入れたクロは「守護」の力を覚え、「今度は、全員で行く」と誓う。洞窟の奥に残されていたハヤテの手帳には、谷の北の古代遺跡が記されていた。',
};
