'use strict';
// ============================================================
//  にゃんこファンタジー 台本（第五章〜エピローグ・おまけ・友情イベント）と、物語の進行
// ============================================================
Object.assign(SCENES, {
  // ================= 第五章　眠れる子猫 =================
  c5_01: { title: '古代遺跡', cast: ['e:sekizou'], bgm: 'field',
    stage: { zone: 'ruins_out', at: [-6, 20], face: 0, cast: { 'e:sekizou': [{ at: [-2.6, 5.4], hidden: true }, { at: [2.4, 5.8], hidden: true }] }, points: { gate: [6, 5, 50] } },
    lines: [
      ['n', 'くろねこ谷の北。森に埋もれるように、古代の遺跡が眠っていた。', { cam: 'look:gate', dur: 7, look: { all: 'gate' } }],
      ['shiro', 'すごい……！　これ、何千年も前の猫たちの遺跡よ！', { f: 'joy', g: 'cheer' }],
      ['tama', '……ここ、しってる……ような……。', { f: 'sleepy', g: 'tilt' }],
      ['kuro', '……タマ？', { f: 'serious', to: 'tama' }],
      ['tama', '……ううん。……ねむいだけ。', { f: 'sleepy', g: 'shake' }],
      ['n', '石のねこ像が、ぎぎぎ……と動き出した！', { enter: 'e:sekizou', shake: 0.3, cam: 'wide', r: { all: 'surprise' }, stance: { all: 'ready' } }],
      ['mike', 'わわっ、像が動いた！', { f: 'surprise', g: 'recoil' }],
    ] },
  c5_02: { title: '壁画の回廊', cast: ['e:hotaru'], bgm: 'dark',
    stage: { zone: 'ruins_in', at: [0, 14], face: 0,
      cast: { 'e:hotaru': [{ at: [-2, 6], hidden: true }, { at: [2.2, 6.6], hidden: true }] },
      points: { mural0: [-16.4, 2.2, 4], mural1: [16.4, 2.2, 18], mural2: [-16.4, 2.2, 32] } },
    lines: [
      ['shiro', '見て、壁画よ！　……大きな猫が、樹を抱いて眠ってる。', { f: 'joy', g: 'point', cam: 'look:mural0', dur: 6, look: { all: 'mural0' } }],
      ['kuro', '……こっちは、四匹の猫が、樹のまわりで手をつないでいる。', { f: 'serious', g: 'point', cam: 'look:mural1', dur: 6, look: { all: 'mural1' } }],
      ['mike', '……一匹、すごく小さい。', { f: 'neutral', g: 'tilt' }],
      ['tama', '……。', { f: 'neutral', look: { tama: 'mural1' } }],
      ['shiro', '古代文字もあるわ。えっと……「樹は、猫たちのつながりから生まれた。つながりが絶えるとき、樹は……最後のにゃんこを生む」', { f: 'serious', g: 'think', cam: 'look:mural2', dur: 7, look: { all: 'mural2' } }],
      ['mike', '……最後のにゃんこ？', { f: 'worry', g: 'tilt' }],
      ['tama', '……。', { f: 'worry', cam: 'tama', close: true }],
      ['n', '壁画の光に引き寄せられるように、古代ほたるが舞い降りてきた。', { enter: 'e:hotaru', cam: 'wide', stance: { all: 'ready' } }],
    ] },
  c5_03: { title: '封印の扉', cast: ['e:guardian'], bgm: 'dark',
    stage: { zone: 'ruins_in', at: [0, -25], face: 0,
      cast: { 'e:guardian': { at: [0, 8.2], hidden: true } }, points: { door: [0, 3.2, 12] } },
    lines: [
      ['n', '回廊の奥に、封印された大きな扉があった。', { cam: 'look:door', dur: 6, look: { all: 'door' } }],
      ['shiro', '封印の魔法……天才のわたしでも、びくともしないわ。', { f: 'worry', g: 'reach' }],
      ['kuro', '……俺の剣でも、無理だ。', { f: 'serious' }],
      ['tama', '……。', { f: 'neutral', move: { tama: [0, 7.5] }, speed: 1.2, look: { all: 'tama' } }],
      ['n', 'タマが扉にふれると、封印の光が、やさしく広がった。', { fx: 'seal', g: 'reach', cam: 'wide', dur: 6, r: { all: 'surprise' } }],
      ['shiro', '開いた……！？　タマ、どうして……', { f: 'surprise', g: 'surprise' }],
      ['tama', '……わかんない。……扉が、「おかえり」って言った。', { f: 'sleepy', g: 'tilt', face: { tama: 'mike' } }],
      ['n', '扉の上に、古代文字が浮かび上がる。', { cam: 'look:door', dur: 5 }],
      ['shiro', '……「最後のにゃんこ」。', { f: 'surprise' }],
      ['tama', '……ぼく？', { f: 'surprise', cam: 'tama', close: true }],
      ['n', '扉の奥から、遺跡の守護神が姿を現した！', { enter: 'e:guardian', move: { tama: [0.5, 2] }, speed: 3, shake: 0.5, cam: 'wide', stance: { all: 'ready' } }],
      ['e:guardian', '……封印を開けられるのは、最後のにゃんこだけ……。その心、確かめさせてもらおう。'],
    ] },
  c5_04: { title: '樹の秘密', cast: ['e:guardian'], bgm: 'sad',
    stage: { zone: 'ruins_in', at: [0, -25], face: 0, cast: { 'e:guardian': { at: [0, 8.2] } } },
    lines: [
      ['n', '守護神は静かに止まり、光の文字で語りはじめた。', { cam: 'foe:e:guardian', dur: 6 }],
      ['n', '……にゃんだーの樹は、猫たちの笑い・友情・思い出・優しさ……心のつながりを糧に生きている。', '遺跡の声', { cam: 'wide', dur: 7 }],
      ['n', 'つながりが薄れると、樹は弱り、感情の実は実らなくなる。実らなければ、猫たちはさらに心を閉ざし、つながりは薄れていく。', '遺跡の声'],
      ['n', '樹が枯れかけたとき、樹はひとつの命を生む。樹を救うための子——最後のにゃんこを。', '遺跡の声', { look: { all: 'tama' } }],
      ['n', '最後のにゃんこは、樹と心がつながっている。樹が弱るほど、その子は深く眠る。', '遺跡の声'],
      ['kuro', '……タマがいつも眠っていたのは、そのせいか。', { f: 'serious', look: { kuro: 'tama' } }],
      ['tama', '……ぼく……樹から、生まれたの？', { f: 'surprise', g: 'lookDown' }],
      ['mike', 'タマはタマだよ！　どこから生まれたって、関係ない！', { f: 'angry', g: 'fist', to: 'tama' }],
      ['shiro', '……そうよ。タマは、わたしが面倒見てる、わたしの……仲間なんだから。', { f: 'worry', g: 'handChest' }],
      ['shiro', '……今度は、ぜったいに、手をはなさないんだから。', { f: 'worry', g: 'fist' }],
      ['kuro', '……今度は？', { f: 'serious', g: 'tilt', to: 'shiro' }],
      ['shiro', 'な、なんでもないわよ！', { f: 'shy', g: 'turnAway' }],
      { bond: ['mike', 'tama', 10] },
      ['kuro', '……樹を枯らしているのは、魔王じゃない。世界に広がった……孤独、か。', { f: 'serious', g: 'think' }],
      ['n', '樹の心臓は、いにしえの猫たちが封じた。その扉を開けられるのもまた、最後のにゃんこだけ……。', '遺跡の声'],
      ['n', '樹の根は、世界じゅうの地下をめぐり、その先は「世界の果て」に行きつく。誰の声も届かぬ、音も色もない場所に……。', '遺跡の声'],
      ['n', '……北の魔王もまた、樹の根に巣くう「何か」を知っている……。', '遺跡の声'],
      ['shiro', '魔王が……？', { f: 'surprise' }],
      ['mike', 'じゃあ、魔王に会いに行こう！　笑いの実も、返してもらわなきゃ！', { f: 'serious', g: 'fist' }],
      ['kuro', '……魔王城は、遺跡の東の魔王領だ。', { f: 'serious', g: 'point' }],
      ['tama', '……みんな……いっしょ？', { f: 'worry', g: 'tilt' }],
      ['mike', '当たり前じゃん！', { f: 'joy', g: 'cheer', r: { tama: 'smile' } }],
    ] },

  // ================= 第六章　魔王城へ =================
  c6_01: { title: '魔王領', cast: ['e:mazoku', 'e:kangoshi'], extra: ['mazoku_yukyu', 'mazoku_nurse'], bgm: 'field',
    stage: { zone: 'demon_land', at: [-2, 24], face: 0,
      cast: { mazoku_yukyu: { at: [-1, 2.8], face: 'mike' }, mazoku_nurse: { at: [1.6, 3.2], face: 'mike' },
        'e:mazoku': { at: [-2.6, 7], hidden: true }, 'e:kangoshi': { at: [2.6, 7.4], hidden: true } },
      points: { castle: [2, 14, 180] } },
    lines: [
      ['n', '魔王領。紫の空の下、おそろしい魔王城がそびえている。……はずなのだが。', { cam: 'look:castle', dur: 7, look: { all: 'castle' } }],
      ['mazoku_yukyu', 'あ、どうも。魔王軍の者です。……あの、有給休暇の申請って、どこに出せばいいか知りません？', { f: 'worry', g: 'bow' }],
      ['mike', 'ゆうきゅう？', { f: 'neutral', g: 'tilt' }],
      ['mazoku_nurse', 'はーい、次の方〜。健康診断ですよ〜。あら、猫ちゃんたちも受けていく？', { f: 'smile', g: 'wave' }],
      ['shiro', '……ここ、本当に魔王領なの？', { f: 'surprise', g: 'shrug' }],
      ['kuro', '……油断するな。', { f: 'shy' }],
      ['mazoku_yukyu', '魔王さまは、最近ずーっと城にこもって、ひとりで猫じゃらしで遊んでるんですよ……。', { f: 'worry', g: 'explain' }],
      ['mazoku_yukyu', 'あっ、これ言っちゃいけないやつだった！　し、侵入者だーー！', { f: 'surprise', g: 'recoil', enter: ['e:mazoku', 'e:kangoshi'], later: [0.5, { exit: ['mazoku_yukyu', 'mazoku_nurse'] }], stance: { all: 'ready' } }],
    ] },
  c6_02: { title: '魔王城の健康診断', cast: ['e:kanbu'], extra: ['mazoku_nurse2'], bgm: 'field',
    stage: { zone: 'demon_castle', at: [11.5, 16], face: 0,
      cast: { mazoku_nurse2: { at: [0.5, 2.6], face: 'mike' }, 'e:kanbu': { at: [0, 6.5], hidden: true } } },
    lines: [
      ['n', '魔王城の中では、年に一度の健康診断が行われていた。', { cam: 'wide', dur: 6 }],
      ['mazoku_nurse2', 'はい、次は体重をはかりますね〜。……あら、あなた、ちょっと魚の食べすぎね。', { f: 'smile', g: 'point', to: 'mike' }],
      ['mike', 'えっ、ぼく！？', { f: 'surprise', g: 'recoil' }],
      ['shiro', '……ぷっ。', { f: 'joy', g: 'laugh' }],
      ['kuro', '……食べすぎだ。', { f: 'smile' }],
      ['tama', '……ミケ、まるい。', { f: 'smile', g: 'nod' }],
      ['mike', 'みんな、ひどい！', { f: 'pout', g: 'pout' }],
      ['e:kanbu', 'こ、こら！　保健係が侵入者の健康診断をしてどうする！　……ああもう、胃が痛い……。', { enter: 'e:kanbu', later: [0.8, { exit: 'mazoku_nurse2' }] }],
      ['kuro', '……来るぞ。', { f: 'serious', stance: { all: 'ready' } }],
    ] },
  c6_03: { title: '魔王', bgm: 'boss',
    stage: { zone: 'demon_throne', at: [11.5, 5.4], face: 0, host: 'maou',
      cast: { maou: { at: [0, 3.6], face: [0, 6], item: 'jarashi' } } },
    lines: [
      ['n', '玉座の間。大きなクッションの前で、黒い猫がひとり、猫じゃらしにじゃれていた。', { cam: 'maou', dur: 6, fx: 'lure:maou' }],
      ['maou', 'にゃっ、にゃっ……ふふ、捕まえたぞ……にゃっ——', { f: 'joy', g: 'laugh' }],
      ['n', '……目が合った。', { face: { maou: 'mike' }, cam: 'wide', dur: 4 }],
      ['maou', '…………。', { f: 'surprise', cam: 'maou', close: true }],
      ['maou', '……見たな。', { f: 'shy' }],
      ['mike', '……見ちゃった。', { f: 'surprise' }],
      ['maou', 'い、今のは違う！　余は魔王である！　これは、その……鍛錬だ！', { f: 'angry', g: 'point', hold: { maou: null } }],
      ['shiro', '猫じゃらしの？', { f: 'smug', g: 'tilt' }],
      ['kuro', '……鍛錬。', { f: 'serious' }],
      ['maou', 'ええい、黙れ！　よく来たな、勇者ども。余は、この世界を滅ぼす者だ！', { f: 'smug', g: 'raise', shake: 0.3 }],
      ['mike', '笑いの実を返して！　ニャハハ王国のみんなが、困ってるんだ！', { f: 'angry', g: 'fist' }],
      ['maou', 'ふん……返してほしくば、余を倒してみよ！', { f: 'angry', stance: { maou: 'ready', all: 'ready' }, cam: 'wide' }],
      ['n', '（ヒント：マオウに「はなす」を使うと、ミケが猫じゃらしを見せる。）', { cam: 'wide', dur: 5 }],
    ] },
  c6_04: { title: '魔王の孤独', bgm: 'sad',
    stage: { zone: 'demon_throne', at: [11.5, 5.4], face: 0, host: 'maou', cast: { maou: { at: [0, 3], stance: 'kneel', face: 'mike', f: 'pained' } } },
    lines: [
      ['maou', '……ぐ……余が、負けるとは……。', { f: 'pained', g: 'lookDown' }],
      ['mike', 'ねえ。どうして、世界を滅ぼそうとしたの？', { f: 'sad', g: 'tilt' }],
      ['maou', '…………。', { f: 'sad', g: 'lookDown' }],
      ['maou', '……寂しいから。', { f: 'sad', cam: 'maou', close: true, r: { all: 'surprise' } }],
      ['maou', '余と遊んでくれる者がいない。', { f: 'cry' }],
      ['maou', '……「世界を滅ぼす」と言えば、誰かが城まで来てくれると思った。……勇者でも、よかったのだ。', { f: 'sad', g: 'lookDown' }],
      ['maou', '部下どもは、余を怖がるか、有給をほしがるばかり。……笑いの実を盗んだのも、その実があれば、ひとりでも笑えると思ったからだ。', { f: 'sad', hold: { maou: 'fruitGray' } }],
      ['maou', '……だが、ひとりで持っていても、実は灰色になるばかりだった。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……マオウも……さみしかったんだね。', { f: 'sad', move: { tama: [0.5, 2] } }],
      ['maou', '……ふん。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'じゃあ、ぼくたちと遊ぼうよ！', { f: 'joy', g: 'offer', hold: { mike: 'jarashi' } }],
      ['maou', '……！　そ、それは……！', { f: 'surprise', fx: 'lure:maou', stance: { maou: 'idle' } }],
      ['maou', '……ぬう……卑怯なり……。', { f: 'shy', g: 'pout', r: { shiro: ['joy', 'laugh'], kuro: 'smile' } }],
      ['maou', '……勇者よ。樹の根元には、何かがいる。……ずっと余に「ひとりでいい」とささやいてきた、黒い何かが。', { f: 'serious', hold: { mike: null } }],
      ['kuro', '……「ひとりでいい」……。', { f: 'serious', g: 'lookDown', cam: 'kuro', close: true }],
      ['kuro', '……ひとつ聞く。昔、黒影洞窟で、四匹の猫を襲ったのは、お前の兵か。', { f: 'serious', to: 'maou' }],
      ['maou', '黒影洞窟？　余の兵は、あそこへは近づかぬ。……あそこにも、その黒い何かが巣くっておる。', { f: 'serious', g: 'shake' }],
      ['kuro', '……俺たちを襲ったのは、魔王軍じゃなかったのか。', { f: 'surprise', cam: 'kuro', close: true, r: { mike: 'worry' } }],
      ['maou', '余の兵は、有給をほしがるばかりの者たちだ。城の外で戦をしたことなど、一度もない。', { f: 'sad', g: 'shrug' }],
      ['mike', 'クロ……。', { f: 'worry', g: 'reach', to: 'kuro' }],
      ['kuro', '……そうか。……本当の敵は、樹の根元にいるんだな。', { f: 'serious', g: 'nod' }],
      ['maou', '笑いの実は、王国へ返そう。……それと。', { f: 'serious' }],
      ['n', 'マオウの手の中で、灰色だった実が、ほんのりと光りはじめた。', { hold: { maou: 'fruit' }, fx: 'sparkle:maou', cam: 'maou', close: true }],
      ['shiro', '見て、実が光ってる……！', { f: 'surprise', g: 'point' }],
      ['maou', '……勘違いするな。余は、退屈しのぎについていくだけだ。', { f: 'shy', g: 'turnAway' }],
      { give: 'maou' },
      ['mike', 'よろしくね、マオウ！', { f: 'joy', g: 'cheer' }],
      ['maou', '……ふん。……よろしく、してやらんこともない。', { f: 'shy', g: 'nod' }],
      ['n', '笑いの実は、魔族兵たちの手で、ニャハハ王国に届けられた。一行は、にゃんだーの樹の根元へ向かう。', { cam: 'wide', dur: 7 }],
    ] },

  // ================= 第七章　最後のにゃんこ =================
  c7_01: { title: 'にゃんだーの樹', cast: ['e:kakera'], bgm: 'sad',
    stage: { zone: 'tree_root', at: [0, -20], face: 180, cast: { 'e:kakera': [{ at: [-2.4, 6], hidden: true }, { at: [2.4, 6.4], hidden: true }] }, points: { tree: [0, 30, 60] } },
    lines: [
      ['n', 'ぽかぽか村の南、丘の向こう。にゃんだーの樹は、灰色の葉を、音もなく落とし続けていた。', { cam: 'look:tree', dur: 8, look: { all: 'tree' } }],
      ['tama', '……樹が……ないてる。', { f: 'sad', g: 'lookUp' }],
      ['mike', 'こんなに、弱ってたなんて……。', { f: 'sad' }],
      ['kuro', '……旅の始まりの夜。俺は、ひとりでここを調べていた。', { f: 'serious', look: { kuro: 'tree' } }],
      ['kuro', '……てっぺん近くの枝の先に、友情の実がひとつだけ、ついていた。今年、この樹に残っていた、最後の友情の実だ。', { f: 'serious', g: 'lookUp' }],
      ['kuro', '……まだ熟してもいないのに、軸がちぎれかけていた。落ちたら、割れる。……取ろうと、枝の先まで手を伸ばした。', { f: 'serious', g: 'reach' }],
      ['kuro', '……そこで、足が滑った。落ちながら、とっさに実をつかんだ。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'こ、この樹のてっぺんで！？', { f: 'surprise', g: 'lookUp', look: { mike: 'tree' } }],
      ['kuro', '……ぶら下がった俺の重さで、枝が大きくしなって——いきおいよく、はね返った。', { f: 'serious', g: 'raise' }],
      ['kuro', '……そのはずみで、軸が折れた。実ごと、空へ放り出されて……光る実にしがみついたまま、夜空を飛んで……気がついたら、お前の村の丘だった。', { f: 'serious', g: 'point' }],
      ['shiro', 'むちゃくちゃよ……。', { f: 'surprise', g: 'shrug' }],
      ['kuro', '……思ったより、遠かった。', { f: 'shy', g: 'turnAway' }],
      ['mike', '……クロ、その実を、守りたかったんだね。', { f: 'gentle', to: 'kuro' }],
      ['kuro', '……結局、割ってしまったがな。', { f: 'sad', g: 'lookDown' }],
      ['mike', 'でも、そのおかげで、ぼくたち会えたんだよ！', { f: 'joy', g: 'hop' }],
      ['kuro', '……ふん。', { f: 'shy', g: 'turnAway', r: { shiro: 'smile', tama: 'smile' } }],
      ['n', '根もとの南。根のトンネルの奥に、古い封印の扉があった。', { cam: 'wide', dur: 6 }],
      ['maou', '……余も、あの声をたどって、ここまでは来た。だが、この扉だけは開かなんだ。', { f: 'serious', g: 'point' }],
      ['kuro', '……俺もだ。何度調べても、びくともしなかった。', { f: 'serious', g: 'nod' }],
      ['shiro', '世界中の猫が樹を調べても、何も見つからなかったわけね。……樹を守るための封印が、中に入りこんだものまで隠してたんだわ。', { f: 'serious', g: 'think' }],
      ['tama', '……この扉も、「おかえり」って、言ってる。', { f: 'gentle', g: 'reach', move: { tama: [0, 2.4] }, speed: 1.2, look: { all: 'tama' } }],
      ['n', 'タマがふれると、封印の扉は、静かに開いた。', { fx: 'sparkle:tama', cam: 'wide', dur: 6, r: { all: 'surprise' } }],
      ['maou', '……扉の奥から、あの声がする。', { f: 'serious', g: 'point' }],
      ['n', '扉の奥から、黒いかけらがあふれ出した！', { fx: 'shadow', enter: 'e:kakera', cam: 'wide', stance: { all: 'ready' } }],
    ] },
  c7_02: { title: '樹の地下', cast: ['e:utsuro'], bgm: 'dark',
    stage: { zone: 'tree_under', at: [0, -24], face: 180, cast: { 'e:utsuro': { at: [0, 6], hidden: true } } },
    lines: [
      ['n', '封印の扉の奥。樹の根の下には、光る樹液が流れる、広い地下が広がっていた。', { cam: 'wide', dur: 7 }],
      ['shiro', '……静かすぎる。誰の声も、届かないみたい。', { f: 'worry' }],
      ['kuro', '……来るぞ。', { f: 'serious', enter: 'e:utsuro', stance: { all: 'ready' } }],
    ] },
  c7_03: { title: 'コドク', cast: ['e:kodoku_kage'], bgm: 'boss',
    stage: { zone: 'tree_under', at: [0, 14], face: 180, cast: { 'e:kodoku_kage': { at: [0, 8] } }, points: { heart: [0, 3.4, 22] } },
    lines: [
      ['n', '樹の心臓の前に、黒い影がうずくまっていた。', { fx: 'darkness', cam: 'wide', dur: 7 }],
      ['e:kodoku_kage', '……来たか。つながりなどという、はかないものを抱えて。'],
      ['mike', 'きみが……樹を枯らしてるの？', { f: 'serious' }],
      ['e:kodoku_kage', '私はコドク。世界に広がった、孤独そのもの。……お前たちの心の中にも、私はいる。'],
      ['e:kodoku_kage', '両親を失った、ひとりの夜。仲間を失った、ひとりの朝。救えなかった、あの日。……遊び相手のいない、長い時間。', { r: { mike: 'pained', kuro: 'sad', shiro: 'worry', maou: 'sad' } }],
      ['shiro', '……どうして、それを……。', { f: 'surprise', g: 'bothChest' }],
      ['kuro', '……黒影洞窟の闇。……あれも、お前か。', { f: 'angry', to: 'e:kodoku_kage' }],
      ['e:kodoku_kage', 'そうだ。お前の仲間を闇に沈めたのは、私だ。……お前だけを残してな。'],
      ['kuro', '……なぜ、俺だけ。', { f: 'angry', stance: { kuro: 'ready' } }],
      ['e:kodoku_kage', 'ひとりにするためだ。……樹の上で、ひとりで調べていたお前に、私は何度もささやいた。「ひとりでいい」と。'],
      ['kuro', '……あの声は……俺の声じゃ、なかったのか。', { f: 'surprise', cam: 'kuro', close: true, r: { all: 'surprise' } }],
      ['mike', '……だから、クロ、最初に会ったとき「一人でいい」って……。', { f: 'worry', to: 'kuro' }],
      ['e:kodoku_kage', 'ひとりでいれば、傷つかない。……さあ、ひとりになれ。', { shake: 0.5 }],
      ['mike', 'ならない！', { f: 'angry', stance: { all: 'ready' } }],
    ] },
  c7_04: { title: '最後のにゃんこ', cast: ['e:kodoku_kage'], bgm: 'sad',
    stage: { zone: 'tree_under', at: [0, 14], face: 180, cast: { 'e:kodoku_kage': { at: [0, 9], hidden: true } }, points: { heart: [0, 3.4, 22] } },
    lines: [
      ['n', '影は散った。……だが、すぐにまた、闇が集まりはじめる。', { fx: 'shadow:heart', cam: 'wide', dur: 6 }],
      ['maou', '……倒しても、消えぬのか。', { f: 'serious' }],
      ['kuro', '……世界中の孤独が、こいつの力になっている。', { f: 'serious' }],
      ['mike', '……ぼくが、もっと強ければ……。', { f: 'pained', g: 'fist', cam: 'mike', close: true }],
      ['tama', '……ねえ、みんな。', { f: 'gentle', move: { tama: [0, 3] }, look: { all: 'tama' } }],
      ['tama', '……ぼく、わかったんだ。……ぼくが、何のために生まれてきたのか。', { f: 'gentle', g: 'lookUp', look: { tama: 'heart' } }],
      ['tama', 'ぼくが樹になればいいんだよ。', { f: 'smile', face: { tama: 'mike' }, cam: 'tama', close: true, r: { all: 'surprise' } }],
      ['tama', 'ぼくが樹にとけて、樹の心臓になれば……樹は、また元気になる。……コドクも、きっと追い払える。', { f: 'smile', g: 'handChest' }],
      ['shiro', '……なに、言ってるの……？', { f: 'surprise' }],
      ['mike', 'そんなの違う。', { f: 'angry', cam: 'mike', close: true }],
      ['mike', '仲間を犠牲にして世界を救うなんて、勇者じゃない！', { f: 'angry', g: 'fist', shake: 0.2 }],
      ['kuro', '……俺もだ。', { f: 'serious', move: { kuro: [1, 3] }, stance: { kuro: 'ready' } }],
      ['kuro', '……もう二度と、仲間はなくさない。', { f: 'serious', g: 'nod' }],
      ['shiro', 'わ、わたしも！　……わたし、昔、魔法で大切な子を救えなかった。失敗するのが怖くて、ずっと天才のふりをしてた。', { f: 'cry', g: 'bothChest' }],
      ['shiro', 'でも……失敗してもいい。何度でもやり直せばいいって、みんなが教えてくれた。……タマを犠牲にする方法なんて、失敗よりずっといや！', { f: 'cry', g: 'fist' }],
      { flag: 'shiroGrow', say: 'シロは失敗を受け入れた！（魔法が失敗しても「失敗は成功のもと」で追撃が出るようになった）' },
      ['maou', '……余は、せっかくできた遊び相手を、手放す気はない。', { f: 'smug', g: 'armsCrossed' }],
      ['tama', '……みんな……。', { f: 'cry' }],
      ['mike', '……タマ。ぼく、ずっと笑ってごまかしてた。お父さんとお母さんがいなくなって、さみしいって言ったら、止まらなくなりそうで。', { f: 'sad', g: 'handChest', to: 'tama' }],
      ['mike', 'でも、みんなといると、ほんとに笑えるんだ。……タマがいなくなったら、ぼく、もう笑えないよ。', { f: 'cry', g: 'bothChest' }],
      ['mike', 'さっき、「もっと強ければ」って思った。……でも、ちがった。', { f: 'gentle', g: 'shake' }],
      ['mike', '強いから助けるんじゃない。仲間だから助けるんだ。', { f: 'gentle', g: 'offer', to: 'tama', cam: 'mike', close: true }],
      { flag: 'mikeHero', say: 'ミケの「食いしん坊」に、仲間の数だけ強くなる力が加わった！' },
      ['e:kodoku_kage', '……ならば、その仲間ごと、ひとりにしてやろう。', { enter: 'e:kodoku_kage', fx: 'darkness', shake: 0.5, cam: 'wide' }],
      ['n', 'コドクが、一行の過去の幻を、次々に見せつける。仲間の姿が、闇に遠ざかっていく——', { cam: 'wide', dur: 7, r: { all: 'pained' } }],
      ['mike', '……みんな！　ぼくの声、聞こえる！？', { f: 'pained', g: 'reach' }],
      ['kuro', '……ああ。聞こえる。', { f: 'serious' }],
      ['shiro', '聞こえるわよ！', { f: 'cry' }],
      ['tama', '……うん。', { f: 'smile' }],
      ['maou', '……うるさいほどにな。', { f: 'smug' }],
      ['n', '互いを呼ぶ声が、幻を打ち破った。', { fx: ['dawn', 'light'], cam: 'wide', dur: 6, r: { all: 'smile' } }],
      ['e:kodoku_kage', '……くっ。だが、お前たちだけでは足りぬ。世界中の孤独は、お前たち五匹のつながりより、ずっと重い……。'],
      ['n', 'コドクは、樹の根を伝って、世界の果てへと消えていった。', { exit: 'e:kodoku_kage', cam: 'wide' }],
      ['shiro', '世界の果て……遺跡の声が言ってた、樹の根の行きつく先ね。誰の声も届かない、音も色もない場所……。', { f: 'worry', g: 'think' }],
      ['kuro', '……世界中の孤独が、根を伝って流れつく場所だ。あいつの巣には、うってつけだな。', { f: 'serious' }],
      ['tama', '……あっち。……根の先から、あの声がする。', { f: 'worry', g: 'point' }],
      ['mike', 'でも、根の先なんて、どうやって行くの？', { f: 'worry', g: 'tilt', to: 'tama' }],
      ['tama', '……根もとの東で、いちばん太い根が一本、地面から出て、果てのほうへのびてる。……その根をたどっていけば、いける。', { f: 'serious', g: 'point' }],
      ['tama', '……ぼく、樹とつながってるから、わかるの。', { f: 'gentle', g: 'handChest' }],
      ['maou', '……声が届かぬ場所なら、届くまで、もっと多くの者の声を集めればよい。', { f: 'serious', g: 'shrug' }],
      ['mike', '……そうか！　ぼくたちが旅で出会ったみんなに、力を貸してもらおう！', { f: 'joy', g: 'cheer' }],
      ['kuro', '……村へ戻るぞ。そこから始める。', { f: 'serious', g: 'nod' }],
    ] },

  // ================= 第八章　みんなのにゃん力 =================
  c8_01: { title: 'ぽかぽか村の危機', cast: ['e:kagejuu'], bgm: 'dark',
    stage: { zone: 'pokapoka', at: [0, 16], face: 0,
      cast: { sonchou: { at: [-2, 4], face: 'mike' }, sakanaya: { at: [1.5, 3.4], face: 'mike', item: 'fish' }, 'e:kagejuu': [{ at: [-3, 9] }, { at: [3.2, 9.6] }] } },
    lines: [
      ['n', 'ぽかぽか村に戻ると、黒い影の獣たちが、村を取り囲んでいた。', { fx: 'darkness', cam: 'wide', dur: 7, r: { all: 'surprise' } }],
      ['sonchou', 'ミケ！　戻ってきたのか！', { f: 'surprise', g: 'surprise' }],
      ['sakanaya', 'あんたたち、下がってな！　……ほら、ミケ！', { f: 'angry', g: 'point' }],
      ['sakanaya', 'あんたに食べさせる魚くらい、いくらでも焼いてやるよ！', { f: 'smile', g: 'give', cam: 'sakanaya', close: true }],
      ['mike', 'おばちゃん……！', { f: 'cry', hold: { sakanaya: null, mike: 'fish' } }],
      ['mike', '……よし。行くよ、みんな！　村を守るんだ！', { f: 'serious', g: 'fist', stance: { all: 'ready' }, hold: { mike: null } }],
    ] },
  c8_02: { title: '集まる猫たち', bgm: 'hope', extra: ['sonchou', 'sakanaya', 'king_npc', 'piero_npc', 'nyahaha_ou', 'kurone', 'mazoku_yukyu', 'chaya'],
    stage: { zone: 'pokapoka', at: [0, 10], face: 0, host: 'sonchou',
      cast: { sonchou: { at: [0, 3], face: 'mike' }, sakanaya: { at: [-1.6, 3.4], face: 'mike' },
        king_npc: { at: [-3.4, 6.5], hidden: true, face: 'mike' }, piero_npc: { at: [3.3, 6], hidden: true, face: 'mike' }, nyahaha_ou: { at: [1.8, 7.4], hidden: true, face: 'mike' },
        kurone: { at: [-4.8, 4], hidden: true, face: 'mike' }, mazoku_yukyu: { at: [4.8, 4], hidden: true, face: 'maou' }, chaya: { at: [-1.8, 7.2], hidden: true, face: 'mike' } },
      points: { sky: [-30, 30, 120] }, wide: { pos: [-3.2, 2.2, -3], look: [0, 0.8, 4] } },
    lines: [
      ['n', '影をはらったあと。村の広場に、見覚えのある顔が、次々と集まってきた。', { cam: 'wide', dur: 7, fx: 'dawn' }],
      ['king_npc', 'よう、勇者。……ずいぶん探したぞ。', { enter: 'king_npc', move: { king_npc: [-2.4, 4.6] }, f: 'smile', look: { all: 'king_npc' } }],
      ['mike', 'キングネズミ！', { f: 'joy', g: 'surprise' }],
      ['king_npc', '魚……分けてやるよ。', { f: 'smile', g: 'give', hold: { king_npc: 'fish' } }],
      ['mike', 'え……でも、それ、大事な冬のごはんじゃ……。', { f: 'surprise' }],
      ['king_npc', '俺にとっては大事なんだ！　……あのとき、お前が分けてくれた魚がな。', { f: 'cry', g: 'fist', cam: 'king_npc', close: true }],
      ['piero_npc', 'ぼくも来たよ！　世界中に笑いを届けるショーの準備は、ばっちりさ！', { enter: 'piero_npc', f: 'joy', g: 'cheer', move: { piero_npc: [2.6, 4.6] } }],
      ['nyahaha_ou', 'わが国の民も、みな力を貸すぞ！　……ぶはははは！', { enter: 'nyahaha_ou', f: 'joy', g: 'laugh' }],
      ['kurone', '谷のみんなも、クロの仲間なら力になるってさ。', { enter: 'kurone', f: 'gentle', g: 'nod', r: { kuro: 'surprise' } }],
      ['mazoku_yukyu', '魔王さまー！　魔王軍一同、有給を返上して参りました！', { enter: 'mazoku_yukyu', f: 'joy', g: 'cheer' }],
      ['maou', '……お前たち。', { f: 'surprise', cam: 'maou', close: true, later: [1.5, { r: { maou: 'shy' } }] }],
      ['chaya', '街道の仲間も来たよ！　お茶も持ってきた！　ハチとブチの笛と太鼓もいっしょだ！', { enter: 'chaya', f: 'smile', g: 'wave' }],
      ['sonchou', 'ミケ。……お前が旅で結んできたつながりが、みんなをここへ連れてきたんじゃよ。', { f: 'gentle', g: 'handChest' }],
      ['mike', '……みんな……！', { f: 'cry' }],
      ['kuro', '……ミケ。これが、お前の力だ。', { f: 'smile', g: 'nod' }],
      ['n', '猫たちの心が重なると、遠くのにゃんだーの樹が、ほんの少し、光を取り戻した。', { fx: ['voices', 'light:sky'], cam: 'wide', dur: 8, look: { all: 'sky' } }],
      ['tama', '……樹が……わらった。', { f: 'joy', g: 'lookUp' }],
      { bond: ['all', null, 20] },
      ['mike', '行こう、世界の果てへ！　みんなの力で、コドクを止めるんだ！', { f: 'serious', g: 'fist', r: { all: ['joy', 'cheer'] } }],
    ] },
  c8_03: { title: '世界の果て', cast: ['e:kagejuu', 'e:utsuro'], bgm: 'dark',
    stage: { zone: 'world_end', at: [0, 20], face: 0, cast: { 'e:kagejuu': { at: [-2.6, 6], hidden: true }, 'e:utsuro': { at: [2.4, 6.6], hidden: true } }, points: { edge: [0, 2, 60] } },
    lines: [
      ['n', '樹の根もとの東から、地面を這う太い根をたどって、どこまでも歩いた。……やがて地面はとぎれ、根は、奈落に浮かぶ石の道を支えていた。', { cam: 'wide', dur: 8 }],
      ['n', '世界の果ては、音も、色もない、しずかな場所だった。', { cam: 'look:edge', dur: 7, look: { all: 'edge' } }],
      ['shiro', '……ここ、さみしい……。', { f: 'worry' }],
      ['maou', '余が、ずっとひとりでいた場所に、よく似ている。', { f: 'sad' }],
      ['tama', '……だいじょうぶ。……今は、みんないる。', { f: 'smile', g: 'nod', to: 'maou', r: { maou: 'shy' } }],
      ['n', '闇の中から、コドクの獣たちが現れた！', { enter: ['e:kagejuu', 'e:utsuro'], cam: 'wide', stance: { all: 'ready' } }],
    ] },
  c8_04: { title: '一人じゃない', cast: ['e:kodoku'], bgm: 'boss',
    stage: { zone: 'world_end', at: [0, -21], face: 0, cast: { 'e:kodoku': { at: [0, 9.5] } } },
    lines: [
      ['e:kodoku', '……来たか。たった五匹で。', { cam: 'foe:e:kodoku', dur: 6 }],
      ['mike', '五匹じゃない！', { f: 'serious', g: 'fist' }],
      ['e:kodoku', '……？'],
      ['mike', 'ぼくたちの後ろには、旅で出会った、みんながいる！', { f: 'serious', g: 'point' }],
      ['e:kodoku', 'つながりなど、いずれ消える。……だから私は、生まれたのだ。'],
      ['kuro', '……消えない。……あいつらは、今も俺の中にいる。', { f: 'serious', stance: { kuro: 'ready' } }],
      ['e:kodoku', 'ならば、試してみるがいい。孤独、絶望、疑心、思い出消去……すべての孤独を、受けてみろ。', { shake: 0.6, fx: 'darkness' }],
      ['n', '（最終決戦：コドクが最後の姿になると、世界中の猫たちの声が届く。友情ゲージが満ちたら「にゃんこオールスターズ」を使おう！　Cキー）', { cam: 'wide', dur: 6, stance: { all: 'ready' } }],
    ] },
  c8_05: { title: 'みんなのにゃん力', cast: ['e:kodoku'], bgm: 'hope',
    stage: { zone: 'world_end', at: [0, -21], face: 0, cast: { 'e:kodoku': { at: [0, 9.5] } }, points: { sky: [0, 30, 60] } },
    lines: [
      ['n', '光に包まれて、コドクの黒い体が、ほどけていく。', { fx: ['dawn', 'light:e:kodoku'], cam: 'foe:e:kodoku', dur: 7 }],
      ['e:kodoku', '……あたたかい……。これが……つながり、か……。'],
      ['e:kodoku', '……私も……本当は……ひとりは、いやだった……。'],
      ['mike', '……じゃあ、きみもおいでよ。', { f: 'gentle', g: 'offer' }],
      ['e:kodoku', '……ふ……。……ありがとう。', { defeat: 'e:kodoku' }],
      ['n', '孤独は、光の粒になって、空へ昇っていった。', { fx: 'voices', cam: 'wide', dur: 6 }],
      ['n', 'そして——', { fx: 'revive', cam: 'look:sky', dur: 8, look: { all: 'sky' } }],
      ['tama', '……樹が……！', { f: 'joy', g: 'cheer' }],
      ['n', '世界の果てまで届くほどの光。にゃんだーの樹に、たくさんの感情の実が実った。笑い、友情、思い出、優しさ——。', { cam: 'wide', dur: 8 }],
      ['shiro', '……きれい……。', { f: 'cry', g: 'bothChest' }],
      ['maou', '……友達って、いいものだな。', { f: 'gentle', cam: 'maou', close: true }],
      ['kuro', '……ああ。', { f: 'smile', g: 'nod' }],
      ['tama', '……ぼく、樹にならなくて……よかったの？', { f: 'worry', g: 'tilt', to: 'mike' }],
      ['mike', '当たり前じゃん！　タマは、ぼくたちと一緒に遊ぶんだから！', { f: 'joy', g: 'hop' }],
      ['tama', '……うん！', { f: 'joy', g: 'cheer' }],
      ['mike', 'ぼくたちは——', { f: 'serious', g: 'fist', cam: 'mike', close: true }],
      ['n', '「ずっと仲間だ！」', 'みんな', { r: { all: ['joy', 'cheer'] }, cam: 'wide', dur: 7, fx: 'laugh' }],
    ] },

  // ================= エピローグ　それから =================
  c9_01: { title: 'それから', bgm: 'village', extra: ['sonchou', 'sakanaya'],
    stage: { zone: 'pokapoka', at: [12, 1.5], face: 90,
      cast: { mike: { at: [0.4, 3.6], face: [0, 0], item: 'fish' }, kuro: { at: [-2.6, 1.2], face: 'mike' }, shiro: { at: [-2.4, -0.6], face: 'mike' }, tama: { at: [-3.6, 0.2], face: 'mike' }, maou: { at: [-1.4, -1.6], face: 'mike' },
        sonchou: { at: [-1.2, 1.8], face: 'mike' }, sakanaya: { at: [3, 1.5], hidden: true, face: 'mike' } },
      wide: { pos: [-4.6, 1.8, -1.4], look: [0, 0.8, 2.6] } },
    lines: [
      ['n', '——それから、数年後。', { cam: 'wide', dur: 7 }],
      ['n', 'マオウは、魔王城を改装して、世界一の猫カフェを開いた。', { cam: 'maou', dur: 6 }],
      ['maou', 'いらっしゃいませ。……ふん、余の淹れる紅茶は、世界一だぞ。', { f: 'smug', g: 'bow' }],
      ['n', 'クロは、冒険者ギルドを作り、ひとりぼっちの冒険者たちに、仲間を紹介している。', { cam: 'kuro', dur: 6 }],
      ['kuro', '……一人で行くな。仲間を連れていけ。……それが、ギルドの決まりだ。', { f: 'smile', g: 'nod' }],
      ['n', 'シロは、魔法学校の校長になった。', { cam: 'shiro', dur: 6 }],
      ['shiro', '失敗を怖がらないこと！　それが、天才への第一歩よ！', { f: 'smug', g: 'raise' }],
      ['n', 'タマは、にゃんだーの樹の管理人として、樹の上で、のんびり暮らしている。……樹が元気になったので、もう眠りすぎることはない。ただ、昼寝が好きなだけだ。', { cam: 'tama', dur: 7 }],
      ['tama', '……きょうも、いいてんき……すぴー。', { f: 'sleepy', stance: { tama: 'sleep' } }],
      ['n', 'そして、ミケは——', { cam: 'mike', dur: 5 }],
      ['mike', 'いらっしゃい、いらっしゃい！　今日は、いい魚が入ってるよー！', { f: 'joy', g: 'wave' }],
      ['sonchou', 'なんで勇者が魚屋なんじゃ。', { f: 'serious', g: 'shake' }],
      ['mike', '魚が好きだから！', { f: 'joy', g: 'cheer', r: { all: 'smile' } }],
      ['sakanaya', 'まったく……うちのライバルになるとはねえ！', { enter: 'sakanaya', f: 'smile', g: 'laugh' }],
      ['n', 'ぽかぽか村は、今日も、ぽかぽかだ。', { cam: 'wide', dur: 8, fx: 'sparkle:mike' }],
    ] },

  // ================= おまけ　ねこ神の夢 =================
  c10_01: { title: '夢の入口', cast: ['e:sakana'], bgm: 'field',
    stage: { zone: 'dream', at: [0, 20], face: 0, cast: { 'e:sakana': { at: [0, 5], hidden: true } } },
    lines: [
      ['n', '猫神社の鳥居の奥。気がつくと、一行は、お菓子と魚の浮かぶふしぎな夢の中にいた。', { cam: 'wide', dur: 7 }],
      ['mike', 'わーっ、魚が空を泳いでる！', { f: 'joy', g: 'cheer' }],
      ['shiro', '……夢、よね？', { f: 'worry' }],
      ['kuro', '……頬をつねってみろ。', { f: 'serious' }],
      ['shiro', 'いたっ！　……なんで、わたしの頬なのよ！', { f: 'angry', g: 'fist', to: 'kuro' }],
      ['e:sakana', 'いいかい、そもそも魚というのはだね……', { enter: 'e:sakana' }],
      ['maou', '……魚がしゃべったぞ。', { f: 'surprise', stance: { all: 'ready' } }],
    ] },
  c10_02: { title: 'へんてこ回廊', cast: ['e:nisemike', 'e:kuroPlush', 'e:tamas'], bgm: 'field',
    stage: { zone: 'dream', at: [0, 6], face: 0, cast: { 'e:nisemike': { at: [-2.6, 4] }, 'e:kuroPlush': { at: [2.6, 4.4] }, 'e:tamas': { at: [0, 7] } } },
    lines: [
      ['e:nisemike', 'ぼくが、本物のミケだよ！'],
      ['mike', 'ぼくが本物だよ！？', { f: 'surprise', g: 'point' }],
      ['kuro', '……偽物のほうが、しっぽの模様が逆だ。', { f: 'serious' }],
      ['e:kuroPlush', '……めんどうだ（録音）。'],
      ['kuro', '……俺は、そんなに言ってない。', { f: 'angry' }],
      ['shiro', '言ってるわよ。', { f: 'smug', r: { mike: 'joy', maou: 'smile' } }],
      ['e:tamas', '「「「すやすや……」」」'],
      ['tama', '……ぼくが、いっぱい……。', { f: 'surprise' }],
      ['shiro', 'どれが本物のタマ！？', { f: 'surprise', g: 'recoil', stance: { all: 'ready' } }],
    ] },
  c10_03: { title: 'ねこ神', cast: ['e:nekogami'], bgm: 'boss',
    stage: { zone: 'dream', at: [0, -15], face: 0, cast: { 'e:nekogami': { at: [0, 9] } } },
    lines: [
      ['e:nekogami', 'よくぞここまで来た。', { cam: 'foe:e:nekogami', dur: 6 }],
      ['mike', '誰？', { f: 'neutral', g: 'tilt' }],
      ['e:nekogami', 'この世界を作った者だ。'],
      ['mike', 'じゃあ、世界救ってよ。', { f: 'serious' }],
      ['e:nekogami', 'それは面倒なので、お前に任せた。'],
      ['kuro', '……面倒、だと。', { f: 'angry', stance: { kuro: 'ready' } }],
      ['shiro', 'クロの親戚！？', { f: 'surprise', g: 'point' }],
      ['e:nekogami', '……まあ、ここまで来たごほうびだ。少し、遊んでやろう。', { shake: 0.4, stance: { all: 'ready' } }],
    ] },
  c10_04: { title: '夢のおわり', cast: ['e:nekogami'], bgm: 'hope',
    stage: { zone: 'dream', at: [0, -15], face: 0, cast: { 'e:nekogami': { at: [0, 9] } } },
    lines: [
      ['e:nekogami', '……ふう。お前たち、強くなったな。'],
      ['e:nekogami', '世界を救ったのは、私ではない。お前たちと、お前たちがつないだ、たくさんの心だ。……だから、任せて正解だった。'],
      ['mike', '……めんどうだっただけでしょ？', { f: 'smug' }],
      ['e:nekogami', '……ばれたか。', { r: { all: ['joy', 'laugh'] } }],
      ['n', 'ねこ神が笑うと、夢は、やさしい光にほどけていった。', { fx: 'light', cam: 'wide', dur: 7 }],
    ] },

  // ================= 友情の特別イベント（友情Lv4） =================
  b_kuro_mike: { title: '屋根の上の星', bgm: 'sad',
    stage: { zone: 'pokapoka', at: [-22, -2], face: 0, bg: 'night', party: ['mike', 'kuro'], cast: { mike: { at: [-0.6, 0] }, kuro: { at: [0.6, 0.2] } }, points: { sky: [0, 20, 30] } },
    lines: [
      ['n', '夜。ミケの家の前で、二匹は星を見上げていた。', { cam: 'wide', dur: 6, look: { all: 'sky' } }],
      ['mike', 'ねえクロ。クロが追いかけてた流れ星って、どんなだった？', { f: 'smile', to: 'kuro' }],
      ['kuro', '……きれいだった。……でも、落ちていくのを見て、思った。……ひとりで落ちていくのは、さみしいだろうなって。', { f: 'gentle', g: 'lookUp' }],
      ['mike', 'だから、追いかけたの？', { f: 'neutral', g: 'tilt' }],
      ['kuro', '……ああ。……そしたら、お前がいた。', { f: 'shy', g: 'turnAway' }],
      ['mike', 'へへっ。じゃあ、あの流れ星に、お礼言わなきゃ！', { f: 'joy', g: 'wave', look: { mike: 'sky' } }],
      ['kuro', '……ふっ。……面倒なやつ。', { f: 'smile' }],
    ] },
  b_mike_shiro: { title: '最後の焼き魚',
    stage: { zone: 'pokapoka', at: [10, 12], face: 0, party: ['mike', 'shiro'], cast: { mike: { at: [-0.7, 0], item: 'fish' }, shiro: { at: [0.7, 0.1] } } },
    lines: [
      ['shiro', 'ちょっとミケ！　その焼き魚、最後の一匹でしょ！　わたしのよ！', { f: 'angry', g: 'point', to: 'mike' }],
      ['mike', 'ぼくが先に見つけたもん！', { f: 'pout', g: 'pout' }],
      ['shiro', 'じゃあ、魔法で二匹に増やしてあげる！　……ダブル！', { f: 'smug', g: 'raise', fx: 'spell:shiro', later: [1.2, { fx: 'poof:shiro' }] }],
      ['n', '……魚は増えなかった。かわりに、シロの毛が爆発した。', { cam: 'shiro', close: true }],
      ['mike', 'ぷっ……あははは！', { f: 'joy', g: 'laugh' }],
      ['shiro', 'わ、笑わないでよ！　……ふふっ、あははは！', { f: 'joy', g: 'laugh' }],
      ['mike', 'はい、半分こ！', { f: 'joy', g: 'give', hold: { mike: null, shiro: 'fish' } }],
      ['shiro', '……最初からそうしなさいよ。……ありがと。', { f: 'shy', g: 'turnAway' }],
    ] },
  b_mike_tama: { title: 'ミケにいちゃん', bgm: 'sad',
    stage: { zone: 'hill', at: [-11, 9], face: 0, bg: 'night', party: ['mike', 'tama'], cast: { mike: { at: [-0.5, 0], stance: 'kneel' }, tama: { at: [0.6, 0.1], stance: 'kneel' } }, points: { sky: [0, 14, 30] } },
    lines: [
      ['tama', '……ミケにいちゃん。……おとうさんと、おかあさんって、どんなの？', { f: 'sleepy', g: 'tilt', to: 'mike' }],
      ['mike', '……えっ。', { f: 'surprise' }],
      ['mike', '……あったかくて、いつも笑ってて……ぼくが魚を盗ると、すっごく怒った。', { f: 'gentle', g: 'lookUp', look: { mike: 'sky' } }],
      ['mike', '……へへ。……もう、いないんだけどね。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……ミケにいちゃん、さみしい？', { f: 'worry' }],
      ['mike', '……ちょっとだけ。でも、今はタマがいるから、へっちゃら！', { f: 'smile', g: 'nod' }],
      ['tama', '……えへへ。……ぼくも。', { f: 'gentle', stance: { tama: 'sleep' } }],
      ['n', 'タマは、ミケの肩にもたれて、すやすやと眠ってしまった。', { cam: 'wide', dur: 7 }],
    ] },
  b_maou_mike: { title: 'はじめてのかくれんぼ',
    stage: { zone: 'demon_land', at: [10, 20], face: 0, party: ['mike', 'maou'], cast: { mike: { at: [-0.8, 0] }, maou: { at: [0.8, 0.2] } } },
    lines: [
      ['maou', '勇者よ。……「かくれんぼ」とやらを、教えるがよい。', { f: 'smug', g: 'armsCrossed', to: 'mike' }],
      ['mike', 'いいよ！　ぼくが鬼ね！　いーち、にーい……', { f: 'joy', g: 'hop' }],
      ['n', '……十数えて振り返ると、マオウは、ぜんぜん隠れていなかった。', { cam: 'maou', close: true }],
      ['mike', '……マオウ、見えてるよ？', { f: 'neutral', g: 'tilt' }],
      ['maou', '……余は、見つけてほしかったのだ。……ずっと、誰かに。', { f: 'shy', g: 'turnAway' }],
      ['mike', '……じゃあ、見つけた！', { f: 'joy', g: 'point' }],
      ['maou', '……ふん。……楽しいではないか、かくれんぼ。', { f: 'smile' }],
    ] },
  b_kuro_shiro: { title: '失敗の記録',
    stage: { zone: 'nyahaha', at: [-22, 18], face: 90, party: ['kuro', 'shiro'], cast: { kuro: { at: [-0.7, 0], item: 'book' }, shiro: { at: [0.7, 0.1] } } },
    lines: [
      ['shiro', '……影の四剣の記録、読ませてもらったわ。失敗の記録も、ちゃんと全部書いてあるのね。', { f: 'serious', to: 'kuro' }],
      ['kuro', '……ハヤテの方針だ。「失敗を書かないやつは、同じ失敗をする」。', { f: 'serious' }],
      ['shiro', '……わたし、失敗を書くのが怖かった。書いたら、本当に失敗したことになる気がして。', { f: 'sad', g: 'lookDown' }],
      ['kuro', '……失敗してもいい。お前が前に出すぎたら、俺が前に立つ。', { f: 'serious', g: 'nod' }],
      ['shiro', '……クロって、真面目よね。', { f: 'smile' }],
      ['kuro', '……お前もだ。', { f: 'smile', r: { shiro: 'shy' } }],
    ] },
  b_kuro_tama: { title: 'ひだまりの番',
    stage: { zone: 'woods', at: [4, -18], face: 0, party: ['kuro', 'tama'], cast: { tama: { at: [0.5, 0.6], stance: 'sleep' }, kuro: { at: [-0.8, 0], stance: 'armsCrossed' } } },
    lines: [
      ['n', '昼下がり。タマがひだまりで眠るそばで、クロがじっと座っていた。', { cam: 'wide', dur: 7 }],
      ['tama', '……クロ……ずっと、そこにいるの……？', { f: 'sleepy' }],
      ['kuro', '……お前が寝ている間に、何かあったら困る。', { f: 'serious', g: 'turnAway' }],
      ['tama', '……クロは、やさしいね。', { f: 'gentle' }],
      ['kuro', '……別に。……面倒なだけだ。', { f: 'shy' }],
      ['tama', '……えへへ。……おやすみ、クロ。', { f: 'sleepy' }],
      ['kuro', '……ああ。……おやすみ。', { f: 'gentle', cam: 'kuro', close: true }],
    ] },
  b_shiro_tama: { title: 'まくらの芽',
    stage: { zone: 'road_rest', at: [-6, 4], face: 0, party: ['shiro', 'tama'], cast: { shiro: { at: [-0.6, 0] }, tama: { at: [0.6, 0.2] } } },
    lines: [
      ['shiro', 'ほら、タマ。頭の芽、寝ぐせでぺしゃんこよ。直してあげる。', { f: 'gentle', g: 'reach', to: 'tama' }],
      ['tama', '……ありがと、シロ。', { f: 'smile' }],
      ['shiro', '……ねえタマ。あなたが樹から生まれたとか、そういうの……わたし、ちょっと怖いの。', { f: 'worry' }],
      ['tama', '……シロ、こわいの？', { f: 'worry', g: 'tilt' }],
      ['shiro', '……あなたが、どこか遠くに行っちゃいそうで。', { f: 'sad', g: 'lookDown' }],
      ['tama', '……どこにもいかないよ。……シロのとなりで、ねる。', { f: 'gentle', g: 'nod' }],
      ['shiro', '……もう。……それなら、いいわ。', { f: 'shy', g: 'handChest' }],
    ] },
  b_kuro_maou: { title: '……',
    stage: { zone: 'valley', at: [-10, 14], face: 0, party: ['kuro', 'maou'], cast: { kuro: { at: [-0.7, 0], stance: 'armsCrossed' }, maou: { at: [0.7, 0.1], stance: 'armsCrossed' } } },
    lines: [
      ['kuro', '……。', { f: 'serious' }],
      ['maou', '……。', { f: 'serious' }],
      ['kuro', '……いい天気だ。', { f: 'serious', g: 'lookUp' }],
      ['maou', '……うむ。', { f: 'serious', g: 'nod' }],
      ['n', '……それから一時間、二匹は並んで空を見ていた。', { cam: 'wide', dur: 7 }],
      ['maou', '……悪くない時間だった。', { f: 'smile' }],
      ['kuro', '……ああ。', { f: 'smile' }],
    ] },
  b_maou_shiro: { title: '実験台',
    stage: { zone: 'road_rest', at: [4, 6], face: 0, party: ['shiro', 'maou'], cast: { shiro: { at: [-0.7, 0] }, maou: { at: [0.9, 0.3] } } },
    lines: [
      ['shiro', 'マオウ！　新しい魔法ができたの。ちょっと実験台になって！', { f: 'joy', g: 'point', to: 'maou' }],
      ['maou', 'ことわる。', { f: 'serious', g: 'turnAway' }],
      ['shiro', '毛並みがつやつやになる魔法よ？', { f: 'smug' }],
      ['maou', '……少しだけならよい。', { f: 'shy' }],
      ['n', '……マオウの毛並みは、つやつやのピンク色になった。', { fx: ['spell:shiro', 'sparkle:maou'], cam: 'maou', close: true }],
      ['maou', '…………。', { f: 'angry' }],
      ['shiro', '……か、かわいいわよ？', { f: 'shy', g: 'shrug' }],
      ['maou', '……ふん。……悪くない。', { f: 'smug', r: { shiro: ['joy', 'laugh'] } }],
    ] },
  b_maou_tama: { title: 'おひるね同盟',
    stage: { zone: 'hill', at: [-12, 10], face: 0, party: ['tama', 'maou'], cast: { tama: { at: [-0.4, 0.4], stance: 'sleep' }, maou: { at: [0.8, 0.2], stance: 'kneel' } } },
    lines: [
      ['tama', '……マオウも……いっしょに、おひるね……する？', { f: 'sleepy', to: 'maou' }],
      ['maou', '……余は魔王だ。昼寝など——', { f: 'smug' }],
      ['tama', '……ふかふかだよ。', { f: 'smile' }],
      ['maou', '……少しだけならな。', { f: 'shy', stance: { maou: 'sleep' } }],
      ['n', '……一時間後。二匹は仲よく、ぐっすり眠っていた。', { cam: 'wide', dur: 7 }],
      ['maou', '……すぴー……。', { f: 'sleepy' }],
    ] },
});

// 第五章〜のあらすじ
const RECAP_2 = {
  c5_01: 'くろねこ谷の北、森に埋もれた古代遺跡へ。タマは、なぜか懐かしそうにしている。',
  c5_02: '壁画には、樹を抱いて眠る巨大な猫と、樹のまわりで手をつなぐ四匹の猫。古代文字には「つながりが絶えるとき、樹は最後のにゃんこを生む」と記されていた。',
  c5_03: '誰にも開けられない封印の扉は、タマがふれると開いた。扉に浮かんだ文字は「最後のにゃんこ」。「……ぼく？」',
  c5_04: '遺跡の守護神は語る。樹は猫たちの心のつながりを糧に生き、枯れかけると樹を救う子「最後のにゃんこ」を生む。タマがいつも眠っていたのは、弱った樹と心がつながっていたからだった。樹の根は世界じゅうの地下をめぐり、その先は、誰の声も届かない「世界の果て」に行きつくという。樹を枯らしているのは魔王ではなく、世界に広がった孤独だった。樹の心臓はいにしえの猫たちに封じられ、その扉も最後のにゃんこにしか開けられないという。魔王も樹の根の「何か」を知っているらしい。',
  c6_01: '魔王領は、有給をほしがる兵や健康診断の係がいる、妙にコミカルな場所だった。魔王は城でひとり、猫じゃらしで遊んでいるらしい。',
  c6_02: '魔王城の健康診断で、ミケは「魚の食べすぎ」と言われてしまう。',
  c6_03: '玉座の間で、魔王マオウはひとりで猫じゃらしにじゃれていた。「余はこの世界を滅ぼす者だ」。',
  c6_04: 'マオウが世界を滅ぼそうとした理由は「余と遊んでくれる者がいない」から。魔王もまた孤独だった。「世界を滅ぼす」と言ったのも、誰かに城まで来てほしかったからだった。クロの仲間を襲ったのも魔王軍ではなく、樹の根元に巣くう黒い何かだと分かる。マオウは「退屈しのぎ」に一行へ加わる。笑いの実は王国へ返された。',
  c7_01: 'にゃんだーの樹は、灰色の葉を落とし続けていた。旅の始まりの夜、この樹に残っていた最後の友情の実が、熟す前に落ちかけていた。取ろうと手を伸ばしたクロは足を滑らせ、落ちながらとっさに実をつかんだ。ぶら下がったクロの重さで大きくしなった枝がいきおいよくはね返り、そのはずみで実の軸が折れて、クロは実ごと空へ放り出された。夜に光る樹の実が、夜空に尾を引いて飛んでいく——ミケが見たあの流れ星は、実を守ろうとしたクロだったのだ。実は割れてしまったが、そのおかげで二匹は出会えた。根もとの封印の扉は、マオウにもクロにも開けられなかった。樹を守るための封印が、中に入りこんだものまで隠していたのだ。タマがふれると扉は開き、奥から黒いかけらがあふれ出した。',
  c7_02: '樹の根の下の地下は、誰の声も届かないほど静かだった。',
  c7_03: '樹の心臓の前で、世界に広がった孤独そのもの「コドク」と対面する。コドクは、一行の心の奥の孤独を言い当て、黒影洞窟でクロの仲間を闇に沈めたのは自分だと告げた。クロだけを残したのは、ひとりにするため。樹を調べていたクロの心に「ひとりでいい」とささやいていたのも、コドクだった。',
  c7_04: 'コドクは倒しても消えない。タマは「ぼくが樹になればいいんだよ」と言う。ミケは「仲間を犠牲にして世界を救うなんて、勇者じゃない！」と拒み、ずっと笑ってごまかしてきたさみしさを打ち明けて「強いから助けるんじゃない。仲間だから助けるんだ」と言った。クロも、失敗を受け入れたシロも、マオウも、タマを守ると決めた。互いを呼ぶ声で幻を打ち破るが、コドクは樹の根の行きつく先、誰の声も届かない「世界の果て」へ逃れた。樹とつながるタマには、根もとの東からのびる太い根をたどれば、そこへ行けるとわかった。世界中の孤独が流れつくその場所で戦うには、五匹だけの声では足りない。',
  c8_01: '村に戻ると、影の獣が村を襲っていた。魚屋のおばちゃんは「あんたに食べさせる魚くらい、いくらでも焼いてやるよ！」と言った。',
  c8_02: '村の広場に、旅で出会った猫たちが集まる。キングネズミは「魚……分けてやるよ。俺にとっては大事なんだ！」と魚を差し出した。小さな親切や友情が、樹をほんの少し光らせる。',
  c8_03: '樹の根もとの東から、地面を這う太い根をたどって、音も色もない世界の果てへ。根は、奈落に浮かぶ石の道を支えていた。',
  c8_04: 'コドクとの最後の戦い。「五匹じゃない！　ぼくたちの後ろには、旅で出会ったみんながいる！」',
  c8_05: '世界中の「つながり」が、コドクを光に変えた。にゃんだーの樹がよみがえり、世界に笑い・友情・思い出・優しさが戻る。「ぼくたちは――」「ずっと仲間だ！」',
  c9_01: '数年後。マオウは猫カフェ、クロは冒険者ギルド、シロは魔法学校、タマは樹の管理人。そしてミケは、魚屋になった。「なんで勇者が魚屋なんじゃ」「魚が好きだから！」',
  c10_01: '猫神社の奥の、お菓子と魚の浮かぶ夢の世界へ。',
  c10_02: 'ミケの偽物、クロのぬいぐるみ、100匹のタマ。へんてこな夢はまだ続く。',
  c10_03: '夢の奥で待っていたのは、この世界を作った「ねこ神」。世界を救うのは「面倒なのでお前に任せた」らしい。',
  c10_04: 'ねこ神は、世界を救ったのは一行と、一行がつないだたくさんの心だと笑った。',
};

// ------------------------------------------------------------
//  物語の進行
// ------------------------------------------------------------
const STORY = [
  { title: '第一章　勇者、拾われる', steps: [
    { t: 'scene', id: 'c1_01', g: '魚どろぼう' },
    { t: 'scene', id: 'c1_02', g: '流れ星の夜' },
    { t: 'field', zone: 'hill', at: [0, 1], start: ['pokapoka', -17, -4], near: ['pokapoka', 'hill'], yaw: 0.6, scene: 'c1_03', g: '流れ星の落ちた、村はずれの丘へ行く' },
    { t: 'field', zone: 'pokapoka', at: [0, -9], scene: 'c1_04', g: '村に戻って、村長にクロのことを話す' },
    { t: 'field', zone: 'forest_in', at: [-2, -9], scene: 'c1_05', battle: '1-1', g: '村の東の、ほしふる森へ' },
    { t: 'field', zone: 'forest_deep', at: [-4, -5], scene: 'c1_06', battle: '1-2', g: 'ほしふる森の奥へ進む' },
    { t: 'field', zone: 'rat_nest', at: [0, -7], scene: 'c1_07', battle: '1-3', after: 'c1_08', g: '森の北、ネズミの王国をたずねる' },
    { t: 'field', zone: 'pokapoka', at: [0, 5], scene: 'c1_09', g: '村に帰って、村長に報告する' },
    { t: 'reward', niboshi: 300, g: '第一章 おしまい' },
  ] },
  { title: '第二章　にゃんこ大集合', steps: [
    { t: 'scene', id: 'c2_01', g: 'ミャオ街道へ' },
    { t: 'field', zone: 'road1', at: [1, 28], start: ['road1', -8, 42], near: ['road1', 'road_rest'], scene: 'c2_01b', g: '街道を北へ進む' },
    { t: 'field', zone: 'road_rest', at: [0, 5], scene: 'c2_02', battle: '2-1', after: 'c2_02b', g: '街道の宿場へ' },
    { t: 'field', zone: 'woods', at: [4, -13], scene: 'c2_03', battle: '2-2', after: 'c2_03b', g: '宿場の東、まどろみの林で眠っている子をさがす' },
    { t: 'scene', id: 'c2_03c', g: '宿場の夜' },
    { t: 'scene', id: 'c2_03d', g: 'いなくなったシロ' },
    { t: 'field', zone: 'road1', at: [8, -2], start: ['road_rest', 4, 6], near: ['road_rest', 'road1'], scene: 'c2_03e', battle: '2-3', after: 'c2_03f', g: '宿場の南、街道の風車の畑でシロをさがす' },
    { t: 'field', zone: 'road2', at: [0, -4], scene: 'c2_04', battle: '2-4', after: 'c2_05', g: '宿場の北、関所あとを越える' },
    { t: 'reward', niboshi: 400, g: '第二章 おしまい' },
  ] },
  { title: '第三章　笑わない街', steps: [
    { t: 'field', zone: 'nyahaha', at: [0, 22], scene: 'c3_01', g: 'ニャハハ王国に入る' },
    { t: 'field', zone: 'castle', at: [0, -5], scene: 'c3_02', g: '町の北、ニャハハ城で王さまに会う' },
    { t: 'field', zone: 'tower', at: [10.5, 12.5], scene: 'c3_03', battle: '3-1', g: '町の北東、笑顔の塔へ' },
    { t: 'field', zone: 'tower_3f', at: [10.5, 12.5], battle: '3-2', g: '楽屋を抜けて、三階の空中ブランコの間へ' },
    { t: 'field', zone: 'tower_top', at: [10.5, 6], scene: 'c3_04', battle: '3-3', after: 'c3_05', g: '塔の最上階、大舞台へ' },
    { t: 'scene', id: 'c3_06', g: '笑顔のかけら' },
    { t: 'reward', niboshi: 500, g: '第三章 おしまい' },
  ] },
  { title: '第四章　黒猫の過去', steps: [
    { t: 'field', zone: 'valley', at: [-25, 6], scene: 'c4_01', g: '城下町の東、くろねこ谷へ' },
    { t: 'field', zone: 'valley', at: [-16, -8], scene: 'c4_02', battle: '4-1', g: '谷の丘の上の墓標へ' },
    { t: 'field', zone: 'cave', at: [14.5, 17.5], scene: 'c4_03', battle: '4-2', g: '谷の北、黒影洞窟へ' },
    { t: 'field', zone: 'cave_deep', at: [14.5, 5.5], scene: 'c4_04', battle: '4-3', after: 'c4_05', g: '地底湖を越えて、洞窟の最奥へ' },
    { t: 'reward', niboshi: 600, g: '第四章 おしまい' },
  ] },
  { title: '第五章　眠れる子猫', steps: [
    { t: 'field', zone: 'ruins_out', at: [-6, 20], scene: 'c5_01', battle: '5-1', g: '谷の北西、古代遺跡へ' },
    { t: 'field', zone: 'ruins_in', at: [0, 14], scene: 'c5_02', battle: '5-2', g: '遺跡の奥、壁画の回廊を調べる' },
    { t: 'field', zone: 'ruins_in', at: [0, -25], scene: 'c5_03', battle: '5-3', after: 'c5_04', g: '回廊の奥、封印の扉へ' },
    { t: 'reward', niboshi: 700, g: '第五章 おしまい' },
  ] },
  { title: '第六章　魔王城へ', steps: [
    { t: 'field', zone: 'demon_land', at: [-2, 24], scene: 'c6_01', battle: '6-1', g: '遺跡の東、魔王領へ' },
    { t: 'field', zone: 'demon_castle', at: [11.5, 16], scene: 'c6_02', battle: '6-2', g: '魔王城に入る' },
    { t: 'field', zone: 'demon_throne', at: [11.5, 6], scene: 'c6_03', battle: '6-3', after: 'c6_04', g: '回廊を抜けて、三階の玉座の間へ' },
    { t: 'reward', niboshi: 800, g: '第六章 おしまい' },
  ] },
  { title: '第七章　最後のにゃんこ', steps: [
    { t: 'field', zone: 'tree_root', at: [0, -20], start: ['tree_root', 0, -38], near: ['tree_root', 'tree_under', 'hill'], scene: 'c7_01', battle: '7-1', g: 'にゃんだーの樹の根もとへ' },
    { t: 'field', zone: 'tree_under', at: [0, -24], scene: 'c7_02', battle: '7-2', g: '封印の扉の奥、樹の地下へ' },
    { t: 'field', zone: 'tree_under', at: [0, 14], scene: 'c7_03', battle: '7-3', after: 'c7_04', g: '地下の奥、樹の心臓へ' },
    { t: 'reward', niboshi: 900, g: '第七章 おしまい' },
  ] },
  { title: '第八章　みんなのにゃん力', steps: [
    { t: 'scene', id: 'c8_01', g: 'ぽかぽか村の危機' },
    { t: 'battle', stage: '8-1', after: 'c8_02', g: '村を守る' },
    { t: 'field', zone: 'world_end', at: [0, 20], start: ['tree_root', 30, 14], near: ['tree_root', 'world_end'], scene: 'c8_03', battle: '8-2', g: '樹の根もとの東から、太い根をたどって世界の果てへ' },
    { t: 'field', zone: 'world_end', at: [0, -21], scene: 'c8_04', battle: '8-3', after: 'c8_05', g: 'コドクと決着をつける' },
    { t: 'reward', niboshi: 1500, g: '第八章 おしまい' },
  ] },
  { title: 'エピローグ　それから', steps: [
    { t: 'scene', id: 'c9_01', g: 'それから' },
    { t: 'ending', g: 'Fin' },
  ] },
  { title: 'おまけ　ねこ神の夢', hidden: true, steps: [
    { t: 'field', zone: 'dream', at: [0, 20], scene: 'c10_01', battle: '9-1', g: '猫神社の奥から、夢の世界へ' },
    { t: 'field', zone: 'dream', at: [0, 6], scene: 'c10_02', battle: '9-2', g: 'へんてこ回廊を進む' },
    { t: 'field', zone: 'dream', at: [0, -15], scene: 'c10_03', battle: '9-3', after: 'c10_04', g: '夢の玉座へ' },
    { t: 'reward', niboshi: 2000, g: 'おまけ おしまい' },
  ] },
];
const STORY_MAIN = 8;

// シーンに章の名前を付け、舞台（stage）を集める
const SCENE_STAGES = {};
STORY.forEach(ch => ch.steps.forEach(st => [st.id, st.scene, st.after].filter(Boolean).forEach(id => { if (SCENES[id]) SCENES[id].chapter = ch.title.split('　')[0]; })));
for (const [id, sc] of Object.entries(SCENES)) { if (sc.stage) SCENE_STAGES[id] = sc.stage; if (!sc.chapter && id.startsWith('b_')) sc.chapter = '友情の特別イベント'; }

const RECAP = {
  chapters: [
    'ミャオニアの世界。にゃんだーの樹が見えるぽかぽか村から、三毛猫ミケの冒険が始まる。',
    '世界の異変を調べる旅。ミャオ街道で、ふしぎな仲間たちと出会う。',
    '「笑いの国」ニャハハ王国は、誰も笑わない街になっていた。',
    'クロの故郷、くろねこ谷。黒影洞窟の奥に、クロの過去が眠っている。',
    '古代遺跡の壁画が、世界の歴史と、にゃんだーの樹の秘密を語る。',
    '怖い場所のはずなのに、妙にコミカルな魔王領。魔王の城へ。',
    'ぽかぽか村の南にそびえる、にゃんだーの樹。その根元に、黒い何かがいる。',
    '旅で出会った猫たちが集まる。世界中のつながりで、最後の戦いへ。',
    'それから、数年後。',
    'クリア後に見つかる、ふしぎな夢の世界。',
  ],
  scenes: { ...RECAP_1, ...RECAP_2 },
};

// 物語の戦闘の場所（ステージ → 区画の戦場。at は地形マップの区画ならマス座標）
const BATTLE_SETS = {
  '1-1': { zone: 'forest_in', at: [-2, -18], face: 0 },
  '1-2': { zone: 'forest_deep', at: [-4, 0], face: 0 },
  '1-3': { zone: 'rat_nest', at: [0, -2], face: 0 },
  '2-1': { zone: 'road_rest', at: [0, 10], face: 0 },
  '2-2': { zone: 'woods', at: [-6, 0], face: 0 },
  '2-3': { zone: 'road1', at: [12, -2], face: 90 },
  '2-4': { zone: 'road2', at: [0, 4], face: 0 },
  '3-1': { zone: 'tower', at: [10.5, 11], face: 0 },
  '3-2': { zone: 'tower_3f', at: [10.5, 12], face: 0 },
  '3-3': { zone: 'tower_top', at: [10.5, 5], face: 0 },
  '4-1': { zone: 'valley', at: [-4, -12], face: 90 },
  '4-2': { zone: 'cave', at: [14.5, 15.5], face: 0 },
  '4-3': { zone: 'cave_deep', at: [14.5, 4], face: 0 },
  '5-1': { zone: 'ruins_out', at: [-2, 6], face: 0 },
  '5-2': { zone: 'ruins_in', at: [0, 14], face: 0 },
  '5-3': { zone: 'ruins_in', at: [0, -26], face: 0 },
  '6-1': { zone: 'demon_land', at: [0, -8], face: 0 },
  '6-2': { zone: 'demon_castle', at: [11.5, 15], face: 0 },
  '6-3': { zone: 'demon_throne', at: [11.5, 4.5], face: 0 },
  '7-1': { zone: 'tree_root', at: [0, -10], face: 180 },
  '7-2': { zone: 'tree_under', at: [0, -10], face: 180 },
  '7-3': { zone: 'tree_under', at: [0, 20], face: 180 },
  '8-1': { zone: 'pokapoka', at: [0, 12], face: 0 },
  '8-2': { zone: 'world_end', at: [0, 16], face: 0 },
  '8-3': { zone: 'world_end', at: [0, -26], face: 0 },
  '9-1': { zone: 'dream', at: [0, 10], face: 0 },
  '9-2': { zone: 'dream', at: [0, -2], face: 0 },
  '9-3': { zone: 'dream', at: [0, -14], face: 0 },
};

// 最終決戦：コドクが最後の姿になると届く、世界中の猫たちの声
CHAPTERS[7].stages[2].final = { voices: [
  ['キングネズミ', '「魚……分けてやるって言っただろ！　負けるな、勇者！」'],
  ['魚屋のおばちゃん', '「帰ってきたら、焼き魚いくらでも食べさせてやるよ！」'],
  ['ピエロ', '「ぼくのショーの主役は、きみたちだよ！」'],
  ['ニャハハ王', '「笑え、笑うのじゃ！　ぶははははは！」'],
  ['ハヤテ・リン・ゴロウ', '「クロ！　みんな！　行けーーっ！」'],
  ['魔族兵のベル', '「魔王さまーっ！　有給、ありがとうございましたーっ！」'],
  ['村長', '「ミケ！　みんな！　一人じゃないぞ！」'],
] };

// 友情の特別イベント（友情Lv4）と、組み合わせのひとこと紹介
const BOND_EVENTS = {
  'kuro|mike': 'b_kuro_mike', 'mike|shiro': 'b_mike_shiro', 'mike|tama': 'b_mike_tama', 'maou|mike': 'b_maou_mike', 'kuro|shiro': 'b_kuro_shiro',
  'kuro|tama': 'b_kuro_tama', 'shiro|tama': 'b_shiro_tama', 'kuro|maou': 'b_kuro_maou', 'maou|shiro': 'b_maou_shiro', 'maou|tama': 'b_maou_tama',
};
const BOND_TAGS = {
  'kuro|mike': 'ボケとツッコミ', 'mike|shiro': '子ども同士の口げんか', 'mike|tama': '兄弟のよう', 'maou|mike': '勇者と元魔王', 'kuro|shiro': '真面目な二匹',
  'kuro|tama': 'クロがいちばん気にかけている', 'shiro|tama': 'シロが面倒を見る', 'kuro|maou': '無口同士で会話が短い', 'maou|shiro': 'シロの実験台', 'maou|tama': 'おひるね同盟',
};
